Logout Changes #9915
HabitRPG/habitica pull request #10022
Opened 2018-02-19 17:14 UTC by pollaro

#9915 
[//]: # I originally changed the URL the logout went to, but this still was not ideal. Now, I'm checking the server, but the route is not being found

[//]: # 9915
### Changes
[//]: # Change auth on both the client and server to check server side for login info. Express is not finding the new route to check this.

[//]: # 1199bfdc-e1e3-4ffe-af31-444a91746d81

----
UUID:

2018-02-19 17:38 UTC, paglias requested changes

2018-02-19 17:38 UTC, paglias commented on website/client/router.js
> +  const isUserLoggedServer = store.dispatch('auth:loginCheck');
this function is async, you should wait for it with await but it also means a full request will be made for every route change on the client which is indesiderable. You should add a route guard function just to the speicific logout route

2018-02-19 17:39 UTC, paglias commented
The route on the server is correct but you're not awaiting the function correctly. But honestly I'm not sure why you added that route

2018-02-22 12:01 UTC, paglias commented
Looking better! Can you remove the commented out code?

2018-02-22 19:20 UTC, pollaro commented
Sure, I thought I did that. I'll get to it, shouldn't take long...

2018-03-17 21:02 UTC, paglias requested changes

2018-03-17 21:02 UTC, paglias commented on website/client/components/logout.vue
> +<style>
can you remove these empty blocks?

2018-03-17 21:02 UTC, paglias commented on website/client/components/logout.vue
> +  data () {},
data and computed should be removed as they're not used

2018-03-17 21:02 UTC, paglias commented on website/client/store/actions/auth.js
> +  await axios.get('/logoutServer');
this shouldn't also redirect the user to the homepage? So instead of doing axios.get why not use `window.location.href = '/logoutServer';	 `?

2018-03-17 21:02 UTC, paglias commented on website/server/controllers/top-level/auth.js
> +  url: '/logoutServer',
to better follow our urls conventions this should be `/logout-server`

2018-03-19 16:33 UTC, pollaro commented
Ok, I'll get to this in the next few days.

2018-04-04 02:02 UTC, lemoness commented
@pollaro Hi there! How is this fix going?

2018-04-04 02:27 UTC, pollaro commented
Slowly. Sorry, I was sick and in bed for a week, and then out of town. I'll have time tomorrow and Thursday

2018-04-04 20:51 UTC, pollaro commented
I applied the changes paglias suggested. Everything worked ok on my local

2018-05-05 16:22 UTC, Yutsuten commented
@pollaro Just notifying you: there are some conflicts to be resolved.

2018-05-06 19:57 UTC, pollaro commented
Sorry, I didn't see these. I've been trying to find a job.

2018-05-13 13:41 UTC, paglias submitted a review, later dismissed

2018-05-13 13:41 UTC, paglias commented on website/server/libs/spells.js
> -import {
can you revert the changes to this file since they seem unrelated?

2018-05-13 13:41 UTC, paglias commented on website/client/router.js
> +import Logout from './components/logout';
are all these changes necessary?

2018-05-13 13:41 UTC, paglias commented on website/client/app.vue
> +    Logout,
we're importing the logout component here but not using it anywhere, can you remove it?

2018-05-22 23:11 UTC, pollaro commented
Alright, lets give this one a go.

2018-05-25 15:28 UTC, paglias commented on website/server/middlewares/notFound.js
> +  '/logout'
why was this added here? This way if you go to habitica.com/logout the client won't be loaded, maybe you wanted to add /logout-server here?

2018-06-15 22:00 UTC, beffymaroo commented
@paglias @pollaro How's this going? Any label changes or status changes needed?

2018-06-15 22:29 UTC, pollaro commented
Sorry, I've been busy and this got lost in the shuffle. I'll get it in the next day or two

2018-06-21 18:54 UTC, beffymaroo commented
@pollaro Great! Thanks for checking in.

2018-07-11 21:09 UTC, SabreCat commented
app.vue appears to have been committed with merge conflict markers, and there's a bunch of odd irrelevant changes. I'll see if I can figure out how to reconcile them from my end, but @pollaro, you might know better what was an intended change and not!

2018-07-11 21:43 UTC, SabreCat commented
OK, that was messy and a bit forceful, but I think I've got it. @pollaro and @paglias, how does this look? Local test seemed to check out, both visiting /logout and using the Log Out menu option take the user out of app and back to static page.

2018-07-12 06:46 UTC, paglias commented
Looks good @SabreCat , if it works let's merge it!

2018-07-12 15:02 UTC, SabreCat commented
Thanks for this, @pollaro, and welcome to the ranks of the Blacksmiths at tier 1! This will undergo some additional testing in a staging environment, then if all goes well be live around the end of next week.

For contributor tiers, note that tiers require increasing amounts of effort from one to the next, so tier 2 will require multiple PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

2018-07-12 20:07 UTC, merged