Fix #10202 - Fix URL for detaching social auths
HabitRPG/habitica pull request #10207
Opened 2018-03-31 18:29 UTC by ESWAT

### Changes
Sends `DELETE` request when detaching social auth instead of `GET`, as the API expects. This fixes the bug with being unable to detach social auths from your account.

**Note:** I’m haven’t added a notification for this action yet since I’m not aware of how to do it yet. Habitica staff: feel free to take over with that if I haven’t made any subsequent commits for it.

----
UUID: ffee6b77-0bf8-422a-a65c-c20de17f2b32

2018-04-08 13:30 UTC, paglias requested changes
left one comment on how to add the notification, let me know if you have any question!

2018-04-08 13:30 UTC, paglias commented on website/client/components/settings/site.vue
>        // Notification.text(env.t("detachedSocial", {network: network.name}));
to send a notification you can use `this.text(this.$t(stringName))` so in this case

```
 this.text(this.$t('detachedSocial', {network: network.name}));
```

2018-04-11 00:20 UTC, ESWAT commented on website/client/components/settings/site.vue
>        // Notification.text(env.t("detachedSocial", {network: network.name}));
Done.

2018-04-13 13:16 UTC, paglias commented
Thanks for this @ESWAT !

2018-04-13 13:16 UTC, merged

2018-04-13 13:18 UTC, paglias commented
welcome to tier 3!