Snasser2015
HabitRPG/habitica pull request #10268
Opened 2018-04-20 06:50 UTC by shadimoustafa

- **Description**
When in Discover Guilds, the member list number on the left side does not fit in the box if it's over 3 digits.

- **Changes**

Before:
![before_change](https://user-images.githubusercontent.com/35777080/38686114-917a5b98-3e41-11e8-92ec-7db97b51d90c.JPG)

After:
![after_change](https://user-images.githubusercontent.com/35777080/38686119-968860f8-3e41-11e8-9cd6-8cb288375e99.JPG)

----
UUID: 3b853dc8-4a8a-4992-a486-f2e961c71bb4

2018-04-21 15:37 UTC, negue commented
@shadimoustafa Thanks for your PR, but could you revert the changes in `README.MD` and `habitica2.bat`

2018-04-21 15:45 UTC, negue commented
@Tressley what do you think about the size changes ?

2018-04-22 04:53 UTC, shadimoustafa commented
@negue I have manually reverted the changes in README.MD and habitica2.bat. Thanks!

2018-04-23 12:15 UTC, Tressley commented
@negue -- LGTM. 👍

2018-04-26 21:45 UTC, negue commented
@shadimoustafa could you remove the `habitica2.bat`since we don't need an empty batch file ^^

2018-04-27 05:34 UTC, shadimoustafa commented
@negue  done!

2018-04-27 17:34 UTC, paglias requested changes

2018-04-27 17:34 UTC, paglias commented on README.md
> +Team JaMiCaSh - Jason, Michelle, Cameron, Shadi
can you remove this line?

2018-04-27 19:46 UTC, shadimoustafa commented on README.md
> +Team JaMiCaSh - Jason, Michelle, Cameron, Shadi
Sure,  done.!

2018-04-28 15:44 UTC, merged

2018-04-28 15:46 UTC, paglias commented
@shadimoustafa  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!