removing the 24px top margin on .modal-dialog .title
HabitRPG/habitica pull request #10377
Opened 2018-05-19 00:58 UTC by fentie

### Changes
Boss HP and Difficulty on the quest details view are not aligned with their values. Removing the top margin so they line back up again, as discussed in the Aspiring Blacksmiths guild

----
UUID: 8f4a567a-038c-4c48-9941-fea2dc1d2845

cc: @Alys

2018-05-25 10:35 UTC, paglias commented
Thanks! Can you post a screenshot of the changes?

2018-05-25 13:30 UTC, fentie commented
Sure:

<img width="489" alt="screen shot 2018-05-25 at 8 29 00 am" src="https://user-images.githubusercontent.com/273815/40546804-d0e2b958-5ff5-11e8-9b24-e0089bb35837.png">

2018-05-26 19:15 UTC, negue commented
your rule is overridden by `.modal-dialog .title ` , if you add `!important; ` then it will work on every modal

2018-05-26 19:20 UTC, fentie commented
@negue I'm not sure I follow you. Is this a problem on other modals too? This is the only one I noticed.

2018-05-26 20:00 UTC, negue commented
well the `margin-top` rule was overridden on the shop detail modal, also on the inventory items detail modal, so with `!important; ` it really worked everywhere 😄

2018-05-28 01:12 UTC, fentie commented
@negue so I looked at this again and I realized part of the problem/confusion was we were using `.title` in a place where it didn't belong... it has no semantic meaning here, it's just a convenient class with a set of styles that (mostly?) match what the implementer was after.

I redid that section with a `<dl>` instead and gave it only the styles it needed.

2018-05-29 15:43 UTC, negue commented
Could you add a `smallVersion` style, `questInfo.vue` is also used in the popovers of a quest, now it shows the big labels in that popover

2018-05-29 15:44 UTC, negue commented on website/client/components/shops/quests/questInfo.vue
> +  color: #4E4A57;
its better to use the colors from `colors.scss` , for this it would be `$gray-50`

2018-06-09 02:22 UTC, fentie commented
@negue should be back in business now. busy few days!

2018-06-11 09:53 UTC, paglias requested changes

2018-06-11 09:53 UTC, paglias commented on website/client/components/shops/quests/questInfo.vue
> +    font-family: 'Roboto', sans-serif;
this font-family rule can be removed as it's specified at an higher level

2018-06-11 09:53 UTC, paglias requested changes

2018-06-11 09:53 UTC, paglias commented on website/client/components/shops/quests/questInfo.vue
> +  font-family: 'Roboto Condensed';
same here

2018-06-11 14:06 UTC, fentie commented
@paglias updated, rebased, and pushed

2018-06-12 09:29 UTC, paglias commented
this is looking good @fentie, thanks! We're going to merge it at the end of this week or at the beginning of the next one

2018-06-15 08:58 UTC, merged

2018-06-15 08:59 UTC, paglias commented
thanks @fentie ! notated towards your next tier