Fix flicker when user mouses over the very leftmost edge of party member avatar
HabitRPG/habitica pull request #10407
Opened 2018-05-28 15:48 UTC by haydenbetts

Fixes #10379 

### Changes
Add one pixel of margin-right to the .member-stats class.

Video Before: https://drive.google.com/file/d/1q7ONERmRuZXTo5VVq6GQ9sv_DHUAQSJj/view
Video After: https://drive.google.com/open?id=1FSM-PFIjGzr1yEvs6OkjQ2vcQaUKd5i6

2018-05-28 19:19 UTC, haydenbetts commented
@paglias @SabreCat @TheHollidayInn How do I run the client side unit tests (those in `/test/client/unit`) locally? I don't see any documentation about it on the wikia.

2018-05-28 20:28 UTC, paglias commented
non run client:unit is the command to use!

2018-05-29 09:47 UTC, paglias requested changes

2018-05-29 09:47 UTC, paglias commented on test/client/unit/specs/components/memberDetails.js
> +import Vue from 'vue';
there are several linting errors here https://travis-ci.org/HabitRPG/habitica/jobs/384875487

2018-05-30 04:27 UTC, haydenbetts commented
@paglias - I am having some trouble mounting the `MemberDetailsComponent` for unit testing. 

Among other errors I am getting:
`Missing required prop: "member"`
 
when I run `npm run client:unit`

Is this error occurring because the `member` object would usually be fetched from the store, and my unit tests do not have access to the store? Would it be possible to set a default `member` prop directly with some sample data?

2018-05-30 12:11 UTC, paglias commented
@haydenbetts no worries about questions :) Yeah it looks like you need to pass the `member` prop to the component in tests, you can see some examples of passing props to tests here https://github.com/HabitRPG/habitica/blob/develop/test/client/unit/specs/components/categories/categoryTags.js#L9 but I think in this case this may be the easiest way: https://github.com/HabitRPG/habitica/blob/develop/test/client/unit/specs/components/ui/drawer.js#L13

2018-06-21 20:30 UTC, SabreCat commented
Setting up a client test for 1px margin of CSS seems like overkill, here. @paglias @TheHollidayInn what do you think about removing the test and merging just the layout fix?

2018-06-22 09:56 UTC, paglias commented
@SabreCat I'm fine with removing the test and merging the pr!

2018-06-22 19:09 UTC, SabreCat commented
@haydenbetts We're on a temporary hold for merges into `develop` this week because of a breaking change we're working on, but this will get merged once our staging environment is out of code freeze. Do you have a Habitica UUID we can award contributor credit to?

2018-06-27 17:07 UTC, merged