Remove "add multiple" tip once a task has been added (fixes #10440)
HabitRPG/habitica pull request #10459
Opened 2018-06-19 12:11 UTC by thefifthisa

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10440

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

The tip is hidden after the Enter key has been pressed and no longer prevents the user from editing a new task immediately.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 9ca2bb65-ce6c-4e4c-a367-5ef9b5c7421e

2018-06-19 14:44 UTC, paglias requested changes

2018-06-19 14:44 UTC, paglias commented on website/client/components/tasks/column.vue
> +      v-model="quickAddText", @keypress.enter="quickAdd($event); quickAddFocused = false",
the code looks good but I think the `quickAddFocused = false` should be moved inside the quickAdd function, we try to keep code in templates to the minimum

2018-06-21 03:26 UTC, thefifthisa commented on website/client/components/tasks/column.vue
> +      v-model="quickAddText", @keypress.enter="quickAdd($event); quickAddFocused = false",
Done!

2018-06-27 17:08 UTC, merged

2018-06-27 17:17 UTC, paglias commented
thanks @thefifthisa! This has been notated towards your second tier