changed @mentioning-auto-complete from text- to caret-based.
HabitRPG/habitica pull request #10638
Opened 2018-08-26 09:39 UTC by legitmaxwu

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9694

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
The bugs described in #9694 were mainly due to the `@mentioning` autocomplete only checking the end of an inputted message for possible tags. Autocomplete suggestions were also only added when the message text itself was edited.

I changed the code so that the autocomplete suggestions update based on caret position instead, similar to how Facebook handles `@mentioning`. The autocomplete suggestions should now be reactive to everything (clicking around on the inputted text, using arrow keys to move the caret, etc.), not just the text itself being updated. This change addresses the bugs in #9694.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 215e51f6-beb1-4617-b359-fcb09681e6fd

2018-08-26 17:51 UTC, legitmaxwu commented
added a sliver of code to slightly optimize performance. when checking for an '@' symbol, the while loop will exit if it encounters a space (names are not supposed to have spaces in them).

I noticed that some names in the tavern actually do have a space in them though. How does that happen? Were they specially assigned?

2018-08-26 18:13 UTC, legitmaxwu commented
Sorry for adding so many commits. Is there any way to run the travis-ci tests locally?

2018-08-26 21:38 UTC, Alys commented
Profile names are allowed to have spaces in them and many do.

2018-08-26 21:41 UTC, Alys commented
The full test suite can be run locally. I'm on my phone so I can't find a link easily but look at the section about tests in the wiki page Using Your Local Install To.... (search those words to find the page).

2018-08-26 22:32 UTC, legitmaxwu commented
Oh snap, I will edit my code then to account for spaces. The original code did not handle spaces for tagging so I was confused there.

2018-08-27 01:56 UTC, Alys commented
Ah yeah, I should have said, sorry, it's a known problem that @ tagging doesn't work the same for players with spaces in their profile names, and since it's a pre-existing problem that's not directly related to the issue you're solving, I don't think you should feel obliged to fix it too.

In particular, if a fix to handle spaces in names turns out to make the message box less responsive / slower, I think we'd prefer to not have the fix. Also, at some future time, probably not too far away, there'll be a different kind of change that will remove the problem of @ tagging someone with spaces in their profile name, so it might be best to ignore it now. :)

2018-08-27 01:57 UTC, Alys commented
But thank you for considering it and being willing to fix it!

2018-08-27 02:31 UTC, legitmaxwu commented
@Alys maybe we could save the space problem for another day. When you change your profile name to something like "Name____123" (with more than 1 space), it shows as 1 space on the Chat Card, but when someone wants to mention you, they actually need to type extra spaces.

I think it would be good to add code to reduce repeated spaces down to 1 space during profile-name-changing itself. So if I wanted to change my name to "Name____234," the system wouldn't let me and automatically make it "Name 234." (This is done on the Chat Card anyways so it shouldn't hurt, right?)

If this is done, then we can come back to this issue and fix it to handle spaces. I wrote code to handle spaces already, but if I change my name to "test2___xD" and "test2 xD" and send a message under each of these names, then the autoselection treats the names as different and we have duplicates as shown below. (They still show up in the dropdown as "test2 xD," but one of them is actually "test2___xD" with extra spaces.

![image](https://user-images.githubusercontent.com/19853022/44637481-2528f680-a966-11e8-87de-cfe74b470930.png)

Basically, it looks kind of weird so I think we should just not handle spaces for now.

(Pretend underscores are spaces, Github won't let me put multiple spaces in a row either)

2018-08-27 04:19 UTC, Alys commented
> I think we should just not handle spaces for now.

I agree! I think that's the best approach.

The other change that I hinted at earlier will probably make the profile name space problem completely redundant so collapsing 2+ spaces to 1 won't be necessary then. Sorry about the air of mystery that I'm adding to this but that other change is still in progress. :)

2018-08-27 04:44 UTC, legitmaxwu commented
Coolio, I guess that the current pull request is ready for review then!

@Alys haha now I'm curious.

2018-08-28 00:43 UTC, legitmaxwu commented
accidentally used two variables for something that needed only 1, so i fixed it.

2018-08-29 15:38 UTC, negue requested changes
could you fix those two? then I'll take a look again

2018-08-29 15:38 UTC, negue commented on website/client/components/chat/autoComplete.vue
> +      while (this.text[startIndex] !== '@' && startIndex >= 0) {
could you extract the search for the correct startIndex to a method?

2018-08-29 15:38 UTC, negue commented on website/client/components/chat/autoComplete.vue
> +      let newText = this.text.slice(0, this.currentSearchPosition) + result + this.text.slice(this.currentSearchPosition + index - startIndex);
did you had another variable `index` during development? cause it doesn't exist anymore ^^

```
Uncaught ReferenceError: index is not defined
    at VueComponent.select (webpack-internal:///2130:103)
    at click (webpack-internal:///2348:18)
    at invoker (webpack-internal:///27:2022)
    at HTMLDivElement.fn._withTask.fn._withTask (webpack-internal:///27:1821)
```

2018-08-29 17:04 UTC, legitmaxwu commented
@negue fixed!

2018-08-30 15:10 UTC, negue commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
could you remove this file ?

2018-08-30 15:23 UTC, negue commented
I have two issues:

1. press `@` 
2. select a name
3. the textarea has los the focus, so you cannot begin to write your message right after


the other issue, if you have a user named `test`:

1. the message already contains a mention`@otherUser hi`
2. you press `@` before the other mention, write `te`
2. select the user `test`
3. you'll see `@testte`

2018-09-07 01:32 UTC, legitmaxwu commented
@negue fixed both errors!

However, the caret will always move to the end of the text when the textarea refocuses. I could not figure out how to move the caret to where it was before the user selects the autocompletion.

One note is that putting a setSelectionRange() function call in the selectedAutoComplete function does not work because it is overridden by some other function that I couldn't identify. If you try this approach, the caret will only move to the right position if selecting the autocomplete does not update any text. (i.e. typing in @testUser and then clicking "textUser" as a selection).

Any ideas on how to fix this? Of course, most tags will happen at the end of the text message anyways so this is not a huge issue.

2018-10-12 18:35 UTC, legitmaxwu commented
Hello, I was wondering if there are any updates/feedback on this pull request?

2018-10-13 19:43 UTC, paglias requested changes

2018-10-13 19:43 UTC, paglias commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
yeah this file should be removed

2018-10-13 19:43 UTC, paglias commented on website/client/components/groups/chat.vue
> +      async selectedAutocomplete (newText) {
why `async` here? there are no `await`ed calls

2018-10-13 19:44 UTC, paglias commented
Hey @legitmaxwu sorry for the delay, I've left two comments but I'm having some issues replicating the bugs in the first place, the list of usernames always disappear for me. Also can you give a look at the conflict?

2018-10-14 10:44 UTC, paglias commented
I was able to reproduce the issue and after fixing the conflicts your PR works well! 

Regarding `setSelectionRange` being overridden isn't that due to `updateCarretPosition`?

I think the issues comes from mixing Vue's code (with its own DOM modification) and normal DOM functions like `appendChild`, ... it's usually fixed by using for everything Vue's directives

2019-09-09 15:25 UTC, paglias commented
Hi @legitmaxwu , I was wondering if you had any update on the status of this PR. thanks!

2019-09-20 15:00 UTC, paglias commented
I'm going to close this but if you want to work on it just let me know! Also since it's some good work I'll link to it in the issues in case it's useful for some future fixes

2019-09-20 15:00 UTC, closed without merging