Disabled messaging to blocked and deleted users
HabitRPG/habitica pull request #10878
Opened 2018-11-28 18:56 UTC by nikkigabbard

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_#_and_issue_numer_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

2018-11-28 18:57 UTC, nikkigabbard commented
issues #9247 and #9989

2018-11-29 02:40 UTC, Alys commented
@nikkigabbard Thanks for submitting this! I've edited the top post to replace "Fixes put_#_and_issue_numer_here" with the issue numbers (also in the title). Can you please edit it to add your User ID (the 36-character string from the Settings > API page in the website) and to write a description of the change? Please also include screenshots of any visible changes to the website. See [Submitting your Change for Review in a Pull Request](https://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica's_Website_and_API#Submitting_your_Change_for_Review_in_a_Pull_Request) (step 4) for details about what's helpful.

2018-12-04 09:31 UTC, paglias requested changes

2018-12-04 09:31 UTC, paglias commented on .gitignore
> +package-lock.json
can you remove this?

2018-12-04 09:31 UTC, paglias commented on test/api/unit/libs/cron.test.js
> +    it('does nothing to plan stats when we are after the last day of the cancelled month', () => {
can you revert the changes to the excluded tests? Thanks!

2018-12-04 14:19 UTC, Tressley commented
@nikkigabbard -- Thank you for your work on this! We actually have updated designs for the Inbox and how better to handle these use cases. Rather than contain the error message in a snack notification, we prefer it's displayed clearly in the Inbox. I've included some screenshots for a quick reference.

![image](https://user-images.githubusercontent.com/2686586/49447820-70447800-f7a5-11e8-816e-c413d5e2ca79.png)
![image](https://user-images.githubusercontent.com/2686586/49447899-a4b83400-f7a5-11e8-9406-f1dd6d4a9c42.png)

If you'd like to make these updates, I can invite you to our Zeplin project (where we house designs for hand-off). I'll just need you to share your email.

2019-09-09 15:29 UTC, paglias commented
hi @nikkigabbard ! do you have any update on the status of this pr? thanks!

2019-09-20 15:06 UTC, paglias commented
Hi @nikkigabbard I'm going to close this one but if you want to work on it just leave a comment

2019-09-20 15:06 UTC, closed without merging