Fix #10907 - Removes Grey Disabled style from Challenge Progress
HabitRPG/habitica pull request #10973
Opened 2019-02-02 19:50 UTC by Mira-M

- Includes a fix that displays task styles based on tab location
- Adds unit test coverage to ensure styles exist (do not exist) depending on location
- Fixes #10907 

### Changes

Approach:
Since the behaviors were different depending on the location, I passed the route's path name to the task class creation functionality so that it was aware of where the request originated.  I was then able to ensure that todo and daily tasks originating from the challenge page did not get the disabled style applied. 

I added unit tests testing the functionality from the tasks page, the guild/group task board and the challenge page.

#### Before

![image](https://user-images.githubusercontent.com/5703010/52168481-fc691200-26f8-11e9-99ca-a460fe4b81c1.png)

#### After

![image](https://user-images.githubusercontent.com/5703010/52168456-98464e00-26f8-11e9-9354-b94edd1530d7.png)

![image](https://user-images.githubusercontent.com/5703010/52168534-6d102e80-26f9-11e9-87d6-93394cfa7e17.png)

#### Regression: User Tasks View (Completed Todo/Daily Tasks are still grey)
![image](https://user-images.githubusercontent.com/5703010/52168506-36d2af00-26f9-11e9-970a-da9e2c9930cd.png)

----
UUID: 

ca561633-c0bb-4544-adf4-dda0aaa23795

2019-02-05 21:11 UTC, negue requested changes
I think using the route to determine the list to change the colors isn't really the right way, like what if we get another view which is on the same route as tasks just on a different modal or something then this would break it right away, I'd suggest to use a fix enum (or string) on each task list

2019-02-05 21:11 UTC, negue commented on website/client/store/getters/tasks.js
> +            if (!(loc === 'challenge')) {
this could be `loc !== 'challenge'` ^^

2019-02-05 21:11 UTC, negue commented on website/client/components/tasks/task.vue
> +      return this.getTaskClasses(this.task, 'control', this.dueDate, this.$route.name);
I think this `this.$route.name` should come from a prop of `task.vue` itself so that its not based on the route

2019-02-05 23:31 UTC, Mira-M commented
> I think using the route to determine the list to change the colors isn't really the right way, like what if we get another view which is on the same route as tasks just on a different modal or something then this would break it right away, I'd suggest to use a fix enum (or string) on each task list

Thanks for the feedback.  Just a bit of clarification, are you saying that we shouldn't use the origin in general to determine the styles, or that the origin shouldn't be populated from `this.$route`?

> I'd suggest to use a fix enum (or string) on each task list

Are you saying that the origin (or some flag of some sort) should be added to the task list itself and then use that to decide which styles to be applied?  I ask because this was my original approach and there were other side effects of doing this where for some reason Todos were being stubborn and the flag wasn't toggling, but this was not the case with dailies.

> like what if we get another view which is on the same route as tasks just on a different modal or something then this would break it right away

I considered this, and thought that since I was ignoring any changes not related to challenges it would be ok, I also added unit tests that should catch if the styles were not as expected.  Next time I'll ask if the approach would be sufficient 🦄 

I apologize in advance for the "duh" questions =^.^=

Nonetheless, I can return to that approach and report any specifics I'm seeing in that behavior instead.  I'll be able to get to it this weekend. Thanks for the info! 😻

2019-02-06 06:45 UTC, negue commented
> > I think using the route to determine the list to change the colors isn't really the right way, like what if we get another view which is on the same route as tasks just on a different modal or something then this would break it right away, I'd suggest to use a fix enum (or string) on each task list
> 
> Thanks for the feedback. Just a bit of clarification, are you saying that we shouldn't use the origin in general to determine the styles, or that the origin shouldn't be populated from `this.$route`?

Sorry for the cryptic responds^^, I meant to say that using the route could lead to potential weird bugs in the long run, using an enum/string would be a bit 'stronger' against that (see the answer below)

> 
> > I'd suggest to use a fix enum (or string) on each task list
> 
> Are you saying that the origin (or some flag of some sort) should be added to the task list itself and then use that to decide which styles to be applied? I ask because this was my original approach and there were other side effects of doing this where for some reason Todos were being stubborn and the flag wasn't toggling, but this was not the case with dailies.

Yes, a fixed source added by code (instead of the variable route) should be the way to go. I mean you can use the current code (well with a bit more around it) and then it should work as it does right now.

Maybe this side effect happened of something else? Hard to guess anything without the code back-then

> 
> > like what if we get another view which is on the same route as tasks just on a different modal or something then this would break it right away
> 
> I considered this, and thought that since I was ignoring any changes not related to challenges it would be ok, I also added unit tests that should catch if the styles were not as expected. Next time I'll ask if the approach would be sufficient 🦄

The test is already correct, you just need to give this 'challenge' flag to the outer task-list itself and then this is good to go ^^

2019-06-15 13:26 UTC, Alys commented
As @Mira-M says at https://github.com/HabitRPG/habitica/issues/10907#issuecomment-502362635 this PR is available for someone else to pick up.

2019-09-09 15:31 UTC, paglias commented
I'm going to close this one.

2019-09-09 15:31 UTC, closed without merging