Inbox: Add API to list conversations
HabitRPG/habitica pull request #11110
Opened 2019-04-08 20:36 UTC by negue

2019-04-14 15:48 UTC, paglias commented on website/server/libs/inbox/index.js
> +    findObj.uuid = options.conversation;
added an index for this

2019-04-14 15:52 UTC, paglias requested changes
left a couple of comments but overall looks good, sorry for the delay!

2019-04-14 15:52 UTC, paglias commented on website/server/controllers/api-v4/inbox.js
> +api.conversations = {
can you add some apidoc comments for this?

2019-04-14 15:52 UTC, paglias commented on test/api/v4/inbox/GET-inbox-conversations.test.js
> +    expect(result[0].username).to.be.equal(user.profile.name);
this should check for the username instead of the profile name?

2019-04-14 15:52 UTC, paglias commented on website/server/libs/inbox/index.js
> +    .exec();
I think to make it a bit faster it might be worth to use `.lean()` here

2019-04-15 18:02 UTC, negue commented
@paglias any idea why the test passes sometimes and other times it returns the wrong order ?

2019-04-15 18:03 UTC, paglias commented
which test @negue? do you have a link to the travis build?

2019-04-15 18:13 UTC, negue commented
This test => https://github.com/HabitRPG/habitica/pull/11110/files#diff-6d0b7cf49acf3d515cfeecb237024e64R37

I ran it multiple times locally, it may works and may not ... which is weird with the same code :D 
Travis => https://travis-ci.org/HabitRPG/habitica/jobs/517471325#L843

2019-04-15 18:53 UTC, paglias commented
Hmm looks like the sorting isn't stable? maybe try to sort by _id here https://github.com/HabitRPG/habitica/pull/11110/files#diff-ebb5855000db09391acfb6b15aed8fc5R62

2019-04-24 17:14 UTC, negue commented
@paglias 

I tried another approach, load the conversations and sort those after, but even this doesn't seem to work.

Filter by `_id` wouldn't work either since the ids are random and not counting from 0 ^^

2019-04-24 19:47 UTC, paglias commented
Hmm ok, I'll give it a look tomorrow!

2019-04-25 20:34 UTC, paglias commented
@negue should be working now

2019-04-26 15:39 UTC, negue commented
@paglias awesome :> guess I used the wrong the orderBy syntax ...

 is there anything left for this api change?

2019-04-26 16:45 UTC, paglias commented
Nope, merging now

2019-04-26 16:45 UTC, merged