Fix challenge update
HabitRPG/habitica pull request #11148
Opened 2019-05-02 16:11 UTC by HydeHunter2

Fixes an issue that we discussed via email (@phillipthelen is aware)

----
UUID: af1477b6-509a-4611-b851-d7a8e3a9c02a

2019-05-02 20:00 UTC, paglias requested changes
@HydeHunter2 thanks! The changes look good but since we already have a list of fields that cannot be updated at https://github.com/HabitRPG/habitica/blob/develop/website/server/models/challenge.js#L65 could you add `leader` there?

2019-05-03 04:59 UTC, HydeHunter2 commented
Oh yes, this is a better solution

2019-05-03 13:34 UTC, paglias approved these changes

2019-05-03 13:35 UTC, merged

2019-05-03 13:40 UTC, paglias commented
Thanks a lot @HydeHunter2 for the investigation and the fix, notated in your profile, welcome to the 3rd tier :)

2020-07-29 13:12 UTC, Alys commented
Recently I had to track down why this change was made so I figure I may as well share what I found. :) It was done to fix a vulnerability - that's why the pull request does not give details (quite correctly). Since it's been merged though, it's no longer a security risk to reveal the details, so here are excerpts from the email in which HydeHunter2 kindly told us about the vulnerability they found:

> I found an exploit that allows you to add any challenge to anyone.  I.e. this exploit can for example:
> - Publish a public challenge on behalf of the admin.
> - Spam tab "my challenge" to someone.
> 
> The vulnerability is that when updating the challenge, Leader has the ability to change any challenge parameters (including the leader's UUID) via a PUT request to the server at /api/v4/challenge/{Challenge_ID}
> 
> Thus, an attacker can create a challenge of any content, and then "update" the leader to any other user. 
>....
> Thus, an attacker can:
> - Create phishing challenges on behalf of the administration.
> - Spam the "My challenge" tab to someone.
> - And so on..



It was originally intentional that a challenge owner be able to select a new owner, and there are still cases where that would be useful, but as HydeHunter2 realised, the ability to change the leader without the new leader's permission made this feature too open to abuse.