Only includes backticks if they haven't been already included. Fixes …
HabitRPG/habitica pull request #11250
Opened 2019-06-30 11:54 UTC by Scens

…the problem.

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11202 
<img width="855" alt="Screenshot 2019-06-29 at 19 04 38" src="https://user-images.githubusercontent.com/15756047/60396144-f0656d00-9b3d-11e9-9bf3-2628c6fb0777.png">

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Affects only messages created by translateMessage function in /website/server/libs/chat/group-chat.js. There doesn't seem to be any other case of displaying double backticks.

Code only includes backticks if they haven't been already included (because they might have been hardcoded in questContent.json).

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

2019-07-09 10:18 UTC, paglias commented
Hi @Scens  and thanks for the PR! Sorry for the delay here but we'll review the pr soon

2019-07-09 14:17 UTC, paglias requested changes
left two small comments!

2019-07-09 14:17 UTC, paglias commented on website/server/libs/chat/group-chat.js
> +  if (!msg.includes('\`')) {
is the backslash here necessary?

2019-07-09 14:17 UTC, paglias commented on website/server/libs/chat/group-chat.js
> +      msg = `${shared.i18n.t('chatQuestStarted', {questName: questScrolls[info.quest].text(lang)}, lang)}`;
this looks good but here like in other messages below given that the string is only the result of the i18n.t call it's not necessary to use the backslashes, so

> msg = `${shared.i18n.t('chatQuestStarted', {questName: questScrolls[info.quest].text(lang)}, lang)}`;

can be

> msg = shared.i18n.t('chatQuestStarted', {questName: questScrolls[info.quest].text(lang)}, lang);

2019-08-07 12:30 UTC, Scens commented
> left two small comments!

Thanks! You are right, I have taken care of these. I've tested this again and everything works fine.

2019-08-15 15:10 UTC, merged

2019-08-15 15:13 UTC, SabreCat commented
Thanks, @Scens! This will go live on the production site around this time next week. Credited toward your second Blacksmith tier!