WIP: Private Messages search &API
HabitRPG/habitica pull request #11972
Opened 2020-03-14 18:21 UTC by negue

This is a WIP to add the ability:
- [x] to search for a specific message in all conversations
  - [x] reloads the conversations sidebar
  - [x] on the conversation selection it only lists the messages that contain the search string
- [x] ability to jump to the context
  - [x] resets the search mode, reloads the normal conversations
  - [x] reload the messages-lists to 10 messages before (including the selected message)
- [ ] load newer messages 
- [ ] jump to recent messages (reset to current behavior)

2020-03-14 19:12 UTC, paglias requested changes
couple of comments about indexes so we won't forget

2020-03-14 19:12 UTC, paglias commented on website/server/libs/inbox/conversation.methods.js
> +    matchQuery.text = searchRegex;
will this require a new index?

2020-03-14 19:12 UTC, paglias commented on website/server/libs/inbox/index.js
> +    findObj.timestamp = Object.assign(findObj.timestamp || {},
index?

2020-03-14 19:15 UTC, negue commented on website/client/src/components/messages/messageList.vue
> +    <div class="row loadmore">
extract as a component? (same as load earlier messages)

2020-03-14 19:15 UTC, negue commented on website/client/src/pages/private-messages.vue
> +// import filter from 'lodash/filter';
clean up

2020-03-21 18:35 UTC, negue commented on website/client/src/pages/private-messages.vue
> +        [o => moment(o.date).toDate()], ['desc']);
parsing string to moment to date really needed? using the normal string to order would probably sort the same?

2020-03-21 18:37 UTC, negue commented on website/server/libs/inbox/shared.methods.js
> +    $or: [
added user/username , I don't know if these have an index already?

2020-04-04 13:18 UTC, closed without merging