Vue component unit test isolation
HabitRPG/habitica pull request #12154
Opened 2020-05-03 06:04 UTC by benkelaar

Fixes unit test isolation for Vue.js component unit tests

While working on a solution for #10786 I started to write a unit test for the `home.vue` component. That went fairly smoothly but after I had added it I noticed that stray events from the home.vue localVue I created ended up failing random other tests. Clearly test isolation was failing. I still haven't figured out exactly why. My standing theory is that the await on the `setValue(value)` somehow doesn't completely wait on the events that are being fired by dispatch because it's not marked as an asynchronous function itself. I think this lack of a-synchronicity somehow breaks the Promise chain. In any case adding the async keyword to the dispatch function seems to fix the test isolation issues.

I'm also tracking down the different stacktraces that are being thrown by Vue.js component unit tests, because they unnecessarily confuse investigations into what is happening. Shall I add those to this merge request or shall I create a new merge request for that?

### Changes
Most significant change is the addition of the `async` keyword to the `dispatch` function in `/src/libs/store/index.js`

Beyond that:
- Added unit test for `home.vue` component
- Small cleanup in `home.vue`
- Replaced use of `zone` by `utcOffset` in `/src/store/index.js`
- Couple other touchups.

----
UUID: d71d2c57-a73d-4591-b64d-e688584a9092

2020-05-03 07:05 UTC, benkelaar commented
Did a quick check of the usages of dispatch. It looks like all usages either don't care about the return value of dispatch or already handle it via either `await` or promise stacking.

2020-05-03 20:28 UTC, paglias requested changes
left two comments but otherwise looks good 👍 It would also match Vuex's own behavior of always returning a promise from a call to dispatch

2020-05-03 20:28 UTC, paglias commented on website/client/src/store/index.js
> +const browserTimezoneOffset = -moment().utcOffset();
This probably works well but I think we'll switch all together in one go with the remaining usages of `.zone()` as described in https://github.com/HabitRPG/habitica/issues/10209

2020-05-03 20:28 UTC, paglias commented on website/client/tests/unit/mixins/groupsUtilities.spec.js
> +Vue.use(Store);
should this use a local Vue instance like in the other test?

```
const localVue = createLocalVue();
localVue.use(Store);
```

2020-05-03 22:21 UTC, benkelaar commented on website/client/tests/unit/mixins/groupsUtilities.spec.js
> +Vue.use(Store);
Yeah I think so, but there's quite a varied amount of approaches in the different Vue.js component tests. Didn't want to open the pit of unifying them all. This however was required for me to get the tests to run at all. However, perhaps this is no longer necessary, will check.

2020-05-04 20:51 UTC, benkelaar commented on website/client/src/store/index.js
> +const browserTimezoneOffset = -moment().utcOffset();
Cool, will revert for this one.

2020-05-04 20:52 UTC, benkelaar commented on website/client/tests/unit/mixins/groupsUtilities.spec.js
> +Vue.use(Store);
Alright, got it to work with localVue. Indeed better.

2020-05-05 14:20 UTC, merged

2020-05-05 14:20 UTC, paglias commented
thanks @benkelaar ! noted in your profile