Only show attainable and owned special pets/mounts
HabitRPG/habitica pull request #12206
Opened 2020-05-16 18:19 UTC by fmaximus

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9498

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Extend specialPets and specialMount with canFind attribute.
Only show special pets and mounts that can be obtained, or are owned.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: c4d64716-9f93-4356-a436-0df52dbf44d5

2020-05-19 15:41 UTC, paglias requested changes
The code is working but this result in an API change for the Content API (habitica.com/api/v4/content) that we cannot accept as it's a breaking change. In particular the `specialPets` and `specialMounts` objects would go from being maps of strings to maps of objects. 

Maybe we could instead a new key to the petInfo or mountInfo maps saying if the pet/mount can be shown or not? Additions of new properties aren't breaking changes

2020-05-20 13:32 UTC, paglias commented on website/client/src/components/inventory/stable/index.vue
> +            if (this.content[`${type}Info`][specialKey].canFind || isOwned('mount', this, userItems)) {
I think having the `if` here and not as a function in the animal item like `isOwned` a few lines below means that to get a new pet to show up a full refresh or page change is necessary. Why not add a new method below `canFind` that makes the check and is used with a `v-show` or `v-if` in the template?

2020-05-20 13:33 UTC, paglias commented
I'm not able to test the correct behavior, added a special pet which is not findable to my test user items but it doesn't show up

<img width="1237" alt="Schermata 2020-05-20 alle 15 28 38" src="https://user-images.githubusercontent.com/589911/82451723-ab785b00-9aae-11ea-8a4f-8787b7c8a4ad.png">

2020-05-25 20:54 UTC, fmaximus commented
With latest commit, I have verified that adding an unfindable pet to a user in mongodb,
will show the new pet after a sync.

2020-05-31 20:08 UTC, merged

2020-05-31 20:09 UTC, paglias commented
thanks @fmaximus ! noted towards your 3rd tier