[WIP][Fixes Issue #12256] New variable addition & new FormatUser instance. Fixes Slack Notification Email Error
HabitRPG/habitica pull request #12330
Opened 2020-06-23 16:14 UTC by ksschmi

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes issue 12256

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
InboxChatReport.js: 
(line 35): .exec() appended to function call
(line 91): A variable for the recipient email was created
(line 63): this variable was passed to the Slack.SendInboxFlagNotification function. 
Slack.js:
(line 148-152): New formatUser instance created to hold recipient information
(line 158): The recipient is set to the new formatUser instance
(line 114): A variable that holds the recipient email is added as a parameter to the sendInboxFlagNotification function

Passes all local tests & unit tests. 
[WIP] still needs manual testing by moderators who receive the Slack notifications. The case in which a sender of a PM reports the PM needs to be checked. 
----
UUID: 199d9490-2253-49c3-9ff0-031937bc0ac9

2020-06-27 14:10 UTC, paglias commented
Hi @ksschmi , saw your comment on the original issue, is this PR ready? should it be closed? thanks

2020-06-27 14:42 UTC, paglias requested changes

2020-06-27 14:42 UTC, paglias commented on website/server/libs/chatReporting/inboxChatReporter.js
> +    // added .exec() to the end of line 35 as suggested by @paglias
can we remove these comment? Comments should be used when they add extra information that might be useful to understand what the code is doing not to explain changes made as part of the PR

2020-06-27 14:42 UTC, paglias commented on website/server/libs/slack.js
> +import ChatReporter from './chatReporting/chatReporter';
ChatReporter has been imported but it's never used

2021-04-30 20:48 UTC, SabreCat commented
Looks like this was addressed in a later PR while we were waiting for updates. Closing!

2021-04-30 20:49 UTC, closed without merging