Prevent the removal of a quest owner from a group, take 2
HabitRPG/habitica pull request #12695
Opened 2020-10-19 18:32 UTC by thewilloftheshadow

Remake of #12680 but with the Pull app uninstalled

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12398

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
This change will throw an error for the `/groups/:groupId/removeMember/:memberId` API route if the user that is being removed is the owner of the quest
This change adds a new string for the new error with the key `cannotRemoveQuestOwner`

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2eb203f5-1b1e-4e5d-84a4-22f130a1090e

2020-10-20 12:39 UTC, paglias requested changes
@thewilloftheshadow thanks for the PR! The code is looking good, could you add an integration test that covers this new behavior? See https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/integration/groups/POST-groups_id_removeMember.test.js and let me know if you need any help

2020-10-20 13:16 UTC, thewilloftheshadow commented
It's been a while since I've been written any tests but I'll give it a go!

2020-10-21 10:45 UTC, thewilloftheshadow commented
Ok, I wrote a test, and it ran both on my machine and [on the CI tests](https://github.com/HabitRPG/habitica/pull/12695/checks?check_run_id=1286198229#step:8:621)

2020-10-23 16:42 UTC, paglias requested changes
two small issues then it's ready to go!

2020-10-23 16:42 UTC, paglias commented on website/server/controllers/api-v3/groups.js
> + * @apiError (400) {NotAuthorized} cannotRemoveQuestOwner Group leader cannot remove
the code here is 401 not 400, I think there was a mistake in the previous docs. NotAuthorized is 401, BadRequest is 400

2020-10-23 16:42 UTC, paglias commented on test/api/v3/integration/groups/POST-groups_id_removeMember.test.js
> +          code: 403,
code should be 401,

```
      code: 401,
      error: 'NotAuthorized',
      message: t('cannotRemoveQuestOwner'),
```

2020-10-23 20:34 UTC, thewilloftheshadow commented
Fixed, and I changed the other NotAuthorized codes to 401 in the apidoc headers as well

2020-10-26 09:46 UTC, merged

2020-10-26 09:48 UTC, paglias commented
@thewilloftheshadow  thanks for this PR! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

2020-10-27 00:10 UTC, thewilloftheshadow commented
Awesome, thanks! I definitely plan on sticking around, that was fun!