Add questOwner to webhook.js
HabitRPG/habitica pull request #13045
Opened 2021-02-10 22:49 UTC by PitiTheGrey

Adds questOwner:UUID to the json response of a webhook

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)
This is the discussion:
https://github.com/HabitRPG/habitica/issues/12931
### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

2021-04-22 08:02 UTC, PitiTheGrey commented
Please excuse me. I am just curious if there is any progress here.

2021-04-29 20:14 UTC, SabreCat commented
This should work fine, but could we add this data field to the expectations for webhook behavior in the relevant integration tests? See e.g. https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/integration/quests/POST-groups_groupId_quests_invite.test.js#L238-L241

2021-04-29 20:57 UTC, SabreCat requested changes
Needs some simple test expectation updates, otherwise good to go

2021-04-29 22:05 UTC, PitiTheGrey commented
Not sure if my commit conflicts with https://github.com/HabitRPG/habitica/pull/13111 
from 2 hours ago?

2021-04-29 22:22 UTC, SabreCat commented
> Not sure if my commit conflicts with #13111 from 2 hours ago?

Nope, that PR has to do with _when_ we send the webhook, while yours changes the _content_ of the webhook, so there's not a conflict!

That said, the new test appears to be failing. Does the `quest` object the webhook receives actually contain a value for `leader`?

2021-05-16 21:42 UTC, PitiTheGrey commented
Please delete in favour of #13277

2021-05-28 21:01 UTC, closed without merging