Fix casting items on parties that exceed it limit by showing Load More Button
HabitRPG/habitica pull request #13509
Opened 2021-09-15 22:59 UTC by dabrowskif

fixes #13394

### Changes

This PR contains 4 commits.

1. st commit: **Fix party size and notification when inviting**
- [ ] Which files: `website/server/models/group.js` && `website/common/script/constants.js`
- [ ] Description: During development i noticed that party limit is actually 31, not 30, as it supposed to be, because party leader wasn't included previously. Code is pretty self-explanatory

2. nd commit: **Fix View Party button in header**

- [ ] Which files: `website/client/src/components/header/index.vue`
- [ ] Description: During development i noticed that when clicking View Party button in header, it doesn't show Load More button.
When clicking Member List (with this shield icon, in Party tab) it worked. I copied some code from `website/client/src/components/groups/group.vue` and modified it, so it doesn't conflict with current code.

3. rd commit:  **Fixed View Party button to properly open party** 
- [ ] Which files: `website/client/src/components/header/index.vue`
- [ ] Description: It was just a small fix to 2nd commit, as i didn't notice that after refreshing the page, View Party button doesn't work.

4. th commit: **Fixed SelectMembersModal to properly show Load More button** 
- [ ] Which files: ` website/client/src/components/selectMembersModal.vue`
- [ ] Description: It was the main fix for the issue with an id 13394 (clickable number is on top of this file). First of all i copied Load More button from previous commits, then i copied some code from previous commits as well. The main thing was to get `group` from dispatch, get some values out of it and save them to the store. I also added `const invite` and assigned it to dispatched `getGroupInvites`, but i wasn't sure what was this fragment of code doing and couldn't find it out, so i just left it here. (lines 269-273)

----
UUID: 86f37f0c-ebaf-4ee8-bf9f-00a5aa485501

2021-09-15 23:01 UTC, dabrowskif commented
Also the search field in Select Members modal is completely bugged (and it was before), but I just have no time to fix this.

2021-09-16 22:36 UTC, SabreCat requested changes
Looking pretty good! Just need to fix the broken test.

2021-09-16 22:36 UTC, SabreCat commented on website/common/script/constants.js
> +export const PARTY_LIMIT_MEMBERS = 29;
This is causing an integration test to fail--I understand from the PR description what this is for, but you'll need to update the expectation in the test suite!

2021-10-07 20:41 UTC, SabreCat commented on website/common/script/constants.js
> +export const PARTY_LIMIT_MEMBERS = 29;
Went ahead and updated the tests!

2021-10-07 20:41 UTC, merged

2021-10-07 20:41 UTC, SabreCat commented
Thanks for this, @dabrowskif! Added to your contributor credit toward Tier 3 Blacksmith!