Purge Facebook
HabitRPG/habitica pull request #13696
Opened 2021-12-13 17:02 UTC by phillipthelen

This is the second PR matching with #13683.

This actually removes most code references to Facebook and removes it as an option for social auth. It does not delete the database structure, since we probably want to keep that until we are sure everything works correctly and no issues would arise from deleting that data.

This should not be merged in/deployed yet. This is for when we are ready to do this step.

2021-12-20 10:50 UTC, phillipthelen commented
The relevant tests all pass. The error is coming from a test that is failing due to g1g1 right now.

2022-08-09 20:35 UTC, SabreCat requested changes
I think the intended changes here are good, but there's a bunch of unrelated stuff that ought to be in a separate PR. Steps to me look like

* Remove the files that have nothing to do with Facebook--looks like mostly client side code style adjustments
* Merge develop back and resolve conflicts
* If desired, submit a separate lint-fix PR

I'm guessing that will clean up everything necessary! Some of the changes here look like things we did in the prereq social auth improvement PRs that maybe didn't get split out? But the develop merge should straighten that out, though if there are discrepancies we'll need to dig into and address those!

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/appFooter.vue
> +                @click.prevent="openBugReportModal()"
This probably doesn't need to be in this PR, especially since we're rewriting the footer

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/bugReportModal.vue
> -      <div v-once class="report-bug-header-describe">
This file is likewise unrelated (probably dragged in via a linter autofix?)

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/bugReportSuccessModal.vue
> -            v-html="icons.checkCircleIcon"
extraneous file

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/groups/tavern.vue
> +                @click.prevent="openBugReportModal()"
extraneous file

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/header/menu.vue
> -                @click.prevent="openBugReportModal()"
'nother 😅

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/header/notifications/worldBoss.vue
> -  mixins: [
'n' another

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/inventory/items/index.vue
> +                  <questInfo
blap

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/shared/closeIcon.vue
> -    @click="$emit('click', $event)"
lint why

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/snackbars/notification.vue
> -    <div class="notification-holder"
...

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/snackbars/notifications.vue
> -  mixins: [
😭

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/static/contact.vue
> +              @click.prevent="openBugReportModal()"
🙄

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/static/privacy.vue
> -      located at <a href='https://habitica.com/static/home'>https://habitica.com/static/home</a> and/or our Apps
I'm scanning through this for anything Facebook related but not seeing it... looks like another aggressive lint

2022-08-09 20:35 UTC, SabreCat commented on website/client/src/components/static/terms.vue
> -    <p class="strong pagemeta">Last Updated: December 14, 2021</p>
same here I think?

2022-09-15 23:22 UTC, SabreCat approved these changes

2022-09-15 23:22 UTC, merged