Update: Quest Refactoring
HabitRPG/habitica pull request #13818
Opened 2022-02-03 17:19 UTC by CuriousMagpie

The existing `quests.js` file is extremely difficult to navigate and cumbersome to update. This PR moves all the quest objects into constants based on quest type.

### Changes
- created `QUEST_GENERIC`, `QUEST_MASTERCLASSER`, `QUEST_SERIES`, `QUEST_SEASONAL`, `QUEST_PETS`, `QUEST_POTIONS`, `QUEST_TIMETRAVEL`, and `QUEST_WORLD` to hold quest objects. Quests have been generally alphabetized within each constant, with the exception is `QUEST_MASTERCLASSER`, where quests are listed in the order of the storyline.
- Quest objects is now called from the constants into `quests.js`, where they are combined into a single object using the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax).

----
UUID: f4e5c6da-0617-48bf-b3bd-9f97636774a8

2022-04-07 20:56 UTC, SabreCat commented
OK, after a find-and-fix on an `import` statement and taking the opportunity to fix a production bug with seasonal quests being available out of season, this looks ok!

My one concern is that I don't agree with `content/constants/questXXXX.js`, organization-wise? we have `content/gear` and `content/appearance`, which are technically constants too but they each have their own space within the app. Why not make a directory `website/common/script/content/quests` and have `generic.js`, `masterclasser.js`, `pets.js` and so on, in there?

2022-04-07 20:58 UTC, SabreCat requested changes
Code is working, I have one suggestion about the file hierarchy that I added in PR conversation!

2022-04-11 21:22 UTC, CuriousMagpie commented
> My one concern is that I don't agree with `content/constants/questXXXX.js`, organization-wise? we have `content/gear` and `content/appearance`, which are technically constants too but they each have their own space within the app. Why not make a directory `website/common/script/content/quests` and have `generic.js`, `masterclasser.js`, `pets.js` and so on, in there?

This is a great suggestion and I went ahead and did that--I think I didn't initially because I wasn't sure if there was a reason why `website/common/script/content/quests` shouldn't exist.

2022-04-15 21:31 UTC, SabreCat approved these changes

2022-04-15 21:35 UTC, merged