Improve flows for social auth users
HabitRPG/habitica pull request #13862
Opened 2022-02-15 17:30 UTC by phillipthelen

2022-02-21 21:14 UTC, SabreCat requested changes
Just one question that might need a trivial fix. I'll send this to Delta for QA once that's answered!

2022-02-21 21:14 UTC, SabreCat commented on website/client/src/components/settings/site.vue
> +          <div v-if="!user.auth.local.has_password">
Is this supposed to be `hashed_password`? I'm not seeing a `has_password` field or method anywhere.

2022-02-24 17:07 UTC, SabreCat approved these changes

2022-03-25 20:56 UTC, SabreCat requested changes
couple of typos we can clean up whenever, one logic design question

2022-03-25 20:56 UTC, SabreCat commented on website/common/locales/en/front.json
> +  "passwordReset": "If we have your emailor username on file, instructions for setting a new password have been sent to your email.",
trivial typo here

2022-03-25 20:56 UTC, SabreCat commented on website/common/locales/en/settings.json
> +    "addPasswordAuth": "Add Password ",
odd trailing space?

2022-03-25 20:56 UTC, SabreCat commented on website/server/controllers/api-v3/auth.js
> +        { 'auth.local.username': email.replace('@', '') },
is there a risk of this picking up someone who coincidentally has a username that's similar to someone else's email address?

2022-03-25 20:57 UTC, SabreCat commented
Also looks like one of the integration tests is landing the wrong error message

2022-03-25 21:28 UTC, SabreCat commented on website/server/libs/auth/index.js
> +    } else {
I think this is what's causing the test failures--
`user` comes from an `$or` search, either we find the email address or we find the lowercase username;
but if we find it on the lowercase username, we end up here, reporting that the email address is already taken even if the email address passed the uniqueness check.

2022-03-29 16:32 UTC, phillipthelen commented on website/server/controllers/api-v3/auth.js
> +        { 'auth.local.username': email.replace('@', '') },
Good point. I. don't think this would really be an issue, but the more correct solution either way would be to only replace the @ if it's the first character

2022-03-30 21:52 UTC, SabreCat approved these changes

2022-03-31 21:43 UTC, merged