fix: Group Plans string duplication & style adjustment
HabitRPG/habitica pull request #14148
Opened 2022-07-27 21:53 UTC by CuriousMagpie

- removed duplicate instance of "Choose your payment method" since that text is now part of the `payment-buttons` component and updated `h4` color to match current design
- adjusted the styling of `updating-group` so that the purple box and the payment buttons box connect with each other and display as if they are a single item instead of two boxes mashed together

2022-08-26 20:30 UTC, SabreCat requested changes
One tiny suggestion, I can tidy it up if that works better!

2022-08-26 20:30 UTC, SabreCat commented on website/client/src/components/groups/groupPlan.vue
> +      color: #34313a;
We don't necessarily need to fix all instances in this PR, but if we're adding a new color style we should take the opportunity to import `colors.scss` and use the `$color-XXX` variables.

2022-08-26 21:28 UTC, CuriousMagpie commented
Yeah, for sure--I've been trying to do that! Must have missed this one in
my excitement to round some corners to `border-radius: 8px`.
--
Natalie Luhrs
my pronouns are she/they


On Fri, Aug 26, 2022 at 4:31 PM Sabe Jones ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> One tiny suggestion, I can tidy it up if that works better!
> ------------------------------
>
> In website/client/src/components/groups/groupPlan.vue
> <https://github.com/HabitRPG/habitica/pull/14148#discussion_r956427212>:
>
> > @@ -398,6 +403,10 @@
>    .payment-options {
>      margin-bottom: 4em;
>
> +    h4 {
> +      color: #34313a;
>
> We don't necessarily need to fix all instances in this PR, but if we're
> adding a new color style we should take the opportunity to import
> colors.scss and use the $color-XXX variables.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/14148#pullrequestreview-1087494079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASTMDCU5DSIUFTMGEFZ6JLDV3ESQ7ANCNFSM543D4QCQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-14 21:28 UTC, SabreCat commented on website/client/src/components/groups/groupPlan.vue
> +      color: #34313a;
On second thought, there's enough random hex codes in this file that we should probably do it all at one go later... never mind XD

2022-09-14 21:30 UTC, SabreCat approved these changes

2022-09-14 21:33 UTC, merged