Group category update issue
HabitRPG/habitica pull request #14186
Opened 2022-08-25 17:40 UTC by antonderegt

[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11162

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
When the categories of a group are updated, the list of all selected categories gets send to the API.
In the group update endpoint the current and the updated group are merged. This works fine for properties like the name. For example:

Current group:
```js
{
  name: "old",
  ...
}
```

Updated group:
```js
{
  name: "new",
  ...
}
```

When these two are merged, the result is:
```js
{
  name: "new",
  ...
}
```

But when merging arrays, the current and updated array are basically concatenated:
Current group:
```js
{
  categories: [
    { name: "a", slug: "a"},
    { name: "b", slug: "b"},
  ],
  ...
}
```

Remove categories a and b and add category c:
```js
{
  categories: [
    { name: "c", slug: "c"},
  ],
  ...
}
```

Result after merge:
```js
{
  categories: [
    { name: "a", slug: "a"},
    { name: "b", slug: "b"},
    { name: "c", slug: "c"},
  ],
  ...
}
```

Another thing that was happening, was that the categories duplicated even when you didn't change them. That was because when saving, every category object gets and _id property. So, the merge function doesn't see `{ name: "a", slug: "a"}` as the same as `{ _id: 123456, name: "a", slug: "b"}`.

#### Solution
To solve this problem I changed the lodash merge function to mergeWith. This function takes another function to customize the merge. In this case I check for arrays, if an array is found, the updated array is returned instead of a merge of the current and updated array. If no array is found, it returns undefined, which means to merge in the default manner.

I also changed `PUT-groups.test.js` to include an initial category in the beforeEach and I added a test to remove that initial category. 

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: d100d5d4-0257-46d4-ac05-51ca01f49189

2022-08-25 17:44 UTC, antonderegt commented
I'm a first time contributor so the workflow for tests hasn't run automatically. Please can an admin click the button to start it?

2022-08-26 21:08 UTC, SabreCat requested changes
This looks solid, @antonderegt, thank you!

One suggestion: would it be possible to make existing bad data self-repairing, by having any outstanding duplicate entries collapse down to a single copy on edit? I noticed that while after the fix it became possible to manually delete duplicates by editing the guild, unchecking a duplicated category, saving, and then repeating the process until all the extra entries were gone, it'd be handy if users didn't need to do that loop.

2022-08-27 10:32 UTC, antonderegt commented
> This looks solid, @antonderegt, thank you!
> 
> One suggestion: would it be possible to make existing bad data self-repairing, by having any outstanding duplicate entries collapse down to a single copy on edit? I noticed that while after the fix it became possible to manually delete duplicates by editing the guild, unchecking a duplicated category, saving, and then repeating the process until all the extra entries were gone, it'd be handy if users didn't need to do that loop.

Ah, great suggestion! I’m on it.

2022-08-28 09:42 UTC, antonderegt commented
Hi @SabreCat, I made the following changes regarding your suggestion:

To make sure previously duplicated categories get cleaned up on every edit of a group, I make sure the list of updated categories is unique, by slug, with the lodash.uniqBy function.

Also added a test for this: 'removes duplicate group categories'.

2022-09-12 19:26 UTC, antonderegt commented
Hi, 

I’m just adding this comment to make you aware of this PR again. If you’re too busy, it’s fine. I just wanted to make sure it wasn’t forgotten.

Thanks

2022-10-12 20:51 UTC, SabreCat approved these changes

2022-10-12 20:51 UTC, SabreCat commented
Apologies for the delays (small team headaches, tch), but this looks good! Noted in your contributions toward your second tier!

2022-10-12 20:51 UTC, merged