Add transaction to challenge join
HabitRPG/habitica pull request #15253
Opened 2024-06-19 15:52 UTC by SYN-tactic

[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_#_and_issue_number_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

2024-07-02 16:07 UTC, SYN-tactic commented
I'm a first time contributor so the workflow for tests hasn't run automatically after I merged in the upstream develop branch. Please can an admin click the button to start it?

2024-07-14 18:03 UTC, SYN-tactic commented
Hi, I updated this branch with the latest from develop but it looks like it needs an admin to restart the workflow. Thanks!

2024-07-29 16:14 UTC, SYN-tactic commented
> Hi, I updated this branch with the latest from develop but it looks like it needs an admin to restart the workflow. Thanks!

Hello, updated this again!

2024-07-29 22:38 UTC, SabreCat requested changes
Hi @SYN-tactic, and thanks for this! Gettin back into the swing of moving PRs through QA, here...

This is definitely a change we want to make, but I suspect the reimport of `mongoose` and starting of a fresh Mongoose session is overkill. Mongoose functions should already be available via the model, imported as `Challenge`. See for instance https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/groups.js#L144-L147 where we fetch the extant session using the properties from the model `db` object.

If I'm mistaken or misunderstanding something here, though, volley back!

2024-07-30 20:26 UTC, SYN-tactic commented
> Hi @SYN-tactic, and thanks for this! Gettin back into the swing of moving PRs through QA, here...
> 
> This is definitely a change we want to make, but I suspect the reimport of `mongoose` and starting of a fresh Mongoose session is overkill. Mongoose functions should already be available via the model, imported as `Challenge`. See for instance https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/groups.js#L144-L147 where we fetch the extant session using the properties from the model `db` object.
> 
> If I'm mistaken or misunderstanding something here, though, volley back!

Hey @SabreCat , thank you for you feedback!

That makes sense - what do you think of starting a session this way, instead?
```javascript
 const session = await Challenge.startSession();
 session.startTransaction();
```
My approach needs a way to reference the session, so based on your input it sounds like I could just start a session this way. However, it's unclear to me whether a reference to an existing/active session already exists on the model that I could somehow retrieve? Let me know if this approach makes sense - if not happy to dig in to this a little more. Cheers!

2026-07-23 18:57 UTC, SabreCat approved these changes

2026-07-23 18:57 UTC, merged

2026-07-23 18:59 UTC, SabreCat commented
after a long long wait, this is on its way through our staging environment! Thanks for this, @SYN-tactic; your Blacksmith credit has been applied on site!