Starting tasks
HabitRPG/habitica pull request #7554
Opened 2016-05-30 23:13 UTC by MathWhiz

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #7103 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Adds social-themed tasks for new users:
![screenshot 2016-05-30 at 6 10 55 pm](https://cloud.githubusercontent.com/assets/12386291/15659566/3ae246ce-2692-11e6-8a75-283fcbcc8d2b.png)

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID:

2016-05-31 16:02 UTC, MathWhiz commented
@crookedneighbor The tests seem to be running with npm v2:
![screenshot 2016-05-31 at 11 01 39 am](https://cloud.githubusercontent.com/assets/12386291/15681519/1bc4a074-271f-11e6-9891-7a0208cc4b96.png)
Could that be why my build is failing?

2016-05-31 17:00 UTC, crookedneighbor commented
It's not using npm v2. v2 is what comes standard with node v4, but if you look at line 161, you'll see that `npm install -g npm@3` gets run which install npm 3.

2016-05-31 17:16 UTC, MathWhiz commented
@crookedneighbor Ok. I'm just not sure where the errors come from, and if they are because of my changes.

2016-05-31 17:21 UTC, crookedneighbor commented on common/locales/en/defaultTasks.json
> +
Why this extra space?

2016-05-31 17:22 UTC, paglias commented
There's a problem in models/user.js#584. It should return a new object for the checklist instead of modifying the existing one

2016-05-31 20:13 UTC, lemoness commented
Is there a way to have the task "Read Overview for New Users" simply
display only for website users, rather than have it say "website only" in
the task itself? If not, that's fine.

On Tuesday, May 31, 2016, Matteo Pagliazzi <notifications@github.com> wrote:

> There's a problem in models/user.js#584. It should return a new object for
> the checklist instead of modifying the existing one
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitrpg/pull/7554#issuecomment-222758271>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADVQwY5pg8eAi1DGTp9jGc2sJhy9r8kfks5qHG49gaJpZM4IqEm3>
> .
>

2016-05-31 21:19 UTC, MathWhiz commented
I don't believe we can, unfortunately.
On Tue, May 31, 2016 at 3:13 PM lemoness <notifications@github.com> wrote:

> Is there a way to have the task "Read Overview for New Users" simply
> display only for website users, rather than have it say "website only" in
> the task itself? If not, that's fine.
>
> On Tuesday, May 31, 2016, Matteo Pagliazzi <notifications@github.com>
> wrote:
>
> > There's a problem in models/user.js#584. It should return a new object
> for
> > the checklist instead of modifying the existing one
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/HabitRPG/habitrpg/pull/7554#issuecomment-222758271>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ADVQwY5pg8eAi1DGTp9jGc2sJhy9r8kfks5qHG49gaJpZM4IqEm3
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitrpg/pull/7554#issuecomment-222806003>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALz_82kRDWcXEV88M7KrgVufuVgr1zbXks5qHJZ8gaJpZM4IqEm3>
> .
>

2016-05-31 21:55 UTC, awitherow commented on common/locales/en/defaultTasks.json
> +
remove space?

2016-05-31 22:31 UTC, MathWhiz commented on common/locales/en/defaultTasks.json
> +
No idea, I probably wanted to space out the habits, todos, and rewards

2016-05-31 22:42 UTC, MathWhiz commented
@paglias is there something I should change?

2016-05-31 22:46 UTC, MathWhiz commented
@paglias would
```javascript
return _.map(taskDefaults.checklist, (checklistItem) => {
  checklistItem.text = checklistItem.text(user.preferences.language);
  return checklistItem;
```
work?

2016-06-08 19:46 UTC, MathWhiz commented
@crookedneighbor Would you be able to help me with the tests?

2016-06-09 00:54 UTC, MathWhiz commented
@crookedneighbor What went wrong?

2016-08-10 15:20 UTC, khipkin commented on test/api/v3/integration/tasks/GET-tasks_user.test.js
> +    expect(tasks.length).to.equal(createdTasks.length + 4); // + 1 because 1 is a default task
Suggestion: update comment too

2016-08-10 15:20 UTC, khipkin commented on test/api/v3/integration/user/GET-user_anonymized.test.js
> +    expect(tasks2.length).to.eql(8); // +1 because generateUser() assigns one todo
Suggestion: here as well?

2016-08-10 15:25 UTC, khipkin commented on test/api/v3/integration/dataexport/GET-export_userdata.json.test.js
>      expect(res.tasks.todos[1]._id).to.equal(tasks[3]._id);
[This test failure](https://travis-ci.org/HabitRPG/habitrpg/builds/151077184#L9979) is due to this assertion.

2016-08-10 15:25 UTC, khipkin commented on test/api/v3/integration/dataexport/GET-export_userdata.xml.test.js
>      expect(res.tasks.todos[1]._id).to.equal(tasks[3]._id);
[This test failure](https://travis-ci.org/HabitRPG/habitrpg/builds/151077184#L10000) is due to this assertion.

2016-08-10 15:28 UTC, khipkin commented
@MathWhiz The tests I commented on make assumptions about tasks' specific indices in `res.tasks.todos` that are no longer true.  I think the problems are just that the indices are not correct.

2016-08-10 15:34 UTC, crookedneighbor commented
I think the generateUser function should automatically remove any tasks that are added as a result of registering. Some tests may need to be updated, but it will eliminate these weird cases in the future.

2016-08-12 02:09 UTC, MathWhiz commented
@crookedneighbor Would an option to keep the registered tasks in the `generateUser()` function be a good idea?

2016-08-12 03:33 UTC, crookedneighbor commented
IMO, I think the user should just be blank. No tasks at all.

2016-08-12 03:45 UTC, MathWhiz commented
The problem with that is that it means I can't (easily) make a test to
check if the default tasks are added.
On Thu, Aug 11, 2016 at 10:33 PM Blade Barringer <notifications@github.com>
wrote:

> IMO, I think the user should just be blank. No tasks at all.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitrpg/pull/7554#issuecomment-239353607>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8_KYbUNzoMip6Th8dcAeDMx5ayX1ks5qe-mcgaJpZM4IqEm3>
> .
>

2016-08-12 11:34 UTC, crookedneighbor commented
No, you would use the register route instead to test that.

2016-08-12 13:03 UTC, MathWhiz commented
Ok
On Fri, Aug 12, 2016 at 6:34 AM Blade Barringer <notifications@github.com>
wrote:

> No, you would use the register route instead to test that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitrpg/pull/7554#issuecomment-239424309>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8xNHvNKzI5x_uulQBvVtqPLqxAViks5qfFo_gaJpZM4IqEm3>
> .
>

2016-09-11 13:34 UTC, crookedneighbor commented on test/helpers/api-integration/v3/object-generators.js
> +  await apiUser.post('/user/reset');
Clever 😄

2016-09-12 13:09 UTC, crookedneighbor commented on common/locales/en/defaultTasks.json
> +  "defaultTodo3Notes": "☰ > Social > Guilds/n/nThis is the best place to ask questions!",
Your `/n` should be `\n`

![screen shot 2016-09-12 at 8 08 20 am](https://cloud.githubusercontent.com/assets/2916945/18436887/2978c518-78c0-11e6-8c8a-a9f033a709ff.png)

2016-09-12 13:10 UTC, crookedneighbor commented on common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
Personally, I don't like this. Looks messy.

![screen shot 2016-09-12 at 8 09 44 am](https://cloud.githubusercontent.com/assets/2916945/18436941/64805720-78c0-11e6-8087-4acc49f72c4c.png)

2016-09-12 13:10 UTC, crookedneighbor commented on common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
Any other maintainers have thoughts on that?

2016-09-12 16:08 UTC, MathWhiz commented on common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
What do you think I should do?

2016-09-12 17:57 UTC, MathWhiz commented on common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
@crookedneighbor How about putting the info in the checklist?

2016-09-13 13:18 UTC, crookedneighbor commented on common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
That's not my call to make. I just don't think this current version looks right.

2016-09-14 03:04 UTC, MathWhiz commented on common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
I can try splitting it into two different tasks...

2016-10-12 03:19 UTC, crookedneighbor requested changes

2016-10-12 03:19 UTC, crookedneighbor commented on website/common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
@lemoness or @alys thoughts on this text?

2016-10-13 09:49 UTC, Alys commented on website/common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
@MathWhiz Could you please show us a screenshot of what `defaultTodo2Notes` looks like when you hover over the task?

2016-10-19 16:30 UTC, librarianmage commented on website/common/locales/en/defaultTasks.json
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
@Alys it currently looks like:

![img](https://cloud.githubusercontent.com/assets/2916945/18436941/64805720-78c0-11e6-8087-4acc49f72c4c.png)

2016-10-20 02:54 UTC, lemoness commented
I think it's a little unclear -- people may not necessarily understand what
the instructions are telling them to do.

On Wed, Oct 19, 2016 at 9:30 AM, AccioBooks <notifications@github.com>
wrote:

> *@MathWhiz* commented on this pull request.
> ------------------------------
>
> In website/common/locales/en/defaultTasks.json
> <https://github.com/HabitRPG/habitica/pull/7554>:
>
> > @@ -11,6 +11,20 @@
>    "defaultTodoNotes": "You can either complete this To-Do, edit it, or remove it.",
>
>    "defaultTodo1Text": "Join Habitica (Check me off!)",
> +  "defaultTodo1Notes": "You can either complete this To-Do, edit it, or remove it.",
> +
> +  "defaultTodo2Text": "Learn About Habitica",
> +  "defaultTodo2Notes": "Overview of New Users:\n\n💻 only: ☰(Menu - Top Bar) > Help\n\nFAQ:\n\n📱: ☰ > Help & FAQ\n\n💻 : ☰ > Help > FAQ",
>
> @Alys <https://github.com/Alys> it currently looks like:
>
> [image: img]
> <https://cloud.githubusercontent.com/assets/2916945/18436941/64805720-78c0-11e6-8087-4acc49f72c4c.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/7554>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADVQwaLJGJnI3Rp4tl5bBsAk4dA2Uf45ks5q1kWTgaJpZM4IqEm3>
> .
>

2016-10-20 03:22 UTC, MathWhiz commented
@lemoness How about splitting it into two tasks? Something like:

* See Overview of New Users (Computer Only)
* See FAQ

2016-10-20 06:42 UTC, lemoness commented
I think that could work! Or maybe have it say, "Read FAQ" etc, since that's
a little more specific about what they should do. (I assume that "Computer
Only" is not in the task name, but rather a sign of where it would appear.)

On Wed, Oct 19, 2016 at 8:22 PM, AccioBooks <notifications@github.com>
wrote:

> @lemoness <https://github.com/lemoness> How about splitting it into two
> tasks? Something like:
>
>    - See Overview of New Users (Computer Only)
>    - See FAQ
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/7554#issuecomment-254999348>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADVQwZHDpsHEebYenEMAztpUFka0zEwdks5q1t5ggaJpZM4IqEm3>
> .
>

2016-10-20 13:41 UTC, MathWhiz commented
@lemoness Unfortunately, having the Overview of New Users on only be shown on the computer is not possible (to my knowledge)

2016-10-20 13:58 UTC, crookedneighbor commented
It is possible to specify what the default tasks are based on what platform was used for sign up. Pretty sure we already do that.

2016-10-20 14:04 UTC, MathWhiz commented
@crookedneighbor What about people that initially sign up on one device, and use both? If someone uses the website at all, it would be useful for them to read it.

2016-10-27 15:38 UTC, lemoness commented
For now, let's just focus on what device they used to sign up. That way, we
can get the changes out sooner.

On Thu, Oct 20, 2016 at 7:04 AM, AccioBooks <notifications@github.com>
wrote:

> @crookedneighbor <https://github.com/crookedneighbor> What about people
> that initially sign up on one device, and use both? If someone uses the
> website at all, it would be useful for them to read it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/7554#issuecomment-255115128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADVQwawluvQKk-JPsKnItcipdu_vEEJ0ks5q13TrgaJpZM4IqEm3>
> .
>

2016-10-29 18:29 UTC, MathWhiz commented
@crookedneighbor I don't see anything in [auth.js](https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/auth.js) that would suggest that there is a difference in how mobile and non-moblie users register, but I'm not sure what I'd look for.

2016-10-29 18:35 UTC, crookedneighbor commented
https://github.com/HabitRPG/habitica/blob/develop/website/server/models/user/hooks.js

2016-10-29 18:40 UTC, MathWhiz commented
@crookedneighbor How do you suggest I change the logic? It is currently checking for the web/android or ios, and I want specific tasks for web and android/ios

2016-11-09 19:38 UTC, MathWhiz commented
@crookedneighbor I don't think I will be able to finish this. The logic behind setting up tasks is a tad too complex for me to change easily (AFAIK), and I've been stuck for the past week. I'm sorry. 😞

2016-11-10 10:34 UTC, Alys commented
@MathWhiz Don't be sorry! Thank you for trying, and thanks very much for letting us know! :heart:

2016-11-10 15:18 UTC, closed without merging