Fix Magic Mount Spacing
HabitRPG/habitica pull request #8015
Opened 2016-09-15 02:49 UTC by Ozzystrasza

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitrpg/issues/7888

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

I did it so the magic mount section will only appear if the user has 1 or more magic pets. Also it will show only the pawprint of the mounts that the user has an equivalent magic pet.

![2016-09-14](https://cloud.githubusercontent.com/assets/20071290/18536388/5349634c-7ad3-11e6-8a4c-85eea95fa4af.png)

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID: 8389891a-ba52-4580-b08b-2cb706c7e0b4

2016-09-15 13:49 UTC, crookedneighbor commented on website/client-old/js/controllers/inventoryCtrl.js
> +      potion = Content.premiumHatchingPotions[potion].key;
I added some data to the Content api that should make this much simpler:

```js
$scope.shouldShowPremiumMountRow = function (potion) {
  var pets = Object.keys(user.items.pets);
  return pets.find(function (petKey) {
    var pet = Content.petInfo[petKey];
    return pet.potion === potion;
  });
};
```

2016-09-15 13:53 UTC, crookedneighbor commented on website/client-old/js/controllers/inventoryCtrl.js
> +      potion = Content.premiumHatchingPotions[potion].key;
The same simplification can be done to the pet equivalent.

2016-09-15 13:57 UTC, crookedneighbor commented on website/client-old/js/controllers/inventoryCtrl.js
> +    $scope.shouldShowPremiumMountSection = function () {
The logic here should basically be if the user has ever had a premium pet, right? 

You can use a similar method to what I showed you above, asserting on the `pet.type === 'premium'` property. Let me know if you need help.

2016-09-15 13:58 UTC, crookedneighbor requested changes
It's all function as is, but we can clean up the logic a bit.

2016-09-15 21:16 UTC, Ozzystrasza commented on website/client-old/js/controllers/inventoryCtrl.js
> +    $scope.shouldShowPremiumMountSection = function () {
Made the changes, including on the `shouldShowPremiumPetRow` function. Hope I did the way you wanted!
On a side note, what did you mean by "It's all function as is"?

2016-09-15 21:21 UTC, crookedneighbor commented on website/client-old/js/controllers/inventoryCtrl.js
> +      return pets.find(function (petKey) {
Looks like we do this exact same check twice. Pull it out into a function?

2016-09-15 21:21 UTC, crookedneighbor requested changes

2016-09-15 21:25 UTC, crookedneighbor commented
It was a typo. All `functional` as is.

2016-09-15 21:38 UTC, Ozzystrasza commented on website/client-old/js/controllers/inventoryCtrl.js
> +      return pets.find(function (petKey) {
Does it need to be `$scope.functionName`, or should it be `var functionName` ? Sorry for the noob question, but I don't quite get the difference yet.

2016-09-15 21:45 UTC, Ozzystrasza commented on website/client-old/js/controllers/inventoryCtrl.js
> +      return pets.find(function (petKey) {
also, all the `shouldShowPremiumMountRow` does now is call this new function, should I remove it and use the new function directly in the mounts.jade? 
And if that's the case it needs to be `$scope.newFunction` right?

2016-09-15 22:10 UTC, Ozzystrasza commented on website/client-old/js/controllers/inventoryCtrl.js
> +      return pets.find(function (petKey) {
Did some changes, let me know if they are ok.

2016-09-15 22:29 UTC, khipkin commented on website/client-old/js/controllers/inventoryCtrl.js
> +      return pets.find(function (petKey) {
The difference is that the functions in the `$scope` can be used by anything else with access to that `$scope` (i.e., any views that use this controller), whereas the `var functionName` functions are helper functions that are not visible outside this file.

2016-09-15 22:40 UTC, crookedneighbor commented on website/client-old/js/controllers/inventoryCtrl.js
> +      return pets.find(function (petKey) {
It's worth noting that `$scope` is an Angular thing. Not a general JavaScript thing.

2016-09-15 22:41 UTC, crookedneighbor commented on website/client-old/js/controllers/inventoryCtrl.js
> +      premiumPotion = Content.premiumHatchingPotions[potion];
var premiumPotion

2016-09-15 22:42 UTC, crookedneighbor requested changes
Other than my one comment, it looks good to me.

2016-09-15 22:48 UTC, Ozzystrasza commented on website/client-old/js/controllers/inventoryCtrl.js
> +      premiumPotion = Content.premiumHatchingPotions[potion];
Damn, how did I miss that!
Just pushed the fix. Thanks for the help and teachings @crookedneighbor and @khipkin .

2016-09-16 02:48 UTC, crookedneighbor commented on website/client-old/js/controllers/inventoryCtrl.js
> +      premiumPotion = Content.premiumHatchingPotions[potion];
Probably because I just reassigned the existing variable before :)

2016-09-16 03:01 UTC, crookedneighbor approved these changes

2016-09-16 03:01 UTC, merged

2016-09-16 03:05 UTC, crookedneighbor commented
I made one minor edit that I noticed while making one last review: https://github.com/HabitRPG/habitrpg/commit/9c0998c29ab44e5370871a16732c0eb1ef5dc87f

Extracts the find pet logic into it's own function that takes a function for how to compare the pet, rather than repeating the logic.

Notated this PR to your next tier.

2016-09-16 03:11 UTC, Ozzystrasza commented
No code repetitions on your watch! 😄 Thanks!

2016-09-16 23:13 UTC, mandyzhou commented
Looks like this was released in v3.41.3, but I'm still seeing the large gap on my Mounts page. The Pets page looks fine, though.

2016-09-16 23:17 UTC, SabreCat commented
@mandyzhou: The release hasn't gone live yet thanks to a hiccup I've attempted to address [here](https://github.com/HabitRPG/habitrpg/pull/8029/files).