added balance to analytics
HabitRPG/habitica pull request #8086
Opened 2016-09-30 15:16 UTC by dumindux

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8057

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID:

2016-09-30 15:22 UTC, paglias requested changes

2016-09-30 15:22 UTC, paglias commented on website/server/libs/analyticsService.js
> +  if (user.balance) {
User.balance should Always exist. Also this check will Always returns false for a balsnce of 0 but we want to store it even if 0

2016-09-30 15:26 UTC, crookedneighbor commented on website/server/libs/analyticsService.js
> +  if (user.balance) {
Agreed.

2016-09-30 16:04 UTC, dumindux commented on website/server/libs/analyticsService.js
> +  if (user.balance) {
Thanks for the suggestions. I will add the changes

2016-09-30 16:28 UTC, crookedneighbor commented
Don't forget to provide your user id.

You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

2016-09-30 16:47 UTC, paglias approved these changes

2016-09-30 16:47 UTC, paglias commented
LGTM 👍

2016-09-30 16:52 UTC, merged

2016-09-30 16:52 UTC, crookedneighbor commented
Let me know your user id so I can credit you for your work!

2016-10-01 03:39 UTC, dumindux commented
Hi, my user id is 5fc49b3a-752c-4d35-9f73-287e19fdc96b

2016-10-01 14:34 UTC, crookedneighbor commented
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

2016-10-01 14:43 UTC, dumindux commented
Wow great!!. Thank you :).