Improve API Docs for Invite to Group, Iss#8087
HabitRPG/habitica pull request #8091
Opened 2016-10-02 23:26 UTC by JTorr

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
https://github.com/HabitRPG/habitica/issues/8087

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Update documentation for Invite to Group to more accurately reflect current structure of parameters and error types.

![screen shot 2016-10-02 at 7 25 18 pm](https://cloud.githubusercontent.com/assets/7951702/19024664/1d4a1ee2-88d6-11e6-8192-7abf3dc9b614.png)
![screen shot 2016-10-02 at 7 25 28 pm](https://cloud.githubusercontent.com/assets/7951702/19024665/1f41621e-88d6-11e6-82e2-699274584fda.png)

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID: 1bf2957d-600e-4952-9e7b-d796cf99763d

2016-10-03 02:34 UTC, crookedneighbor requested changes

2016-10-03 02:34 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + * @apiParam {Array} [emails] Body parameter - An array of objects, each
I think the preferred way of writing this is:

```js
/*
 * // other stuff
 * @apiParam {Object[]} [emails] Body parameter - An array of objects, each representing one email address to invite
 * @apiParam {String} emails.email The email address of the user being invited
 * @apiParam {String} [emails.name] The name of the user being invited
*/
```

2016-10-03 02:34 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + *      {"email": "user-1@example.com"},
Good catch on this.

2016-10-03 02:34 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + *   "success": true,
I think we should provide some boiler plate at the top describing the success and notifications properties. No need to provide them in every response example.

2016-10-03 02:34 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + * @apiErrorExample
Let's not include `apiErrorExample`s unless there's some really tricky case.

2016-10-03 12:53 UTC, JTorr commented on website/server/controllers/api-v3/groups.js
> + * @apiParam {Array} [emails] Body parameter - An array of objects, each
Ah, thank you. Will fix.

2016-10-03 22:30 UTC, JTorr commented
@crookedneighbor Please review changes. Thanks!

2016-10-03 22:41 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + *   "success": true,
Looks like this still needs to be addressed.

2016-10-03 23:01 UTC, JTorr commented on website/server/controllers/api-v3/groups.js
> + *   "success": true,
I see that I missed the Notification property. Just to clarify, do you mean the success and notification properties should be at the top of the file (representing all of the Groups API calls), or together with the other properties (ex. line 676)

2016-10-04 02:48 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + *   "success": true,
I'm saying that every request, regardless of group, has these properties. We don't need to put them in every success example. We should adjust the template to include some introductory information about requests. Not something that needs to be done in this PR, but you should remove the success and notifications keys from this example.

2016-10-04 02:52 UTC, crookedneighbor commented
Just pushed a commit that illustrates how errors should be structured. https://github.com/HabitRPG/habitica/commit/2dc09586784366fcb139c377d3993c52ea5ac9da

Any error that would be repeated should be defined at the top of the appropriate file. For instance, the `GroupNotFound` error is defined here: https://github.com/HabitRPG/habitica/commit/2dc09586784366fcb139c377d3993c52ea5ac9da#diff-b950a7c557b35ea58bc2685532c46170R25

```
/**
 * @apiDefine GroupNotFound
 * @apiError (404) {NotFound} GroupNotFound The specified group could not be found.
 */
```

And it's used like this:

```
* @apiUse GroupNotFound
```

If it's an error that only occurs in a single route, it should be defined in that route:

```
 * @apiError (statusCode) {ErrorType} NameForError A description of the error
```

2016-10-04 23:08 UTC, JTorr commented
@crookedneighbor Thanks for the example. Very helpful. LMK if these changes are what you were looking for.

2016-10-05 03:54 UTC, crookedneighbor commented
What I'm saying regarding the `success` and `notifications` params returned in a successful response is that we _should not_ include them on every request. Instead, we should add information in the header of the API doc (see http://apidocjs.com/#headerfooter) about them. We should also include information about authenticating.

Those seem like separate concerns from this PR. So for now, just remove the information about `success` and `notifications`.

For the errors, I don't think we should generalize them. IE, let's be specific to the resource:

```js
// only applicable to the invite route, so we just add it there
* @apiError (400) {BadRequest} NoEmailProvided An email address was not provided in the `emails` body param
// for group update and creation, so we define it at the top and use `@apiUse GroupBodyInvalid` in the routes
* @apDefine GroupBodyInvalid
* @apiError (400) {BadRequest} GroupBodyInvalid A parameter in the group body was invalid
```

Also, just opened a PR to correct our use of `NotAuthorized` which should only be used for authentication. Here's a link to the changes to the `invite` route: https://github.com/HabitRPG/habitica/pull/8103/files#diff-b950a7c557b35ea58bc2685532c46170R550

2016-10-05 22:30 UTC, JTorr commented
@crookedneighbor How's it look now?

2016-10-06 01:57 UTC, crookedneighbor requested changes
We decided that those changes I made in the PR I linked would be a breaking change. So the errors need to stay as `NotAuthorized`.

Many of the `BadRequest` errors you have listed should actually be listed as `NotAuthorized`.

2016-10-06 01:57 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + *}
Space here between `*` and `}`

2016-10-06 01:57 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + * @apiError (400) {BadRequest} MustBeArray The `uuids` or emails body param is
emails should be surrounded in back ticks like uuids is.

2016-10-06 01:57 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> + * @apiError (400) {BadRequest} UserNotFound One or more of the `uuids` does not
It's actually a `404 NotFound` error. You can just use the `UserNotFound` error defined in the user controller.

```
@apiUse UseNotFound
```

2016-10-06 18:29 UTC, JTorr commented
@crookedneighbor Issues addressed.

2016-10-06 22:40 UTC, crookedneighbor approved these changes

2016-10-07 01:54 UTC, merged

2016-10-07 01:55 UTC, crookedneighbor commented
Thanks for your patience. Notated toward your next tier.