add additional IAP price tiers
HabitRPG/habitica pull request #8114
Opened 2016-10-09 13:32 UTC by vIiRuS

Adds new gem purchase price tiers for the apps and removes an unused one for the iOS app.

2016-10-09 15:50 UTC, khipkin commented on website/server/controllers/top-level/payments/iap.js
> +    switch (purchaseData.productId) {
Suggestion: Assign a value to `amount` in the switch, but make the API call afterwards to reduce redundancy.

2016-10-09 17:22 UTC, paglias commented on website/server/controllers/top-level/payments/iap.js
> +    switch (purchaseData.productId) {
agreed

2016-10-09 17:59 UTC, crookedneighbor commented on website/server/controllers/top-level/payments/iap.js
> +    switch (purchaseData.productId) {
Agreed.

2016-10-10 15:06 UTC, vIiRuS commented
changed the switch statement

2016-10-11 18:32 UTC, paglias requested changes

2016-10-11 18:32 UTC, paglias commented on website/server/controllers/top-level/payments/iap.js
> +    await payments.buyGems({user, paymentMethod: 'IAP GooglePlay', amount, headers: req.headers}); // eslint-disable-line babel/no-await-in-loop
the eslint comment should not be necessary, also can you split the object on multiple lines as it was before?

2016-10-11 18:32 UTC, paglias commented on website/server/controllers/top-level/payments/iap.js
> +    let amount = 0;
`let amount;` without = 0

2016-10-11 18:32 UTC, paglias commented on website/server/controllers/top-level/payments/iap.js
> +    if (amount === 0) throw new Error('INVALID_ITEM_PURCHASED');
`if (!amount)`

2016-10-11 18:32 UTC, paglias commented on website/server/controllers/top-level/payments/iap.js
> +        if (amount === 0) {
if (!amount)

2016-10-11 18:32 UTC, paglias commented on website/server/controllers/top-level/payments/iap.js
> +        await payments.buyGems({user, paymentMethod: 'IAP AppleStore', amount, headers: req.headers}); // eslint-disable-line babel/no-await-in-loop
split in multiple lines

2016-10-11 18:32 UTC, paglias commented on website/server/controllers/top-level/payments/iap.js
> +        let amount = 0;
let amount;

2016-10-11 18:50 UTC, paglias approved these changes

2016-10-11 19:30 UTC, merged