Only unequip Gen 1 pets/mounts when releasing pets/mounts, fixes #5366
HabitRPG/habitica pull request #8119
Opened 2016-10-11 02:54 UTC by abatula

Fixes #5366

### Changes
When releasing pets, mounts, or both, it will no longer unequip your pet or mount if it is a quest or special pet/mount.

This does not affect the `releasePets`, `releaseMounts`, or `releaseBoth` tests. Should another set of tests be written to ensure a quest pet (e.g. base gryphon) is not unequipped?
----
UUID: f5a68145-b375-4b99-8fb4-f9ff7a2c52b5

2016-10-12 02:51 UTC, crookedneighbor requested changes

2016-10-12 02:51 UTC, crookedneighbor commented on website/common/script/ops/releaseBoth.js
> +  if (Object.keys(content.pets).indexOf(user.items.currentMount) > -1) {
Probably better to do something like:

```js
let mount = content.mountInfo[user.items.currentMount];

if (mount && mount.type === 'drop') {
  user.items.currentMount = '';
}

let pet = content.petInfo[user.items.currentPet];

if (pet && pet.type === 'drop') {
  user.items.currentPet = '';
}
```

2016-10-12 17:40 UTC, abatula commented
Rewrote pet/mount checking to check if its type is "drop" instead of checking for its name as a key in `content.pets`.

2016-10-17 02:01 UTC, crookedneighbor commented
The tests for these functions should be adjusted to include these conditions.

2016-10-18 01:10 UTC, abatula commented
Added tests to make sure quest pets and mounts aren't removed.

2016-10-20 02:45 UTC, crookedneighbor requested changes

2016-10-20 02:45 UTC, crookedneighbor commented on test/common/ops/releaseBoth.js
> +  it('removes currentMount', () => {
Probably should specify that this condition is met when the mount is a drop mount. You could also include assertions about currentPet in this test.

2016-10-20 02:45 UTC, crookedneighbor commented on test/common/ops/releaseBoth.js
> +  it('leaves quest pets and mounts equipped', () => {
technically it's `non-drop pets` since special pets and premium pets also stay equipped.

2016-10-20 02:45 UTC, crookedneighbor commented on website/common/script/ops/releaseBoth.js
> +  // Only remove current mount if it is Gen 1 (dropped)
I don't think these comments are necessary.

2016-10-21 00:42 UTC, abatula commented
Updated tests to check whether a pet/mount is a drop type. Also renamed tests and removed comments.

2016-10-21 03:00 UTC, merged