Api doc dataexport
HabitRPG/habitica pull request #8120
Opened 2016-10-11 17:16 UTC by MathWhiz

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
#8087 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Improves documentation of Data Export functions

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID:

2016-10-12 02:44 UTC, crookedneighbor requested changes

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiDefine authError
Let's not use this in the documentation for each route. We should instead have some info in the header of the API doc about authorization requirements. (not for this PR)

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiDefine pathParam Path Parameters
This is defined here, so you can remove it: https://github.com/HabitRPG/habitica/commit/afb5b473a37325a82151bf48b0c7d54b4979e6eb

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * ...
Provide some sample data here.

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> - * @apiSuccess {String} A json file
This returns a json file, not an object.

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> - * @apiSuccess {String} A json file
It should probably stat that it's a json file of the user object and link to the get user route.

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiSuccess {String} data A xml file. See /export/userdata.json for structure info.
`a xml` -> `an xml`

It should probably stat that it's an xml file of the user object and link to the get user route.

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiParam (pathParam) {string} uuid The User ID of the user
`(Path) {String}`

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiDefine pathParam Path Parameters
Also, I elected to name the group `Path` instead of `pathParam`

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiSuccess {String} image A png file
It's a PNG file, not a `{String}`. Also, specify that it is the User's avatar

2016-10-12 02:44 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiParam (pathParam) {string} uuid The User ID of the user
`{String}`

2016-10-12 03:38 UTC, MathWhiz commented on website/server/controllers/top-level/dataexport.js
> - * @apiSuccess {String} A json file
@crookedneighbor That might be a good idea, but it also adds tasks organized by type, which is not part of the get user route

2016-10-12 03:50 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> - * @apiSuccess {String} A json file
That's true. For this route (and the XML one) I'm comfortable with just describing it and not including extensive information about it.

2016-10-12 03:54 UTC, MathWhiz commented
@crookedneighbor Made the changes!

2016-10-12 04:04 UTC, librarianmage commented on website/server/controllers/top-level/dataexport.js
> - * @apiSuccess {String} A json file
@crookedneighbor Got it. I have included the link in both (although get user doesn't currently have info)

2016-10-12 13:08 UTC, closed without merging

2016-10-12 13:08 UTC, crookedneighbor commented on website/server/controllers/top-level/dataexport.js
> + * @apiSuccess {XML} returns An xml file of the user object. See <code><a href='#api-User-UserGet'>GET /user</a></code>.
For future reference, markdown is preferred here.

2016-10-12 13:09 UTC, crookedneighbor commented
I made a few adjustments and merged this in. :+1:

2016-10-12 13:31 UTC, MathWhiz commented
@crookedneighbor Awesome! Did you notate it?

2016-10-13 01:15 UTC, crookedneighbor commented
Thanks for the reminder. Just did.

2016-10-13 01:16 UTC, MathWhiz commented
Thank you 😊!
On Wed, Oct 12, 2016 at 8:15 PM Blade Barringer <notifications@github.com>
wrote:

> Thanks for the reminder. Just did.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8120#issuecomment-253383816>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_80K72mdn_554ht7oQNHuFCt9QRC_ks5qzYYlgaJpZM4KT4UG>
> .
>