Send a message to the party chat when a quest is aborted, fixes #4879
HabitRPG/habitica pull request #8150
Opened 2016-10-19 03:24 UTC by abatula

Fixes #4879

### Changes
When a user aborts an active quest, print a message to the party.

![questabort](https://cloud.githubusercontent.com/assets/2165770/19504637/d2eaec26-9589-11e6-83a2-24e6186dc3df.png)

If these changes look ok, I'll work on a test for it.

----
UUID: f5a68145-b375-4b99-8fb4-f9ff7a2c52b5

2016-10-20 02:39 UTC, crookedneighbor requested changes

2016-10-20 02:39 UTC, crookedneighbor commented on website/server/controllers/api-v3/quests.js
> +    group.sendChat(`\`${user.profile.name} aborted the party quest ${questName}.\``);
We should probably have tests around this behavior.

2016-10-22 02:01 UTC, abatula commented
Added two test cases to check that party message is sent.

2016-10-24 03:07 UTC, abatula commented
I'm stumped on why the check is failing. 

It looks like the failing check is a line in a [test for checking a cast spell](https://github.com/HabitRPG/habitica/blob/f1bb2db73b5dc8ff54114662e9a86647f3bba320/test/api/v3/integration/user/POST-user_class_cast_spellId.test.js#L159). I don't know why this becomes a problem, does something about creating a stub for the chat function affect later files?

I also tried using a similar check to the previously mentioned function:
`expect(questingGroup.chat[0]).to.exist;
  expect(questingGroup.chat[0].uuid).to.equal('system');`
But this causes an issue with coupon codes and payment, as shown [here.](https://gist.github.com/abatula/a364a13386d3cd8098dd3ad699bd776d)

I can't see how any of these issues are related to my test code.

2016-11-02 02:34 UTC, abatula commented
Fixed the issue with the test, just needed to restore the `sendChat` function after testing.

2016-11-20 01:27 UTC, abatula commented
Are there any other changes needed for this pull request before it can be merged?

2016-11-20 07:07 UTC, Alys commented
I've tested this locally and confirmed that the message is inserted in party chat as desired, and that the test works correctly (i.e., changing the message that the test expects to see causes the test to fail; setting it to the expected value allows the test to pass). 

I'm not good enough with our code base to properly review the quality of the new code but it looks okay to me. I'll merge this PR in about four days if there's no other comments. @abatula Feel free to post a reminder here if none of us have merged or made comments after five days.

2016-11-25 19:53 UTC, abatula commented
Checking in to see if there are any requested changes to this pull request, or if it's ready to go.

2016-11-25 22:17 UTC, Alys commented
@abatula Thanks for the reminder. I was overloaded with real-live work the past couple of days. I'll merge it later today since no one else has commented.

2016-11-26 07:48 UTC, merged

2016-11-26 07:54 UTC, Alys commented
@abatula Thank you! I've noted this as credit towards your next tier.