Allow guilds to be edited by staff and moderators - fixes #6721
HabitRPG/habitica pull request #8152
Opened 2016-10-19 06:54 UTC by wdavew

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes [6721](https://github.com/HabitRPG/habitica/issues/6721)

### Changes
Staff and moderators can now edit guilds as if they were guild leaders. This includes editing descriptions and titles, assigning leadership, and removing members / invites. These changes only apply to guilds, not parties, and are only meant to be used in rare circumstances.

Once these changes are agreed upon and merged, the wiki's Guilds page should be updated to contain a section similar to "Staff and Moderators' Permissions" in the Challenges page.

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID: 5d0ce005-8e73-476d-ad03-707ec0bb5520

2016-10-20 02:38 UTC, crookedneighbor submitted a review, later dismissed
At a first glance, this looks pretty good.

Left some comments and you have quite a few linting errors to take care of, but

2016-10-20 02:38 UTC, crookedneighbor commented on website/server/controllers/api-v3/groups.js
> +    let optionalMembership = user.contributor.admin ? true : false;
Is the ternary needed here?

2016-10-20 02:38 UTC, crookedneighbor commented on website/views/options/social/group.jade
> +            span(ng-if='group.leader._id == user.id || (user.contributor.admin === true && group.type === "guild")')
Since this logic is now more complex and used multiple places, it should be put onto `$scope` instead in the client controller for the group.

2016-10-20 02:38 UTC, crookedneighbor commented on test/api/v3/integration/groups/PUT-groups.test.js
> +
Extra space here.

2016-10-20 06:57 UTC, wdavew commented on website/server/controllers/api-v3/groups.js
> +    let optionalMembership = user.contributor.admin ? true : false;
@crookedneighbor 
After a second look I don't think the ternary or any conversion to a boolean is really needed. `user.contributor.admin` is either `undefined` or `true`.  The `optionalMembership` argument to `getGroup` in the server side group model is checked for strict equality against `true`,  but _not_ `false`, so I can take the ternary out and it should be fine.

2016-10-20 06:57 UTC, wdavew commented on website/views/options/social/group.jade
> +            span(ng-if='group.leader._id == user.id || (user.contributor.admin === true && group.type === "guild")')
@crookedneighbor 
Good point, thanks. It looks like you specifically highlighted just the administrator portion of this condition, so I'll plan on only moving that logic to the controller. But could we also abstract the whole thing into a method like `$scope.isAbleToEditGroup`?

2016-10-20 11:13 UTC, crookedneighbor commented on website/views/options/social/group.jade
> +            span(ng-if='group.leader._id == user.id || (user.contributor.admin === true && group.type === "guild")')
Yes, I would move the whole thing.

2016-10-24 13:45 UTC, khipkin commented on website/server/controllers/api-v3/groups.js
> +    let optionalMembership = user.contributor.admin;
Suggestion: `Boolean(user.contributor.admin)`

2016-10-24 16:53 UTC, wdavew commented on website/server/controllers/api-v3/groups.js
> +    let optionalMembership = user.contributor.admin;
Thanks, I had also missed one of the other ternaries in this commit so I'll fix this and take into account your suggestion.

2016-11-20 11:24 UTC, Alys commented
Hi @wdavew . Is this ready for review again?

2016-11-21 03:36 UTC, wdavew commented
Hi @Alys -- yes, this is ready for review. On Travis one test is failing regarding exporting history to CSV, but I'm not sure why. It seems to be passing on my local server.

2017-02-26 09:46 UTC, paglias requested changes

2017-02-26 09:46 UTC, paglias commented on test/api/v3/integration/groups/POST-groups_id_removeMember.test.js
> +      expect(_.findIndex(invitedUserWithoutInvite.invitations.guilds, { id: guild._id })).eql(-1);
Heads up, we're migrating to lodash v4 (https://github.com/HabitRPG/habitica/pull/8495) which includes many breaking changes (https://github.com/lodash/lodash/wiki/Changelog#v400). Before merging this PR should be checked and updated to make sure all lodash methods are compatible with v4.

2017-04-21 16:09 UTC, TheHollidayInn commented
Test locally with non admin and admin.

2017-04-22 20:00 UTC, Alys commented
I think website/common/locales/en/groups.json has been given Windows line endings.

2017-04-22 21:26 UTC, TheHollidayInn commented
Yea, I am pretty sure I messed that up :P I'll fix it.

2017-06-08 19:53 UTC, TheHollidayInn commented
Closing for #8800

2017-06-08 19:54 UTC, closed without merging

2017-06-08 20:45 UTC, TheHollidayInn commented
Congratz on tier 1, @wdavew!