Group plan subscription
HabitRPG/habitica pull request #8153
Opened 2016-10-19 11:35 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

This adds Group Subscriptions. More specifically:

1. There is now a subscription tab on the group page
2. Users can create a group sub with Stripe, Update their card, and Cancel
3. Users can create a group sub with Paypal and cancel
4. Users can create a group sub with Amazon and cancel

A few things will need to be set up for this to work:

1. Stripe needs a group_monthly plan added via the console
2. Paypal needs a group monthly plan added via the rest API and the P-[id] will need to be added to the config.json
3. I believe amazon should work by itself

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID:

2016-10-19 12:08 UTC, paglias requested changes

2016-10-19 12:08 UTC, paglias commented on scripts/paypalBillingSetup.js
> +// var blocks = require('../website/common').content.subscriptionBlocks;
even if we don't actively use this file these changes should be reverted probably

2016-10-19 12:08 UTC, paglias commented on test/api/v3/unit/libs/payments.test.js
> +    group = generateGroup({
generateGroup is an async function, it should use `await`. And it already saves the group, no need to call .save() later

2016-10-19 12:08 UTC, paglias commented on website/client-old/js/services/paymentServices.js
> +      var paymentMethod = group.purchased.plan.paymentMethod;
paymentMethod is already declared

2016-10-19 12:08 UTC, paglias commented on website/common/script/content/index.js
> +  group_monthly: {
we should have discounted plans for those who subscribe in advance for 1 whole year

2016-10-19 12:08 UTC, paglias commented on website/server/controllers/api-v3/groups.js
> +    let groupFields = basicGroupFields.concat(' description memberCount balance purchased');
group.purchased shouldn't be hidden to anyone except the leader / paying group member?

2016-10-19 12:08 UTC, paglias commented on website/server/controllers/top-level/payments/amazon.js
> +    if (groupId) {
blank line above the if

2016-10-19 12:08 UTC, paglias commented on website/server/controllers/top-level/payments/amazon.js
> +      let group = await Group.findById(groupId).exec();
limit returned fields? at least remove the chat. Also there's no handling if the group isn't found or on who's cancelling the subscription to have the necessary permissions

2016-10-19 12:08 UTC, paglias commented on website/server/controllers/top-level/payments/paypal.js
> +      let group = await Group.findById(groupId).exec();
only fetch necessary field, also missing security checks

2016-10-19 12:08 UTC, paglias commented on website/server/controllers/top-level/payments/paypal.js
> +      let group = await Group.findOne({ 'purchased.plan.customerId': req.body.recurring_payment_id });
limit returned fields

2016-10-19 12:08 UTC, paglias commented on website/server/controllers/top-level/payments/stripe.js
> +      let group = await Group.findById(groupId).exec();
limit returned fields and security checks

2016-10-19 12:08 UTC, paglias commented on website/server/controllers/top-level/payments/stripe.js
> +      let group = await Group.findById(groupId).exec();
limit returned fields and security checks

2016-10-19 12:08 UTC, paglias commented on website/server/libs/payments.js
> +    group = await Group.findById(data.groupId).exec();
limit returned fields and security checks

2016-10-19 12:08 UTC, paglias commented on website/server/libs/payments.js
> +    group = await Group.findById(data.groupId).exec();
limit returned fields and security checks

2016-10-19 12:08 UTC, paglias commented on website/server/libs/payments.js
> +  let group;
sometimes cancelSubscription is passed groupId and sometimes the entire group https://github.com/HabitRPG/habitica/pull/8153/files#diff-1e4a176d299b36b0817c230e499db62dR287

2016-10-19 12:08 UTC, paglias commented on website/server/models/group.js
> +    plan: {
let's abstract these fields between user and group with a shared sub model

2016-10-20 08:12 UTC, TheHollidayInn commented on website/common/script/content/index.js
> +  group_monthly: {
I believe they haven't decided on pricing in Slack yet. It should be fairly straightforward to add other plans though.

2016-10-20 08:13 UTC, TheHollidayInn commented on website/server/controllers/api-v3/groups.js
> +    let groupFields = basicGroupFields.concat(' description memberCount balance purchased');
Do you mean, shouldn't be shown? I do need to check if there is an active subscription though - for all users.

2016-10-20 08:15 UTC, TheHollidayInn commented on website/server/libs/payments.js
> +  let group;
Ah, yea. I'm unsure how those tests passed... I'll look into that.

2016-10-20 08:19 UTC, paglias commented on website/common/script/content/index.js
> +  group_monthly: {
Let's add a yearly plan anyway with same pricing as the user's yearly plan. We can change it later

2016-10-20 08:21 UTC, paglias commented on website/server/controllers/api-v3/groups.js
> +    let groupFields = basicGroupFields.concat(' description memberCount balance purchased');
Yes, group.purchased has some private data that should only be shown to the paying user. You can use a virtual property to show the subscription status

2016-10-21 08:48 UTC, TheHollidayInn commented on test/api/v3/unit/libs/payments.test.js
> +    group = generateGroup({
I don't believe the unit generateGroup is async:

```
export function generateGroup (options = {}) {
  return new Group(options);
}
```

And, saving is required, I believe.

2016-10-21 08:54 UTC, TheHollidayInn commented on website/server/libs/payments.js
> +  let group;
Actually, I am not seeing where the entire group is passed. I haven't updated the code, but I remember your link showing a place... now I can't find it.

2016-10-21 09:04 UTC, TheHollidayInn commented on website/server/libs/payments.js
> +  let group;
Nevermind

2016-10-22 13:39 UTC, paglias commented on website/server/models/subscriptionPlan.js
> +  timestamps: true,
timestamps can be removed

2016-10-22 13:40 UTC, paglias requested changes

2016-10-22 13:40 UTC, paglias commented on website/server/models/subscriptionPlan.js
> +  minimize: false, // So empty objects are returned
let's add `_id: false` since it'll only be used as an embedded doc

2016-10-22 13:40 UTC, paglias commented on website/server/models/user/schema.js
> +    plan: {type: SubscriptionPlanSchema, default: () => {
hmm, do we need the default here?

2016-10-22 15:04 UTC, TheHollidayInn commented on website/server/models/user/schema.js
> +    plan: {type: SubscriptionPlanSchema, default: () => {
Yes, I'm pretty sure we do from the tests, but I'm not sure if this default is correct. When running some of the tests, the user pruchase.plan property was access, but since it didn't have a default, it was always empty. When, I added the default object (after looking at other abstracted schemas), everything seemed to work.

2016-10-22 15:04 UTC, TheHollidayInn commented on website/server/models/subscriptionPlan.js
> +  minimize: false, // So empty objects are returned
Works for me

2016-10-24 10:11 UTC, TheHollidayInn commented
This should be updated!

2016-10-24 20:00 UTC, paglias commented on test/api/v3/unit/libs/payments.test.js
> +    group = generateGroup({
you're right, I got confused with the helper named the same way but for integration tests

2016-10-24 20:12 UTC, paglias requested changes

2016-10-24 20:12 UTC, paglias commented on website/server/models/user/schema.js
> +    plan: {type: SubscriptionPlanSchema, default: () => {
sounds good, we'll do some testing to be sure it doesn't mess with anything

2016-10-24 20:12 UTC, paglias commented on website/server/libs/payments.js
>    let plan = data.user.purchased.plan;
can we move this plan = .... to and `else if` in case we're not dealing with a group? it makes things easier to understand

2016-10-24 20:12 UTC, paglias commented on website/server/libs/payments.js
>    let plan = data.user.purchased.plan;
same here https://github.com/HabitRPG/habitica/pull/8153/files#diff-422c79cb5a6d7e0e43593f8edf7d7a71R43

2016-10-24 20:12 UTC, paglias commented on website/server/controllers/top-level/payments/stripe.js
> +    let customerId = user.purchased.plan.customerId;
else if when not dealing with a group

2016-10-24 20:12 UTC, paglias commented on website/server/controllers/top-level/payments/stripe.js
> +    if (!subscription) {
we risk deleting the user's personal subscription here if they have both? There's a way to be sure we're cancelling the personal one or the group one based on the situation?

2016-10-24 20:12 UTC, paglias commented on website/server/controllers/top-level/payments/stripe.js
>      let customerId = user.purchased.plan.customerId;
else if in case we're not dealing with a group

2016-10-24 20:12 UTC, paglias commented on website/server/controllers/top-level/payments/stripe.js
> +    let groupId = req.body.groupId;
validation for groupId param

2016-10-24 20:12 UTC, paglias commented on website/server/controllers/top-level/payments/stripe.js
> +    let groupId = req.body.groupId;
hmm actually I see there's no validation for any of the params for these routes even before this PR

2016-10-24 20:12 UTC, paglias commented on website/server/controllers/top-level/payments/amazon.js
> +    let lastBillingDate = user.purchased.plan.lastBillingDate;
else if in case we're not dealing with a group

2016-10-24 20:12 UTC, paglias commented on website/server/controllers/api-v3/groups.js
> +    if (group.purchased.plan.customerId) group.purchased.active = true;
group.purchased.active is defined as a field, why it's necessary to set it manually?

2016-10-25 10:43 UTC, TheHollidayInn commented on website/server/libs/payments.js
>    let plan = data.user.purchased.plan;
Yep, yep. I always try to avoid using else when possible, but I am fine to change it as well.

2016-10-25 10:44 UTC, TheHollidayInn commented on website/server/controllers/api-v3/groups.js
> +    if (group.purchased.plan.customerId) group.purchased.active = true;
It is a pseudo field. The data is never saved. It is just used here to tell users without access to the customer information that the group does have an active subscription.

2016-10-25 10:45 UTC, TheHollidayInn commented on website/server/controllers/top-level/payments/stripe.js
> +    if (!subscription) {
Good point. I think I can just add a else if check.

2016-10-25 10:55 UTC, paglias commented on website/server/controllers/api-v3/groups.js
> +    if (group.purchased.plan.customerId) group.purchased.active = true;
Yeah but you defined it into the model https://github.com/HabitRPG/habitica/pull/8153/files#diff-b6f239870392ed0ec2a2b73cbebaa699R97. If it's a pseudo field it should not be added to the model but to the JSON representation. You can use the toJSONTransform function

2016-10-25 12:10 UTC, TheHollidayInn commented on website/server/controllers/api-v3/groups.js
> +    if (group.purchased.plan.customerId) group.purchased.active = true;
It looks like `toJSONCleanChat` returns a group json object. I will just remove the field from the group model.

2016-10-30 13:55 UTC, paglias approved these changes

2016-11-01 20:51 UTC, merged