Made fixes to Issue 8016
HabitRPG/habitica pull request #8155
Opened 2016-10-19 18:26 UTC by RussWilkie

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID:

2016-10-19 22:12 UTC, crookedneighbor requested changes

2016-10-19 22:12 UTC, crookedneighbor commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file.

2016-10-19 22:12 UTC, crookedneighbor commented on website/views/options/social/group.jade
> +                      | {{member.profile.name}}
Please remove the extra white space you added.

2016-10-19 23:32 UTC, RussWilkie commented on website/views/options/social/group.jade
> +                      | {{member.profile.name}}
Made the changes and re-committed. Would I need to do another pull request?

2016-10-20 02:03 UTC, closed without merging

2016-10-20 02:04 UTC, crookedneighbor commented
I manually merged in your change because it looks like you had some trouble rebasing.

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

2016-10-20 14:05 UTC, RussWilkie commented
@crookedneighbor Sweet! User Id: b8ee1cb8-601e-4928-ad4c-297b815db36b

2016-10-20 22:14 UTC, crookedneighbor commented
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!