Group approval ui
HabitRPG/habitica pull request #8184
Opened 2016-11-04 02:08 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

- Adds all group plan UI
- Added approval tab to groups with subscriptions
- Added requires approval option to group tasks
- Added list of approvals that can be approved
- Added notifications when an approval is requests
- Added notification when task has been approved

[//]: # (Put User ID in here - found in Settings -> API)
----
UUID:

2016-11-08 20:29 UTC, paglias commented
Can we have a few screenshots?

2016-11-08 20:36 UTC, paglias requested changes

2016-11-08 20:36 UTC, paglias commented on test/api/v3/integration/tasks/groups/GET-approvals_group_id.test.js
> +    await expect(member.post(`/tasks/${syncedTask._id}/score/up`))
this is a beforeEach block, not a test, why it has an expectation?

2016-11-08 20:36 UTC, paglias commented on test/api/v3/integration/tasks/groups/POST-group_tasks_id_score_direction.test.js
> +    expect(user.notifications[0].data.groupId).to.equal(guild._id);
this expectation and the 3 ones above seem to be un-related to the scope of the test that is showing that a task that need approval cannot be scored

2016-11-08 20:36 UTC, paglias commented on website/client-old/js/components/groupApprovals/groupApprovalsController.js
> +      if (!confirm("Are you sure you want to approve this?")) return;
in locale file and I would  change it to "...approva this task?"

2016-11-08 20:36 UTC, paglias commented on website/server/controllers/api-v3/tasks.js
> -      return res.respond(200, {message: res.t('taskApprovalHasBeenRequested'), task});
not sure this should be an error but I'd like to discuss it because maybe the 200 response isn't the best fit either

2016-11-08 20:36 UTC, paglias commented on website/server/controllers/api-v3/tasks/groups.js
> +    .populate('userId', 'profile')
this means that it'll populate the userId field with `user.profile`?

2016-11-08 22:35 UTC, TheHollidayInn commented on test/api/v3/integration/tasks/groups/GET-approvals_group_id.test.js
> +    await expect(member.post(`/tasks/${syncedTask._id}/score/up`))
Ehh. I was catching the thrown error this way. I will switch it to a try..catch.

2016-11-08 22:37 UTC, TheHollidayInn commented on test/api/v3/integration/tasks/groups/POST-group_tasks_id_score_direction.test.js
> +    expect(user.notifications[0].data.groupId).to.equal(guild._id);
These are all related to the expectations of what happens when the use case of seeking approval to score a task that needs approval. Are you wanting me to separate these expectations to a separate test more like a unit test?

2016-11-08 22:39 UTC, TheHollidayInn commented on website/server/controllers/api-v3/tasks.js
> -      return res.respond(200, {message: res.t('taskApprovalHasBeenRequested'), task});
Yea, I had this as a 200 at first, but that didn't make sense. The error has some benefits on as well. Not sure what is best though.

2016-11-08 22:40 UTC, TheHollidayInn commented on website/server/controllers/api-v3/tasks/groups.js
> +    .populate('userId', 'profile')
This should limit the fields: http://mongoosejs.com/docs/populate.html, then scroll down to Field selection

2016-11-09 09:31 UTC, paglias commented on website/server/controllers/api-v3/tasks/groups.js
> +    .populate('userId', 'profile')
👍

2016-11-09 18:14 UTC, TheHollidayInn commented
# Main Group Screen
![2016-11-09](https://cloud.githubusercontent.com/assets/1253400/20149175/c1cec744-a675-11e6-93e8-57428a5e185f.png)

# Marking a task as needs approval
![2016-11-09 1](https://cloud.githubusercontent.com/assets/1253400/20149181/cb74a318-a675-11e6-9d0f-00bdf0aae094.png)

# Approval Requested Notification
![2016-11-09 2](https://cloud.githubusercontent.com/assets/1253400/20149192/dc3ee08c-a675-11e6-84ce-eff2deb4de85.png)

# Viewing Approvals
![2016-11-09 3](https://cloud.githubusercontent.com/assets/1253400/20149201/e361e5e4-a675-11e6-8596-a16004b84a89.png)

2016-11-09 18:39 UTC, paglias commented
1. I think we should use a different icon for the notification
2. The green Approve button should be spaced
3. Under "{{Task Name}} for user: {{user}} Approve Button" in the last screenshot it looks like there should be extra content (the white box under the grey title)

2016-11-10 17:44 UTC, TheHollidayInn commented
@paglias Sounds good. Which icon should we use for the notification?

2016-11-12 22:47 UTC, merged