Fills In Previously Skipped Unit Tests for revive.js
HabitRPG/habitica pull request #8193
Opened 2016-11-06 01:42 UTC by rrgayhart

### Changes

Fills in unit tests that were skipped/pending for `revive.js`.

----
UUID: 4f82317e-6f0c-4855-9512-3b9b8ca0017d

2016-11-06 03:37 UTC, crookedneighbor requested changes
Overall, 👍 . Just a few nitpicky comments.

2016-11-06 03:37 UTC, crookedneighbor commented on test/common/ops/revive.js
> +  it('it decreases a random state from str, con, per, int by one', () => {
state -> stat

2016-11-06 03:37 UTC, crookedneighbor commented on test/common/ops/revive.js
> +    expect(message).to.equal('');
I don't think it's important to assert on the empty message here.

2016-11-06 03:37 UTC, crookedneighbor commented on test/common/ops/revive.js
> +    user.items.gear.owned[eyewearKey] = true;
To make sure that this is the only owned item, let's do:

```js
user.items.gear.owned = {
  eyewear_special_yellowTopFrame: true, // eslint-disable-line camelcase
};
```

It's okay to use the full key name when setting it up and making the assertion. Not DRY, but it makes the test easier to read.

2016-11-06 03:37 UTC, crookedneighbor commented on test/common/ops/revive.js
> +    user.items.gear.owned[weaponKey] = true;
Same comment as my previous comment.

2016-11-06 03:59 UTC, rrgayhart commented
@crookedneighbor 👍 - changes made - lmk if you see more revisions!

2016-11-07 03:17 UTC, merged

2016-11-07 03:42 UTC, crookedneighbor commented
Notated toward your next tier.