#8190 Fix: PM-blocking a player does not stop them inviting you to a party or guild
HabitRPG/habitica pull request #8206
Opened 2016-11-11 19:19 UTC by rrgayhart

Fixes #8190 

### Changes

- Fixes issue where blocking a player does not stop them from inviting you to a party of guild
- Moves shared logic of detecting a blockedUser to it's own function
- Adds unit and integration testing

----
UUID: 4f82317e-6f0c-4855-9512-3b9b8ca0017d

2016-11-15 04:41 UTC, crookedneighbor requested changes

2016-11-15 04:41 UTC, crookedneighbor commented on website/common/script/libs/userBlockPresent.js
> +  let userBlockedSender = receiver.inbox.blocks.indexOf(sender._id) !== -1;
Let's make this a bit more DRY

```js
function isBlocked(user1, user2) {
  return user1.inbox.blocks.indexOf(user2._id) !== -1
}

module.exports = function userBlockPresent (sender, receiver) {
  let userBlockedSender = isBlocked(receiver, sender);
  let senderBlockedReceiver = isBlocked(sender, receiver);
  return userBlockedSender || senderBlockedReceiver;
};
```

2016-11-15 04:41 UTC, crookedneighbor commented
Overall, seems reasonable.

2016-11-15 06:05 UTC, khipkin commented on website/common/script/libs/userBlockPresent.js
> +  let userBlockedSender = receiver.inbox.blocks.indexOf(sender._id) !== -1;
I agree! But to be fair, the code was like this originally. 😛

2016-11-15 14:49 UTC, crookedneighbor commented on website/common/script/libs/userBlockPresent.js
> +  let userBlockedSender = receiver.inbox.blocks.indexOf(sender._id) !== -1;
![Picard Nodding](https://media.giphy.com/media/l2SqcJPdAq0oaiZNu/giphy.gif)

2016-11-15 14:50 UTC, crookedneighbor commented
Looks to me like this isn't used anywhere on the client. We may want to implement this logic later on the client, but for now it should be moved to a server lib instead.

2016-11-18 23:44 UTC, rrgayhart commented on website/common/script/libs/userBlockPresent.js
> +  let userBlockedSender = receiver.inbox.blocks.indexOf(sender._id) !== -1;
😭 ❤️

2016-11-18 23:45 UTC, rrgayhart commented
@crookedneighbor Changes implemented! LMK if you see additional adjustments!

2016-11-19 05:10 UTC, khipkin commented on test/api/v3/integration/groups/POST-groups_invite.test.js
> +    it('returns error when to receiver has blocked the inviter', async () => {
"the" receiver 😈

2016-11-20 17:59 UTC, rrgayhart commented on test/api/v3/integration/groups/POST-groups_invite.test.js
> +    it('returns error when to receiver has blocked the inviter', async () => {
😱 Haha - will fix right now!

2016-11-30 20:46 UTC, rrgayhart commented
@crookedneighbor - Quick ping reminder that this PR is ready to be re-looked at when you're able!

2016-12-11 02:08 UTC, TheHollidayInn commented on website/server/controllers/api-v3/members.js
> +    if (userBlock || userOptedOutOfMessaging) {
You should add a new test for this route.

2016-12-11 02:09 UTC, TheHollidayInn commented
I'm a little late to the review, but I added one comment. Overall, this looks really good. Your coding style is nice.

2017-06-07 23:59 UTC, SabreCat commented
This covers a lot of the same ground as https://github.com/HabitRPG/habitica/commit/018976a7231683420acd982bf9705b0046846840 ; I think for this we should expand that functionality to cover these scenarios rather than implement a parallel check. Closing this for now.

2017-06-07 23:59 UTC, closed without merging