Docker improvements
HabitRPG/habitica pull request #8297
Opened 2016-12-18 19:32 UTC by DrStrangepork

#8288

### Changes
Fixes #8288 
Dockerfile was missing node module `mocha`
Configuration/Documentation updates

----
UUID: 30983c37-52c3-415d-977c-38af6c7db91c

2016-12-19 15:11 UTC, paglias requested changes

2016-12-19 15:11 UTC, paglias commented on .dockerignore
> +website
why was this ignored but not other project folders? Like /gulp, /webpack, ...

2016-12-19 15:11 UTC, paglias commented on bower.json
> -  "version": "0.1.1",
isn't the version number required? Also I'd just skip changes to bower.json, thanks but we're going to ditch it with the redesign that is in progress

2016-12-19 15:32 UTC, DrStrangepork commented on .dockerignore
> +website
I added what I knew was not needed, and this list resulted in a significant speed increase, so I felt it safe to stop there. If there are other folders that you know are also unneeded, I'd be happy to add them.

2016-12-19 15:34 UTC, paglias commented on .dockerignore
> +website
@DrStrangepork I have to say I'm no Docker expert but website is the folder that contains the entire source code, why isn't it needed?

2016-12-19 15:35 UTC, DrStrangepork commented on bower.json
> -  "version": "0.1.1",
According to https://github.com/bower/spec/blob/master/json.md, version has been deprecated.
But if bower has a timeline itself to be deprecated in Habitica, then I will these changes out of the PR.

2016-12-19 15:41 UTC, DrStrangepork commented on .dockerignore
> +website
The .dockerignore file manages the build context that gets sent to the service during the build process. In Habitica's case, we're building a stand-alone image that pulls its own`git clone` of Habitica, builds it and serves it, so there is little that _must_ be passed to the docker service (theoretically, everything except Dockerfile could be excluded). The /website directory gets created within the image as part of its local Habitica repo and build process, so it doesn't need to be passed on to docker.

2016-12-19 15:49 UTC, DrStrangepork commented on .dockerignore
> +website
In my local install, the 3 directories included consist of >98% of the total size of my habitica folder, so there would be very little speed increase in adding any additional folders.

2016-12-19 19:28 UTC, paglias commented on .dockerignore
> +website
If only Dockerfile is needed what about

```
# Ignore everything
*

# But not Dockerfile
!Dockerfile
```

2016-12-19 23:43 UTC, DrStrangepork commented on .dockerignore
> +website
I can test that out

2016-12-28 00:18 UTC, DrStrangepork commented on .dockerignore
> +website
`docker-compose up` with above `.dockerignore`:

    real	1m27.618s
    user	0m23.492s
    sys	0m9.614s

`docker-compose up` with `.dockerignore` from this PR:

    real	0m12.910s
    user	0m0.856s
    sys	0m0.414s

2016-12-28 08:33 UTC, paglias commented on .dockerignore
> +website
Sounds good!

2016-12-28 08:33 UTC, merged

2016-12-28 08:34 UTC, paglias commented
Notated towards your next tier