Group plans reorder tasks
HabitRPG/habitica pull request #8358
Opened 2017-01-02 20:15 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

- Added a new endpoint for reordering group tasks
- Added front end check to see if we need to reorder group task and to call the correct end point if so

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-01-04 15:07 UTC, paglias commented on website/server/controllers/api-v3/tasks/groups.js
> +    // If for some reason the task isn't ordered (should never happen), push it in the new position
is it possible to abstract this logic so that we don't duplicate code between group and user (and maybe challenges) tasks reordering?

2017-01-04 15:08 UTC, paglias requested changes

2017-01-04 15:08 UTC, paglias commented on website/server/controllers/api-v3/tasks/groups.js
> +    });
missing .exec()

2017-01-04 21:07 UTC, Alys commented
Challenge task reordering is much desired.

On Wed, 4 Jan 2017, 15:08 Matteo Pagliazzi <notifications@github.com> wrote:

> *@paglias* commented on this pull request.
> ------------------------------
>
> In website/server/controllers/api-v3/tasks/groups.js
> <https://github.com/HabitRPG/habitica/pull/8358#pullrequestreview-15127364>
> :
>
> > +
> +    if (!task) {
> +      throw new NotFound(res.t('taskNotFound'));
> +    }
> +
> +    if (task.type === 'todo' && task.completed) throw new BadRequest(res.t('cantMoveCompletedTodo'));
> +
> +    let group = await Group.getGroup({user, groupId: task.group.id, fields: requiredGroupFields});
> +    if (!group) throw new NotFound(res.t('groupNotFound'));
> +
> +    if (group.leader !== user._id) throw new NotAuthorized(res.t('onlyGroupLeaderCanEditTasks'));
> +
> +    let order = group.tasksOrder[`${task.type}s`];
> +    let currentIndex = order.indexOf(task._id);
> +
> +    // If for some reason the task isn't ordered (should never happen), push it in the new position
>
> is it possible to abstract this logic so that we don't duplicate code
> between group and user (and maybe challenges) tasks reordering?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8358#pullrequestreview-15127364>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABbTATRnM4Kujuj_U1OHA3_e3CAtCwooks5rO7W9gaJpZM4LZMVq>
> .
>

2017-01-10 18:53 UTC, TheHollidayInn commented
Updated.

2017-01-10 19:52 UTC, paglias commented
Looks good 👍 a unit test for the move task would be perfect but feel free to merge it without

2017-01-11 18:16 UTC, merged