Add tags to default tasks
HabitRPG/habitica pull request #8419
Opened 2017-01-18 00:00 UTC by MathWhiz

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8360 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-01-18 04:42 UTC, MathWhiz commented
![screenshot 2017-01-17 at 10 42 18 pm](https://cloud.githubusercontent.com/assets/12386291/22051137/3d375f88-dd06-11e6-8d88-c579367cb2d4.png)
It worked!

2017-01-18 14:57 UTC, TheHollidayInn commented
Can you add tests for this? When a user register - tasks are created with correct tags?

2017-01-19 00:41 UTC, MathWhiz commented
Unit test?

2017-01-19 05:31 UTC, TheHollidayInn commented
Yea, most of these hooks (if not all) trigger before a user is saved. So, you can add a test to this file: https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/unit/models/user.test.js . To ensure the tasks are created correctly.

2017-02-19 00:51 UTC, MathWhiz commented
I am not sure how to write a test for this.

2017-02-20 22:22 UTC, TheHollidayInn commented on test/api/v3/integration/user/auth/POST-register_local.test.js
> +      let habits = await user.get('/tasks/user?type=habits');
The above does not return a user attached to a request object. `user.get` is produced from our helper functions.

2017-02-20 22:22 UTC, TheHollidayInn commented on test/api/v3/integration/user/auth/POST-register_local.test.js
> +      expect(habits[0].tags).to.have.a.lengthOf(3);
These should check more than just length.

2017-02-26 04:09 UTC, MathWhiz commented
@TheHollidayInn Would you be able to take a look at my test to see what I should change? I am not sure how to debug a test, as the output of the test is not very helpful.

2017-02-26 09:55 UTC, paglias requested changes

2017-02-26 09:55 UTC, paglias commented on website/server/models/user/hooks.js
> +        newTask.tags = _.map(taskDefaults.tags, findTag);
Heads up, we're migrating to lodash v4 (https://github.com/HabitRPG/habitica/pull/8495) which includes many breaking changes (https://github.com/lodash/lodash/wiki/Changelog#v400). Before merging this PR should be checked and updated to make sure all lodash methods are compatible with v4.

2017-02-26 21:15 UTC, MathWhiz commented on website/server/models/user/hooks.js
> +        newTask.tags = _.map(taskDefaults.tags, findTag);
It appears that `_.map` is not affected significantly in the upgrade to v4, so everything should be good.

2017-02-26 21:54 UTC, MathWhiz commented
@TheHollidayInn @paglias I fixed the test!

![5sldpwb - imgur](https://cloud.githubusercontent.com/assets/12386291/23344074/9fc41ed0-fc3b-11e6-9d03-172c075285ff.gif)

2017-02-28 14:03 UTC, paglias requested changes

2017-02-28 14:03 UTC, paglias commented on website/server/models/user/hooks.js
> +  function findTag (tagName) {
can this function be defined at the root level of the file instead of inside another function?

2017-02-28 14:03 UTC, paglias commented on website/server/models/user/hooks.js
> +        newTask.tags = _.map(taskDefaults.tags, findTag);
what if a tag isn't found in user.tags? We don't want to have task.tags include undefined or null values. Probably you'll want to call `_.compact` on the result https://lodash.com/docs/4.17.4#compact

2017-03-01 03:55 UTC, MathWhiz commented
@paglias Fixed ~~I hope~~!

2017-03-01 15:58 UTC, MathWhiz commented
Travis CI is having an error loading the build it did for my latest commit. What should I do?

2017-03-01 16:12 UTC, paglias requested changes

2017-03-01 16:12 UTC, paglias commented on website/server/models/user/hooks.js
> +   let tagID = _.find(user.tags, (userTag) => {
is user available at this point? Shouldn't it be passed as an argument?

2017-03-01 16:13 UTC, paglias commented
@MathWhiz not sure about the travis error, let's see if the build starts with a new commit (probably needed to resolve conflicts)

2017-03-01 16:13 UTC, MathWhiz commented on website/server/models/user/hooks.js
> +   let tagID = _.find(user.tags, (userTag) => {
That might be it. Will be updating

2017-03-01 16:38 UTC, paglias commented
Build seems to have started. If it passes this LGTM @TheHollidayInn

2017-03-01 16:38 UTC, paglias approved these changes

2017-03-01 20:00 UTC, MathWhiz commented
Another Travic CI error :(

2017-03-01 20:33 UTC, TheHollidayInn commented
They said they have some down time

2017-03-02 14:36 UTC, paglias requested changes

2017-03-02 14:36 UTC, paglias commented on website/server/models/user/hooks.js
> +  return tagID.id
missing semicolon

2017-03-02 14:36 UTC, paglias commented on website/server/models/user/hooks.js
> +   let tagID = _.find(user.tags, (userTag) => {
extra indentation

2017-03-02 16:12 UTC, MathWhiz commented
@paglias All fixed!

2017-03-02 17:11 UTC, paglias commented
thanks :)

2017-03-03 13:57 UTC, paglias commented
Tested locally and it works, thanks!

2017-03-03 13:57 UTC, paglias approved these changes

2017-03-03 13:57 UTC, merged