Ability to delete account as a social user
HabitRPG/habitica pull request #8438
Opened 2017-01-21 00:13 UTC by rachel-ftw

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #7417

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Updated so that users without a local log in information can still delete their account by typing DELETE instead of a password. When the settings page is loaded if `user.auth.local.email` is present then the modal requiring the password pops up. If it's not present then it's assumed that the person is logged in via social and they're given the DELETE modal.

The user route handles verification, and checks if both `user.auth.local.email` & `user.auth.local.hashed_password` are true and if so, uses the previous written flow to delete a user. 

If `user.auth.google.id` or `user.auth.facebook.id` are true then the logic checks that the user wrote DELETE (case sensitive).

#### File Changes
- **front.json & settings.json**: added phrases that match the updated UI elements.
- **website/server/controllers/api-v3/user.js**: added an `else/if` statement that checks if the user has a local or social log in and check the respective expected input entry.
- **website/views/options/settings.jade**: added another button and if logic to both so the correct button will display depending on whether or not the user has local auth.
- **website/views/shared/modals/settings.jade**: added the social modal content.

I'd love it if someone could give me some reflections on the best things to test the validity of a local user account. Can someone get an email into local if they don't have a local registration? I couldn't get a real idea of what social user data is stored in `user.auth.google/facebook`, is looking for `.id` specific enough?

Looking forward to reflections 💃 

big ups to @pllearns for writing the testing and @deonna for help and support <3 

----
rachel-ftw's UUID: 97f4775f-0e99-47cd-8002-63a062972bf6

2017-01-21 00:22 UTC, rachel-ftw commented
Added image to initial comment: 
![social delete modal](https://cloud.githubusercontent.com/assets/17391810/22169792/ee5db948-df2b-11e6-84a9-84ee7732385e.png)

and referenced [phil's testing PR](https://github.com/HabitRPG/habitica/pull/8429)

2017-01-22 14:39 UTC, Alys commented
@rachel-ftw If you haven't already, see my comment here and the one after it: https://github.com/HabitRPG/habitica/issues/7417#issuecomment-274313672
That might answer some of your questions. Tell us if you have others.

2017-01-22 17:50 UTC, TheHollidayInn reviewed
Looks good. I believe I saw test in a separate PR. Are you two working together on this?

2017-01-22 17:50 UTC, TheHollidayInn commented on website/server/controllers/api-v3/user.js
> +      if(req.body.password !== 'DELETE') {
I would combine this with the above `else if`

2017-01-22 17:50 UTC, TheHollidayInn commented on website/server/controllers/api-v3/user.js
> +      if(req.body.password !== 'DELETE') {
Also, let's move DELETE up to be a const.

2017-01-23 00:46 UTC, Alys commented on website/server/controllers/api-v3/user.js
> +      if(req.body.password !== 'DELETE') {
"DELETE" is intended to be translatable so a constant wouldn't work.

2017-01-23 18:35 UTC, rachel-ftw commented on website/server/controllers/api-v3/user.js
> +      if(req.body.password !== 'DELETE') {
fixed the `else if`

2017-01-23 18:37 UTC, rachel-ftw commented
@TheHollidayInn Yah, @pllearns and I were working together on it. ❤️

2017-01-25 19:22 UTC, TheHollidayInn commented
Awesome, if you can fix the linting issues and merge conflicts, I'll check the other PR is well.

2017-02-26 09:56 UTC, paglias requested changes

2017-02-26 09:56 UTC, paglias commented on website/server/controllers/api-v3/user.js
> +      req.checkBody({
req.checkBody doesn't do anything unless you call req.validationErrors() and then throw the error if it exists, like it's done a few lines above

2017-06-07 19:25 UTC, SabreCat commented
Continuing this in #8796. @rachel-ftw, if you'd like to resume work on this yourself, you need only say the word!

2017-06-07 19:25 UTC, closed without merging