Repeatables
HabitRPG/habitica pull request #8444
Opened 2017-01-22 00:08 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
This adds the business logic for the following:
1. Every X weeks
2. Every X Months
3. Every month on a day of the month
4. Every month on a day of the week
5. Every X years

Todo:
- [ ] Combine exery X with day of the week, month, etc
- [ ] Add model fields in separate PR
- [ ] Add UI in separate PR

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-01-29 22:01 UTC, paglias commented on website/common/script/cron.js
> +import 'moment-recur';
this has to be added to package.json

2017-01-29 22:04 UTC, paglias commented on website/common/script/cron.js
> +import 'moment-recur';
also it doesn't seem very updated https://github.com/c-trimm/moment-recur/issues

2017-01-29 23:04 UTC, TheHollidayInn commented on website/common/script/cron.js
> +import 'moment-recur';
Yea, I emailed the author and will fork it if need be.

2017-01-31 03:44 UTC, TheHollidayInn commented
![monthly-screenshot](https://cloud.githubusercontent.com/assets/1253400/22451577/f533547c-e72c-11e6-8c95-755e4c4885ef.PNG)

2017-01-31 10:13 UTC, paglias commented on package.json
> +    "moment-recur": "^1.0.5",
before merging we should recompile the shrinkwrap.json file

2017-01-31 10:18 UTC, paglias requested changes

2017-01-31 10:18 UTC, paglias commented on website/client-old/js/services/taskServices.js
> +      'su': 'Sunday',
can we use i18n strings here? moment.locale should be available in the client https://momentjs.com/docs/#/i18n/

2017-01-31 10:18 UTC, paglias commented on website/client-old/js/services/taskServices.js
> +    var numberToShortDay = {
this map already exists in common/script/cron.js

2017-01-31 16:17 UTC, TheHollidayInn commented on website/client-old/js/services/taskServices.js
> +      modalScope.task._edit.repeatsOn = 'dayOfMonth';
@TODO: Check for old tasks without this property.

2017-02-02 16:38 UTC, TheHollidayInn commented on website/client-old/js/services/taskServices.js
> +    var numberToShortDay = {
Is there a way to share that map without being able to import?

2017-02-02 16:39 UTC, paglias commented on website/client-old/js/services/taskServices.js
> +    var numberToShortDay = {
Common core is accessible in the client through window.habitrpgShared or the Shared angular service

2017-02-06 17:14 UTC, khipkin commented on test/common/shouldDo.test.js
> +  context('Monthly - Every Day of the month', () => {
Suggestion: "Every X Day of the month", otherwise the meaning is unclear.

2017-02-06 17:16 UTC, khipkin commented on test/common/shouldDo.test.js
> +  context('Monthly - Every Day of the week', () => {
"Certain Days of Every X Week"

2017-02-06 17:20 UTC, khipkin commented on website/client-old/js/services/taskServices.js
> +      var summary = 'Repeats ' + task._edit.frequency + ' every ' + task._edit.everyX + ' ' + frequencyPlural;
This needs to be localizable if it will be displayed to the user.

2017-02-06 17:21 UTC, khipkin commented on website/common/script/cron.js
> +export function shouldDo (day, dailyTask) {
If the `options` param is removed from the callee, then it should be removed from all callers as well.

2017-02-06 17:23 UTC, khipkin commented on website/server/models/task.js
> +  daysOfMonth: {type: [Number], default: []}, // Days of the month that the daily should repeat on
What if invalid values are given? Ex: day 10 of the week, day 40 of the month, etc.  Or even day 30 might be problematic during February.

2017-02-06 17:23 UTC, khipkin commented on website/views/shared/tasks/edit/advanced_options.jade
> +    div(ng-if='::task.type == "daily"')
Remove trailing whitespace.

2017-02-06 17:24 UTC, khipkin commented on website/views/shared/tasks/edit/advanced_options.jade
> +        label.option-title Repeats
TODO: make these strings localizable.

2017-02-06 20:46 UTC, TheHollidayInn commented on test/common/shouldDo.test.js
> +  context('Monthly - Every Day of the month', () => {
Hmm. I fine with rewording, but every x day can be confused with every x days. This is representing every date (different than the day).

2017-02-06 20:47 UTC, TheHollidayInn commented on test/common/shouldDo.test.js
> +  context('Monthly - Every Day of the week', () => {
I'm thinking "Certain Days on Week (Y)" or something

2017-02-26 10:04 UTC, paglias requested changes

2017-02-26 10:04 UTC, paglias commented on website/common/script/cron.js
> +    for (let [repeatDay, active] of Object.entries(dailyTask.repeat)) {
is object.entries supported by our current babel presets? It's a stage 4 proposal that'll be included in es2017

2017-02-27 17:33 UTC, paglias approved these changes

2017-02-27 22:41 UTC, merged

2017-02-28 11:40 UTC, Alys commented
The edit bug mentioned in my comment at https://github.com/HabitRPG/habitica/pull/8469#issuecomment-282975199 comes from this PR (all other pending PRs don't have it).

When you click on the pencil icon to edit a task, the edit modal doesn't appear.

2017-02-28 16:07 UTC, paglias commented on website/common/script/cron.js
> +import 'moment-recur';
quick question about this: if in the new client we never imports `website/common/script/cron.js` the moment-recur module won't be imported to. Is it necessary to import it for the client side to work? If yes, I'll add it separately