Reordered Magic Hatching Potions, fixes issue 8465
HabitRPG/habitica pull request #8467
Opened 2017-02-02 15:50 UTC by willira2

[//]: #8465 
Fixes https://github.com/HabitRPG/habitica/issues/8465

### Changes
[//]: # Updated Magic Hatching Potion list in hatching-potions.js to order the potions in a more logical pattern. Moved Royal Purple potion to top of the list, and other seasonal potions are now listed from Spring to Winter.

[//]: # 18119562

----
UUID:

2017-02-02 16:38 UTC, SabreCat requested changes

2017-02-02 16:38 UTC, SabreCat commented on website/common/script/content/hatching-potions.js
> -  Spooky: {
Looks like whitespacing got adjusted by accident--it doesn't have a functional impact, but the standard in our code is two spaces per indent.

2017-02-02 19:20 UTC, willira2 commented on website/common/script/content/hatching-potions.js
> -  Spooky: {
Whoops, I'll fix that. I didn't notice it in Sublime Text but I can see it in vim.

2017-02-03 21:18 UTC, SabreCat commented
@willira2: Nice! Of course, now there are Cupid Potions to incorporate. :cat::sweat_drops: If you rebase this branch onto `develop`, that'll resolve the merge conflict. And maybe the Cupid potions could go to the top, preceding the springtime potions.

2017-02-03 23:14 UTC, willira2 commented
@SabreCat To do this, I just need to go onto the branch where I was working on this and run "git rebase develop"? I'm still learning git D:

2017-02-04 00:51 UTC, Alys commented
@willira2 First do `git fetch upstream` to download the latest material from the official repository.

Then do `git rebase upstream/develop` on the branch you were working on.

2017-02-04 00:56 UTC, willira2 commented
@Alys Thank you! Ok, I've done that. Hopefully that resolves the conflict?

2017-02-04 00:59 UTC, Alys commented
Ah, sorry, I should have said: To make the rebase be added to your pull request, you also need to push your changes to your own fork of the repo in GitHub. That will be something like `git push origin issue8465`

2017-02-04 01:23 UTC, willira2 commented
@SabreCat Do you mind taking me off this issue? Changing the file is no problem, but my git skills (or lack thereof) are proving to be the challenge. It's such an easy fix that I hate to keep it in limbo like this.

2017-02-04 03:47 UTC, SabreCat commented
@willira2 All good--I can do the rebase and incorporate the Cupid potions. What's your Habitica UUID so I can credit you for the rest?

2017-02-04 03:51 UTC, Alys commented
@willira2 We can take you off the issue if you wish, but we can also talk you through using git. This is a low priority issue so there's no rush to get it done!

If there were merge conflicts when you rebased, we can help you resolve them. If you're not sure, and if the output of the rebase is still on screen, you can paste it here or take a screenshot. 

If you're having trouble pushing the rebased code to github, I can give you more detailed steps.

Just let us know! :)

2017-02-04 03:58 UTC, willira2 commented
@SabreCat I'll give it one last shot with @Alys 's help. 

@Alys , rebasing went through, but when I went to push, this is what I got:

![screen shot 2017-02-03 at 10 56 31 pm](https://cloud.githubusercontent.com/assets/18119562/22615527/1fb36e78-ea64-11e6-9574-ffe101de55ed.png)

Thanks to both of you for helping me!

2017-02-04 04:13 UTC, Alys commented
(@SabreCat sorry! Your reply hadn't appeared when I'd posted mine.)

@willira2 That's not an uncommon thing and is usually easy to fix, but it can occasionally indicate a problem that needs to be resolved first, so before pushing we should check that what you're about to push is okay. Can you please do this:
`git diff origin/issue8465  website/common/script/content/hatching-potions.js`
and show us the output?

And by the way, if it all seems to go horribly wrong, we can recover your work! Git lets us go back to good commits so fixes are easy. :)

2017-02-04 04:20 UTC, willira2 commented
@SabreCat ok, here's the output of that command:

![screen shot 2017-02-03 at 11 18 46 pm](https://cloud.githubusercontent.com/assets/18119562/22615647/421b63c8-ea67-11e6-9e4a-ce52ea6b4f10.png)

2017-02-04 04:48 UTC, Alys commented
@willira2 Can you do this command and show us the output?

`git remote  -v`

It sounds like `origin` might not be the local name for your GitHub fork.

2017-02-04 05:10 UTC, willira2 commented
@Alys 
![screen shot 2017-02-04 at 12 09 34 am](https://cloud.githubusercontent.com/assets/18119562/22615904/43fec0c0-ea6e-11e6-8d43-856ef43ad74d.png)

2017-02-04 08:55 UTC, Alys commented
That's all good, and now that I look at the error message more closely, it's complaining about the path to the file - sorry about that, I should have noticed.

Were you running `git diff origin/issue8465 website/common/script/content/hatching-potions.js` in the top-level directory in your local install? I.e., in the `habitica` directory that contains files like config.json and package.json? That's where it should be run.

2017-02-04 17:08 UTC, willira2 commented
@Alys  oh whoops, I was not. This looks better: 
![screen shot 2017-02-04 at 12 07 22 pm](https://cloud.githubusercontent.com/assets/18119562/22620140/b15ce1ec-ead2-11e6-8781-abf749449c28.png)

2017-02-04 19:14 UTC, SabreCat commented
Great! There's a couple of things going on here:

* You can see changes to this file that took place while you were working on this PR in that `git diff` output: `return pot._season === 'winter'` was replaced with `return pot._season === 'valentines'` because we moved from Winter Wonderland to the Valentine's mini event. But git doesn't know if your PR is supposed to switch it back to `winter` or not. Make sure that line includes the `valentines` bit instead, before committing and pushing.
* When you rebase, your local branch ends up with a different sequence of commits than the one you have stored on GitHub. That's why you get the `failed to push some refs` error, because git can't resolve the situation by just tacking a new commit on to the end of your PR. To tell git to overwrite the remote branch, making it back into an exact copy of your local branch, use the `--force` switch on your `git push`.

2017-02-04 19:52 UTC, willira2 commented
@SabreCat Ok, I've checked the file and made sure it was correct, per your specifications. I'm going to try committing and pushing it again with the --force switch.

2017-02-08 19:14 UTC, SabreCat approved these changes

2017-02-08 19:14 UTC, merged

2017-02-08 19:15 UTC, SabreCat commented
Perfect! @willira2, what's your Habitica UUID, if any? You'll get contributor tier credit for this!

2017-02-27 02:11 UTC, willira2 commented
@SabreCat , sorry, just saw this! My UUID is 75e6d5ff-9e9d-4ddf-a03c-bc2e0e07605b. Thanks again to you and @Alys for the help!

2017-02-27 17:24 UTC, SabreCat commented
@willira2 Great! Congratulations on becoming a Tier 1 Blacksmith. 😺 Note that subsequent tiers require increasing amounts of effort from one to the next, so Tier 2 will require multiple PRs or a more substantial PR to attain. But keep helping out and we'll express our gratitude accordingly!