[WIP] Content turn gear to models
HabitRPG/habitica pull request #8486
Opened 2017-02-10 18:42 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-02-11 11:56 UTC, paglias requested changes

2017-02-11 11:56 UTC, paglias commented on website/client-old/js/controllers/tasksCtrl.js
> +      $scope.itemStore = Shared.updateStore(User.user, Content);
why is the store updated twice?

2017-02-11 11:56 UTC, paglias commented on website/client-old/js/services/sharedServices.js
> +        gearItem.text = function (language) {
shouldn't already be translated from the server?

2017-02-11 11:56 UTC, paglias commented on website/common/script/content/gear/sets/armoire.js
> +    textlocaleKey: 'armorArmoireLunarArmorText',
I don't think this is necessary, the server should return already translated texts

2017-02-11 11:56 UTC, paglias commented on website/server/controllers/api-v3/content.js
> +    // if (cachedContentResponses[language] === true) {
I'm quite sure we want to keep caching

2017-03-07 03:11 UTC, khipkin commented
Suggestion: Replace 133 instances of "notesLocalKey" with "Notes**Locale**Key".

2017-06-12 18:30 UTC, TheHollidayInn commented
Closing this because from the redesign we are able to import parts of the common files using Webpack. I think the new importing method will allow us to migrate to "CMS" like features on portions of the content at a time rather than the whole content collection.

2017-06-12 18:30 UTC, closed without merging