Subscription end date should format according to user's preference
HabitRPG/habitica pull request #8514
Opened 2017-02-26 22:33 UTC by megantiu

Fixes #8506 

### Problem
On the Settings > Subscription page, a canceled subscription's end date is always formatted `MM/dd/yyyy`, even when the user's preferred date format differs.

### Solution
Use the user's chosen date format instead of hard-coding the USA format.

<img width="501" alt="screen shot 2017-02-26 at 5 27 34 pm" src="https://cloud.githubusercontent.com/assets/12753198/23344353/04865f4c-fc49-11e6-9484-21195b4c3247.png">

### Details
The date formatting method takes arguments in all-caps (like `MM/DD/YYYY`), whereas we store it as `MM/dd/yyyy`, so I called on `toUpperCase()` on `user.preferences.dateFormat`.

----
UUID: bd794f6e-3845-49e5-88cc-a140b24cdea4

2017-02-27 14:22 UTC, crookedneighbor requested changes
Good catch.

Have you tried using the date filter instead of moment to accomplish this? 

https://github.com/HabitRPG/habitica/blob/7fc2500bfd0b22303dd8c30f5166b9350d4542c7/website/views/shared/modals/members.jade#L18

I'd prefer that route.

2017-02-28 01:23 UTC, megantiu commented
Oh cool, I hadn't! I'm not much of a Javascript developer (a full-time Rubyist myself), so this is still a learning process for me. Thanks for pointing out the correct Angular way to do it! 😄 Changes made.

2017-02-28 20:51 UTC, TheHollidayInn commented
This works locally for me.

2017-03-03 18:49 UTC, paglias commented
I think we can merge

2017-03-03 18:52 UTC, merged

2017-03-10 19:57 UTC, megantiu commented
Hey, sorry to bother, but I just realized: will this count toward/as my next contributor tier?

2017-03-10 20:35 UTC, Alys commented
@megantiu Thank you so much for asking and I'm sorry we didn't handle that already! Every PR that's merged counts towards a tier (not always a complete tier by itself), so you're right to ask when we don't say anything!

I've noted this in your Habitica account as credit towards tier 3.

2017-03-10 20:38 UTC, megantiu commented
Thanks for the clarification/credit, @Alys! I appreciate it 🙂