ApiDoc Group
HabitRPG/habitica pull request #8516
Opened 2017-02-27 16:35 UTC by MathWhiz

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Part of #8087

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-02-28 20:21 UTC, TheHollidayInn commented
I think this just need success and param examples on each route and then it is good.

2017-03-01 16:39 UTC, paglias requested changes

2017-03-01 16:39 UTC, paglias commented on website/common/locales/en/groups.json
> +  "possessiveParty": "<%= name %>'s Party",
are these new strings expected?

2017-03-01 16:41 UTC, MathWhiz commented
They were there when I merged develop in, so I have no idea
On Wed, Mar 1, 2017 at 10:40 AM Matteo Pagliazzi <notifications@github.com>
wrote:

> *@paglias* requested changes on this pull request.
> ------------------------------
>
> In website/common/locales/en/groups.json
> <https://github.com/HabitRPG/habitica/pull/8516#discussion_r103729311>:
>
> > @@ -102,6 +102,7 @@
>    "messageSentAlert": "Message sent",
>    "pmHeading": "Private message to <%= name %>",
>    "pmsMarkedRead": "Your private messages have been marked as read",
> +  "possessiveParty": "<%= name %>'s Party",
>
> are these new strings expected?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8516#pullrequestreview-24525647>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_840EmyfSUptx_uHbP8AiI9RnOmrfks5rhZ9igaJpZM4MNVLS>
> .
>

2017-03-01 16:42 UTC, paglias commented
yeah, it's strange, can you remove them?

2017-03-01 17:16 UTC, TheHollidayInn commented
I added those in when merging as well. I thought they were from some new PR.

2017-03-01 17:22 UTC, paglias commented
now it's even stranger, with a full file differing. Can you close this pr and open a new one from a clean develop branch?

2017-03-01 17:31 UTC, TheHollidayInn commented
I see this issue often with merging locals.

2017-03-01 18:29 UTC, MathWhiz commented
Could there be something wonky with the line endings in the locales?

2017-03-01 18:51 UTC, TheHollidayInn commented
Yea I definitely think it is with white characters. Probably my fault, tbh

2017-03-01 19:59 UTC, MathWhiz commented
New PR located at #8522

2017-03-01 19:59 UTC, closed without merging