Enabled repeatables
HabitRPG/habitica pull request #8572
Opened 2017-03-15 20:13 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-03-15 22:15 UTC, Alys commented
I'd like us to take a very cautious approach to testing and merging this. We had bugs last time that weren't picked up by our automated tests, so I'd like to see the tests improved first, and then this merged after that.

The bugs were from people who had non-zero Custom Day Start times and were viewing their Dailies after midnight but before the CDS time, so I suspect that the tests don't cover that case. There might be other cases too. I'll try to make time this weekend to think about all the cases that might need to be tested and see if we have tests for them.

2017-03-16 05:03 UTC, TheHollidayInn commented
Yea, this is because we had no automated tests before - so refactoring becomes an issue. We will have to try and think of all the manual tests/features.

2017-03-16 05:04 UTC, TheHollidayInn commented
Yea, this is because we had no automated tests before - so refactoring becomes an issue. We will have to try and think of all the manual tests/features.

2017-03-16 13:39 UTC, paglias commented on website/common/script/cron.js
> -import _ from 'lodash'; // eslint-disable-line lodash/import-scope
I hadn't noticed this but we should really avoid importing the entire lodash in common or in client. Adding one exception defats the entire purpose of only loading individual utilities

2017-03-16 13:40 UTC, paglias commented
This need to wait for the isNextDue PR for the mobile apps anyway?

2017-03-16 14:49 UTC, TheHollidayInn commented on website/common/script/cron.js
> -import _ from 'lodash'; // eslint-disable-line lodash/import-scope
I'll update it! This was before I saw the lodash update.

2017-03-16 14:49 UTC, TheHollidayInn commented
The UI needs to wait, but nextDue depends on this shouldDo

2017-03-19 09:57 UTC, Alys commented
I've listed all the `shouldDo` tests that I think are necessary for the current behaviour at https://github.com/HabitRPG/habitica/issues/8585

2017-04-09 16:47 UTC, paglias commented
This is waiting on some mobile changes ans the isDue PR right?

2017-04-09 19:46 UTC, Alys commented
Also waiting on new tests for the current repeat behaviour. Our tests weren't sufficient to pick up a bug when this first went live.

2017-05-12 13:47 UTC, paglias requested changes

2017-05-12 13:47 UTC, paglias commented on website/common/script/cron.js
> +    let differenceInMonths = moment(day).month() + 1 - moment(startDate).month() + 1;
why plus 2 months here?

2017-05-12 13:47 UTC, paglias commented on website/server/controllers/api-v3/tasks.js
> +      let optionsForShouldDo = cloneDeep(user.preferences.toObject());
toObject already clones objects so calling deepClone is not necessary, see https://github.com/Automattic/mongoose/issues/5008

2017-05-12 13:56 UTC, TheHollidayInn commented on website/common/script/cron.js
> +    let differenceInMonths = moment(day).month() + 1 - moment(startDate).month() + 1;
Yea, I guess we don't need this since I am adding it to both sides :P

2017-05-12 13:57 UTC, TheHollidayInn commented on website/server/controllers/api-v3/tasks.js
> +      let optionsForShouldDo = cloneDeep(user.preferences.toObject());
Ah, nice.

2017-05-12 17:24 UTC, SabreCat commented
Non-blocking question. There are two more Daily features we would eventually like, to finish out the use cases:

* "Active until completed" option. Example: "Pay rent" comes due on the first of each month. On June 1 the Daily is active. If I check it off, it will be active again July 1. But if I _don't_ complete it, it's still active on June 2, 3, etc. Once I get around to taking care of it, it'll go inactive until July 1.
* "X times in Y interval" method. For things like "work out three times a week" or "call parents twice a month" or whatever. This would necessitate a distinction between Dailies _appearing active_ vs. _causing penalties when missed_; if there's still enough days left in the interval to satisfy the condition, it doesn't hurt you. But if you get to the point where there are X or fewer days left in the interval, missing it kicks in the usual damage, degrades the Daily's color, and so on.

These features needn't be in scope for this. But how much refactoring would be necessary to incorporate them later? Would the Repeatables code here need to be substantially rewritten to accommodate the above, or could we extend/tweak the logic without too much waste?

2017-05-12 17:30 UTC, SabreCat commented
Issue: the summary line "Repeats [frequency] every [X] [intervals]" is hardcoded in English. Should be an I18N string with variables.

2017-05-12 17:34 UTC, SabreCat commented
Non-blocking existing issue we could maybe clean up here: Every X can go below 1. Should stop at 1.

2017-05-25 00:49 UTC, merged