Change icon for NPC achievement
HabitRPG/habitica pull request #8628
Opened 2017-03-31 02:16 UTC by MathWhiz

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8611 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-04-09 16:41 UTC, paglias requested changes

2017-04-09 16:41 UTC, paglias commented on website/common/script/content/achievements.js
> -    icon: 'achievement-ultimate-warrior',
is this icon still used somewhere else? If not it should be removed

2017-04-09 17:13 UTC, MathWhiz commented
It is used in the ultimate warrior achievement, I believe.
On Sun, Apr 9, 2017 at 11:41 AM Matteo Pagliazzi <notifications@github.com>
wrote:

> *@paglias* requested changes on this pull request.
> ------------------------------
>
> In website/common/script/content/achievements.js
> <https://github.com/HabitRPG/habitica/pull/8628#discussion_r110546565>:
>
> > @@ -107,7 +107,7 @@ let specialAchievs = {
>      textKey: 'contribText',
>    },
>    npc: {
> -    icon: 'achievement-ultimate-warrior',
>
> is this icon still used somewhere else? If not it should be removed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8628#pullrequestreview-31728537>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_88lRLmJyRbUbVL3X2ioUSb-oeo7fks5ruQo0gaJpZM4MvJF8>
> .
>

2017-04-09 17:17 UTC, khipkin commented on website/common/script/content/achievements.js
> -    icon: 'achievement-ultimate-warrior',
it's used for the ultimate warrior achievement.

2017-04-09 17:20 UTC, paglias approved these changes

2017-04-09 17:22 UTC, paglias commented
ok, another question: i saw in the folder all images have both a 2x and a normal resolution image while this PR only adds the 2x image. Isn't the normal one missing?

2017-04-09 17:51 UTC, MathWhiz commented
I was not provided a non-2x version.
On Sun, Apr 9, 2017 at 12:22 PM Matteo Pagliazzi <notifications@github.com>
wrote:

> ok, another question: i saw in the folder all images have both a 2x and a
> normal resolution image while this PR only adds the 2x image. Isn't the
> normal one missing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8628#issuecomment-292799353>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_89olcH_wn3oJAtAt3JsBkykMh3h_ks5ruRPLgaJpZM4MvJF8>
> .
>

2017-04-09 17:52 UTC, paglias commented
Cc @beffymaroo

2017-04-09 18:25 UTC, MathWhiz commented
@paglias As I understand it, sprites are created in 1x scale and then are scaled up.

2017-04-09 22:05 UTC, awitherow approved these changes
Considering it is the only image attached to the issue, perhaps we should get this merged...

2017-04-09 22:07 UTC, paglias commented
I'm just unsure this will work properly without the 1x version. Checking
with @SabreCat

Il 10 Apr 2017 00:05, "Austin Witherow" <notifications@github.com> ha
scritto:

> *@awitherow* approved this pull request.
>
> Considering it is the only image attached to the issue, perhaps we should
> get this merged...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8628#pullrequestreview-31735630>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAkAV8fbOvTBnlCsYbl5NctfekU7VSa-ks5ruVYvgaJpZM4MvJF8>
> .
>

2017-04-10 18:34 UTC, SabreCat commented
I'm not aware of anyplace we still use the 1x version of achievements since the overhaul of the cheevos page @khipkin did a while back. We should be OK with just the 2x version!

2017-04-12 03:41 UTC, khipkin commented
Yeah I can't think of anywhere still using the 1x versions. I think now they're just legacy. 😛

2017-04-12 03:48 UTC, khipkin commented
#7904 for reference

2017-04-22 18:52 UTC, merged

2017-04-22 18:53 UTC, SabreCat commented
@MathWhiz Merged, thank you! I will add this to your growing Tier 6 progress list.

2017-04-22 19:38 UTC, MathWhiz commented
😄
On Sat, Apr 22, 2017 at 1:54 PM Sabe Jones <notifications@github.com> wrote:

> @MathWhiz <https://github.com/MathWhiz> Merged, thank you! I will add
> this to your growing Tier 6 progress list.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8628#issuecomment-296393917>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_81wBJ2GDajw261dP7AfMlbSl59fqks5rykzHgaJpZM4MvJF8>
> .
>