Added wintery skins to content
HabitRPG/habitica pull request #8645
Opened 2017-04-03 18:31 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

This PR adds the winter skins to our content list

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-04-03 20:48 UTC, paglias commented on features.config.json
> +{
was this meant to be in the PR?

2017-04-03 21:05 UTC, SabreCat commented on features.config.json
> +{
That looks like the enterprise plans config file. Wayward `git add -A`?

2017-04-03 21:17 UTC, TheHollidayInn commented on features.config.json
> +{
UGhh, my bad

2017-04-06 03:59 UTC, khipkin commented on website/common/script/content/appearance/skin.js
> +  'snowy': {price: 2, set: sets.winterySkinColors},
Are snowy and winterstar intentionally different from the rest?

2017-04-11 19:30 UTC, SabreCat requested changes
Should be `winterySkins` instead of `winterySkinColors` on those last couple of lines. Good to go after that!

2017-04-17 20:13 UTC, TheHollidayInn commented
Fixed. Sorry for the delay.

2017-04-18 19:30 UTC, SabreCat approved these changes

2017-04-22 18:54 UTC, merged