Require Dailies to have a Start Date
HabitRPG/habitica pull request #8649
Opened 2017-04-04 02:46 UTC by MathWhiz

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #7715 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-04-09 16:37 UTC, paglias requested changes

2017-04-09 16:37 UTC, paglias commented on website/views/shared/tasks/edit/repeatables.jade
> +fieldset.option-group.advanced-option(ng-show="task.type === 'daily'")
what changed in this file? Can't see from git diff

2017-04-09 16:37 UTC, paglias commented on website/server/models/task.js
> +    required: true,
Test needed

2017-04-09 17:20 UTC, MathWhiz commented on website/views/shared/tasks/edit/repeatables.jade
> +fieldset.option-group.advanced-option(ng-show="task.type === 'daily'")
I

2017-04-09 17:21 UTC, MathWhiz commented on website/views/shared/tasks/edit/repeatables.jade
> +fieldset.option-group.advanced-option(ng-show="task.type === 'daily'")
I can't tell either

2017-04-09 17:21 UTC, khipkin commented on website/views/shared/tasks/edit/repeatables.jade
> +fieldset.option-group.advanced-option(ng-show="task.type === 'daily'")
Append `?w=1` to the URL to ignore whitespace changes, and you'll see that only whitespace changed.

2017-05-12 14:42 UTC, MathWhiz commented
@paglias Ping!

2017-05-18 11:29 UTC, paglias commented
This looks good but it'll probably require a migration for tasks that don't have the field unless we want to give it a default value. Ideas?

2017-05-18 11:29 UTC, paglias approved these changes

2017-05-18 11:36 UTC, Alys commented on website/views/shared/tasks/edit/repeatables.jade
> +fieldset.option-group.advanced-option(ng-show="task.type === 'daily'")
The file has Windows line breaks in it in `develop`, so I'm guessing this change removes them and uses just Unix line breaks, which is consistent with the majority of other files in the repo.

2017-05-18 11:40 UTC, Alys commented
There's some discussion of the default value in the issue although I'm thinking now that for simplicity and speed we should just go with a default value of "today".

2017-05-20 19:15 UTC, MathWhiz commented
@paglias @Alys What should I change?

2017-05-28 01:43 UTC, Alys commented
@MathWhiz sorry about the delay on your question. My feeling is that with the code that you have now, you probably don't need to change anything regarding the default date. When a new Daily is created, it is always given the correct default date (today) so that part is fine as it is. The `required: true` that you've added should prevent the date being removed. I believe the `type: Date` code that was already there should prevent someone saving a value that isn't a date. So with this PR I think the API has everything it needs.

Ideally, there'd be code on the website to give a friendly error message to the user if they try to delete the start date, but since we're rewriting the website and since deleting the start date is probably rare, I don't think it's a critical thing to add now.

2017-05-28 01:45 UTC, MathWhiz commented
Does that meat that everything looks good?
On Sat, May 27, 2017 at 8:44 PM Alys <notifications@github.com> wrote:

> @MathWhiz <https://github.com/mathwhiz> sorry about the delay on your
> question. My feeling is that with the code that you have now, you probably
> don't need to change anything regarding the default date. When a new Daily
> is created, it is always given the correct default date (today) so that
> part is fine as it is. The required: true that you've added should
> prevent the date being removed. I believe the type: Date code that was
> already there should prevent someone saving a value that isn't a date. So
> with this PR I think the API has everything it needs.
>
> Ideally, there'd be code on the website to give a friendly error message
> to the user if they try to delete the start date, but since we're rewriting
> the website and since deleting the start date is probably rare, I don't
> think it's a critical thing to add now.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8649#issuecomment-304487340>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8xpzR7kWbaj8HTeKLCS2iwXyVIvMks5r-NFigaJpZM4MyUt_>
> .
>

2017-05-29 10:20 UTC, paglias approved these changes
Can be merged for me!

2017-06-06 02:17 UTC, MathWhiz commented
Ping? I am really sorry for bugging you all, but I would really like to know if I am missing anything.

2017-06-06 17:05 UTC, merged

2017-06-06 17:05 UTC, paglias commented
Notated towards your next tier! Thanks and sorry again for the super long delay!

2017-06-06 17:11 UTC, MathWhiz commented
Cool, thanks!