[WIP] New cards — Congratulations, Get Well
HabitRPG/habitica pull request #8655
Opened 2017-04-05 14:51 UTC by MathWhiz

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8610 
Fixes #8609 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-04-05 15:16 UTC, MathWhiz commented
:( How can I fix the decrease in coverage?

2017-04-05 15:38 UTC, TheHollidayInn commented
Hmm. I think it may be checking coverage on the content files. I don't think you should worry.

2017-04-06 04:02 UTC, khipkin commented on website/common/locales/en/generic.json
> +    "congratsCardAchievementText": "It's great to celebrate your friends' achievements! Sent or received <%= count %> Congratulations Cards.",
nit: lowercase "congratulations cards" for consistency with other cards.

2017-04-06 18:31 UTC, MathWhiz commented
@khipkin Updated.

2017-04-07 01:58 UTC, MathWhiz commented
This PR is no longer a work in progress (well, it probably still is, but I have added everything).

2017-04-09 16:35 UTC, paglias requested changes

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +      if (!target.flags) target.flags = {};
target.flags should always exist

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +  congrats: {
what about a test for this?

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +  getwell: {
test for this?

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +      if (!target.flags) target.flags = {};
flags should always exist

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +          if (!u.achievements.getwell) u.achievements.getwell = 0;
`achievements.getwell` shouldn't be added in the user schema?

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +          if (!u.achievements.congrats) u.achievements.congrats = 0;
achievements.getwell shouldn't be added in the user schema?

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +      target.items.special.getwellReceived.push(user.profile.name);
getWellReceived shouldn't be added to the user schema?

2017-04-09 16:35 UTC, paglias commented on website/common/script/content/spells.js
> +      target.items.special.congratsReceived.push(user.profile.name);
congratsReceived shouldn't be added to the user schema?

2017-04-09 17:26 UTC, MathWhiz commented
I'm sorry, @paglias, but I don't understand some of your comments. I copied and pasted the code from the greeting card, so the achievement stuff is copied from that. I also don't see any tests for the other cards.

2017-04-09 17:29 UTC, paglias commented
@MathWhiz no worries, regarding tests it's true that there aren't but I think we should start to write them for a new spells. And regarding the achiements I'm saying that you're setting values to fields that are not defined in /website/server/models/user/schema.js so they won't be saved in the database

2017-04-09 18:23 UTC, MathWhiz commented
What do you mean about the flags?

2017-04-09 18:25 UTC, paglias commented
Same thing, they  have to be defined in the schema or they wont be saved

Il 09 Apr 2017 20:23, "MathWhiz" <notifications@github.com> ha scritto:

> What do you mean about the flags?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-292802894>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAkAVy6v1YieHlDcvFy1tqMb4r79VbCDks5ruSIvgaJpZM4M0W9R>
> .
>

2017-04-24 01:09 UTC, khipkin commented
Looks like only half of the new images have transparent backgrounds.

2017-04-24 01:43 UTC, MathWhiz commented
Whelp, I will fix that as soon as I can
On Sun, Apr 23, 2017 at 8:09 PM Kaitlin Hipkin <notifications@github.com>
wrote:

> Looks like only half of the new images have transparent backgrounds.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-296503073>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8zjT56JHdlNP_drg4mFjP5ARcoCeks5ry_ZOgaJpZM4M0W9R>
> .
>

2017-04-24 03:00 UTC, MathWhiz commented
@paglias 

In regards to tests, here is what I have planned:

1. Cards should return information specified in the [APIdoc](https://habitica.com/apidoc/#api-User-UserBuySpecialSpell)
2. Cards should only work on a user (not sure if done client-side)
3. Cards should increase the achievement for both users when a card is sent
4. Cards should increase the achievement once if a user sends it to themself
5. Returns error with lack of gold
6. I don't know if this is possible, but making sure that spells are only castable when "enabled"

Is there anything I am missing?

2017-04-24 08:12 UTC, paglias commented
@MathWhiz looks like a complete list!

2017-05-08 13:51 UTC, MathWhiz commented
@paglias If you have some time, some help would be greatly appreciated. Tests have never been my forte, and I seem to have figured out how to screw them up.

2017-05-09 14:07 UTC, paglias requested changes

2017-05-09 14:07 UTC, paglias commented on test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
> +    await user.post(`/user/cast/cast/birthday?targetId=${recipient._id}`);
double /cast in the url

2017-05-09 14:07 UTC, paglias commented on test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
> +    await user.post(`/user/cast/cast/birthday?targetId=${user._id}`);
double /cast in the url

2017-05-09 16:41 UTC, MathWhiz commented
Finished! @paglias

2017-05-18 02:26 UTC, MathWhiz commented
It would be greatly appreciated if this pull could be reviewed. Thanks!

2017-05-18 10:55 UTC, paglias approved these changes

2017-05-18 10:56 UTC, paglias commented
Looks good to me! Sorry for the delay @MathWhiz .

@SabreCat can we merge this or any other work is needed?

2017-05-18 10:56 UTC, paglias commented
Note: I haven't tested it locally, only reviewed the code

2017-05-18 17:24 UTC, SabreCat commented
I'll look it over, thanks!

2017-05-25 18:17 UTC, MathWhiz commented
Thank you for looking it over, @SabreCat!

2017-05-28 20:08 UTC, MathWhiz commented
@SabreCat I have made some logic fixes, so you will want to pull again to make sure everything is a-ok.

2017-06-06 19:44 UTC, SabreCat commented
Couple of things here:

The card images in the shop aren't on the right canvas size, so they have inconsistent button sizes vs. the other ones--
![image](https://user-images.githubusercontent.com/4501321/26848499-7fd03bd6-4ab5-11e7-9b46-fad967673257.png)
Looks like they need to be recanvased to 57x54.

Secondly, there are enough cards after these additions that I don't think these belong in the "Special" category of the Market anymore. We should move all the cards out to their own "Cards" Market category, above Special.

2017-06-06 19:46 UTC, SabreCat requested changes
Recanvas, create dedicated Market category (though we can definitely help with the latter if the path forward there is unclear!)

2017-06-06 19:46 UTC, MathWhiz commented
Ok! I can take a look at resizing them/moving them
On Tue, Jun 6, 2017 at 2:45 PM Sabe Jones <notifications@github.com> wrote:

> Couple of things here:
>
> The card images in the shop aren't on the right canvas size, so they have
> inconsistent button sizes vs. the other ones--
> [image: image]
> <https://user-images.githubusercontent.com/4501321/26848499-7fd03bd6-4ab5-11e7-9b46-fad967673257.png>
> Looks like they need to be recanvased to 57x54.
>
> Secondly, there are enough cards after these additions that I don't think
> these belong in the "Special" category of the Market anymore. We should
> move all the cards out to their own "Cards" Market category, above Special.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-306596251>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8yaw7GhrvYmhrDPrGJONq_4XW00Aks5sBaw_gaJpZM4M0W9R>
> .
>

2017-06-06 21:42 UTC, SabreCat commented
One other thing I just noticed--it's best not to include changes to any of the compiled spritesheet data (PNG and CSS) in the PR. Those changes will inevitably get overwritten in production, and it makes the PR harder to review. So if those changes can be reverted to `develop` state on this PR, it'd be a help!

2017-06-06 21:43 UTC, MathWhiz commented
Got it! I will revert them in my next PR

2017-06-06 21:50 UTC, MathWhiz commented
@SabreCat I tried resetting it, but it didn't seem to work properly.

2017-06-06 21:58 UTC, SabreCat commented
Try

```
git checkout develop website/client/assets/* website/static/*
git commit
git push
```

2017-06-06 21:59 UTC, MathWhiz commented
I did :/
On Tue, Jun 6, 2017 at 4:58 PM Sabe Jones <notifications@github.com> wrote:

> Try
>
> git checkout develop website/client/assets/* website/static/*
> git commit
> git push
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-306629625>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_85YpAZyNQ_G6rbnPfzWM6BSTn2NMks5sBcuVgaJpZM4M0W9R>
> .
>

2017-06-06 22:00 UTC, SabreCat commented
Make sure you've checked out and pulled `develop` from the main repo first, perhaps?

2017-06-06 22:22 UTC, SabreCat commented
If you can't get that to work, I just pushed https://github.com/HabitRPG/habitica/tree/MathWhiz/new-cards -- you can cherry-pick f004256.

2017-06-06 22:50 UTC, MathWhiz commented
I'm sorry, but to make sure I understand, can you be a bit more specific
about how to do that?

I have also created the new section:



On Tue, Jun 6, 2017 at 5:00 PM Sabe Jones <notifications@github.com> wrote:

> Make sure you've checked out and pulled develop from the main repo first,
> perhaps?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-306630035>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_83Z_lham-w4twdUB3A9byWQwhEqaks5sBcwIgaJpZM4M0W9R>
> .
>

2017-06-06 22:54 UTC, SabreCat commented
It depends a bit how you have your remotes set up locally. It'd look something like the following, supposing `HabitRPG` is the official repo:

```
git fetch HabitRPG
git checkout develop
git pull HabitRPG develop
git checkout new-cards
git checkout develop website/client/assets/* website/static/*
git commit
git push
```

2017-06-06 22:58 UTC, MathWhiz commented
Won't that also pull stuff I don't want changed?
On Tue, Jun 6, 2017 at 5:54 PM Sabe Jones <notifications@github.com> wrote:

> It depends a bit how you have your remotes set up locally. It'd look
> something like the following, supposing HabitRPG is the official repo:
>
> git fetch HabitRPG
> git checkout develop
> git pull HabitRPG develop
> git checkout new-cards
> git checkout develop website/client/assets/* website/static/*
> git commit
> git push
>
> —
>
>
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-306640223>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_85PuU8blxkEworQohL7W0yhuqtbPks5sBdilgaJpZM4M0W9R>
> .
>

2017-06-06 22:59 UTC, SabreCat commented
Or if you mean the `cherry-pick` strategy:

```
git fetch HabitRPG
git checkout new-cards
git cherry-pick f004256
git push
```

2017-06-06 23:06 UTC, MathWhiz commented
@SabreCat Looks like It worked!

2017-06-06 23:06 UTC, SabreCat commented
Success! 14 files changed, so much easier to work with than 50. Thank you!

2017-06-06 23:08 UTC, MathWhiz commented
You are welcome!

2017-06-07 00:16 UTC, SabreCat commented
Getting this error when attempting to send cards to party members, even existing cards:

![image](https://user-images.githubusercontent.com/4501321/26856937-ce275370-4adb-11e7-82c5-49a0ccf4fba2.png)

Are you able to complete the workflow locally?

2017-06-07 00:18 UTC, MathWhiz commented
It worked for me :/

Oh dear
On Tue, Jun 6, 2017 at 7:16 PM Sabe Jones <notifications@github.com> wrote:

> Getting this error when attempting to send cards to party members, even
> existing cards:
>
> [image: image]
> <https://user-images.githubusercontent.com/4501321/26856937-ce275370-4adb-11e7-82c5-49a0ccf4fba2.png>
>
> Are you able to complete the workflow locally?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-306649930>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_87cwd2faQUZKYByHGpf5xoJa-tsRks5sBevggaJpZM4M0W9R>
> .
>

2017-06-07 00:21 UTC, SabreCat commented on website/common/script/content/spells.js
> -      if (!target.flags) target.flags = {};
I think this is the source of the error I'm hitting. If the target doesn't have the `flags` object, we hit an error when trying to set a property on it. Why were these removed?

2017-06-07 00:22 UTC, MathWhiz commented
@paglias said that they would always exist, there fore to remove them (if I
understood them correctly)
On Tue, Jun 6, 2017 at 7:21 PM Sabe Jones <notifications@github.com> wrote:

> *@SabreCat* commented on this pull request.
> ------------------------------
>
> In website/common/script/content/spells.js
> <https://github.com/HabitRPG/habitica/pull/8655#discussion_r120510367>:
>
> > @@ -452,7 +450,6 @@ spells.special = {
>        if (!target.items.special.greetingReceived) target.items.special.greetingReceived = [];
>        target.items.special.greetingReceived.push(user.profile.name);
>
> -      if (!target.flags) target.flags = {};
>
> I think this is the source of the error I'm hitting. If the target doesn't
> have the flags object, we hit an error when trying to set a property on
> it. Why were these removed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#pullrequestreview-42478456>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8wU32nEHkeG1l2O-AuKLH6k0fnvoks5sBe0YgaJpZM4M0W9R>
> .
>

2017-06-07 00:32 UTC, SabreCat commented
Heh, no, they were saying that if you're saving a value to the database, it needs to be defined in the user schema, or it won't be saved. For achievements, special items, and flags. If all of those are there, you're cool.

2017-06-07 00:34 UTC, MathWhiz commented
> target.flags should always exist
?

2017-06-07 00:35 UTC, SabreCat commented
I don't think it's good practice to rely on that, no, especially given I've encountered an error with it in my own testing.

2017-06-07 00:36 UTC, MathWhiz commented
I was just quoting what @paglias commented.
On Tue, Jun 6, 2017 at 7:35 PM Sabe Jones <notifications@github.com> wrote:

> I don't think it's good practice to rely on that, no, especially given
> I've encountered an error with it in my own testing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-306652518>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8zHvmg5wOA50IhvMMcadg_moYYHBks5sBfBpgaJpZM4M0W9R>
> .
>

2017-06-07 00:38 UTC, SabreCat commented
I can't even find where he said that, sorry :\

2017-06-07 00:41 UTC, MathWhiz commented
It was the fourth review he made in the large batch of them (collapsed)
On Tue, Jun 6, 2017 at 7:38 PM Sabe Jones <notifications@github.com> wrote:

> I can't even find where he said that, sorry :\
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HabitRPG/habitica/pull/8655#issuecomment-306652879>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALz_8y1HLgX64zjcNt--AiBl4fbZ5rZTks5sBfEOgaJpZM4M0W9R>
> .
>

2017-06-07 00:44 UTC, SabreCat commented
Ah, I see it. In any case, perhaps he was mistaken; in common code, it's possible that it's present on the server but not the client, etc.

2017-06-07 01:20 UTC, MathWhiz commented
@SabreCat Ok, I will change it back

2017-06-07 01:27 UTC, MathWhiz commented
@SabreCat ... and done!

2017-06-07 01:45 UTC, SabreCat commented
OK, looks great now! I have one thing I'll probably tweak myself, moving these achievements out of Seasonal to Basic, but it's a preexisting issue with the Greeting and Thank You cards, but it's not necessary for this PR. I'll tag this for merge and credit it to your Blacksmith progress!

2017-06-07 01:47 UTC, MathWhiz commented
:tada: Thanks!

2017-06-07 01:48 UTC, MathWhiz commented
Slowly making progress towards my next tier!

2017-06-07 01:52 UTC, SabreCat approved these changes

2017-06-07 02:04 UTC, merged