Fix android setup process
HabitRPG/habitica pull request #8656
Opened 2017-04-05 20:22 UTC by vIiRuS

This fixes two things that caused issues with the setup process in the android app.

2017-04-05 22:22 UTC, SabreCat requested changes
Looks good but for that failing lint test.

2017-04-06 01:54 UTC, TheHollidayInn commented
Didn't we have this value before? I believe I added this somewhere a while back.

2017-04-06 01:54 UTC, TheHollidayInn commented
We should also add a  test

2017-04-06 20:05 UTC, SabreCat approved these changes

2017-04-06 22:10 UTC, merged