Fix for automatic allocation not persisting fixes #8641
HabitRPG/habitica pull request #8661
Opened 2017-04-08 20:03 UTC by TNychka

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
https://github.com/HabitRPG/habitica/issues/8641

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
- Changed stats.jade so on selection of Automatic Allocation Checkbox, user preference changes are sent in one request. 
- Commented issue on setUser function

The issue was when Automatic allocation is selected on a user's stats page, the changes are not saved. This issue was caused during an update of lodash from version 3 to 4, the root cause being previously the jade profile saved user.preferences.automaticAllocation and _then_ user.preferences.allocationMode one after the other. Some issue in lodash caused the User object not to persist between each call, so only the final call was saved (In this case automaticAllocation was lost but allocationMode was saved). The fix was to send all the changes at once, so when the Automatic allocation checkbox is selected, autoAllocate _and_ allocMode are both sent at the same time. 

---
UUID: f57bd235-ec21-4357-b5c9-a0536294b285

2017-04-09 13:56 UTC, paglias commented on website/client-old/js/services/userServices.js
> +      //Calling this multiple times rapidly will not persist changes
Are changes not persisted locally or on the server? Locally it shouldn't happen as this is a normal sync function

2017-04-09 14:28 UTC, TNychka commented on website/client-old/js/services/userServices.js
> +      //Calling this multiple times rapidly will not persist changes
What I saw was that calling it twice somehow didn't save the user object locally which was then synced. Calling the function with attribute A and then B only saves B for some reason. However if you call the function with A and B then both save.

2017-04-09 16:23 UTC, paglias commented on website/client-old/js/services/userServices.js
> +      //Calling this multiple times rapidly will not persist changes
That's strange.. it's possible that between one call and the other the server responded with the updated user that then overwrote the second call?

2017-04-09 20:27 UTC, TNychka commented on website/client-old/js/services/userServices.js
> +      //Calling this multiple times rapidly will not persist changes
That is a possibility, the two calls issue the setUser call, then an ajax request. If the ajax request overwrites the local version, then that would be the cause. I noticed that I could not replicate the issue while debugging with a breakpoint. If there was a delay (like a breakpoint) the calls probably had time to resolve before the next one was made. If the call could issue a promise or create a queue of requests, that would probably be the best solution. The comment might be unnecessary then.

2017-04-11 19:51 UTC, SabreCat requested changes
Remove `userServices.js` if it wasn't meant to be changed, or commit the changes it should have if it was. After that, we should be OK to merge this!

2017-04-11 19:51 UTC, SabreCat commented on website/client-old/js/services/userServices.js
> +
There don't seem to be any functional changes committed to `userServices`, just this bit of whitespace.

2017-04-11 19:51 UTC, SabreCat commented on website/views/options/profile/stats.jade
> +                    input(type='checkbox', ng-model='user.preferences.automaticAllocation', ng-change='set({"preferences.automaticAllocation": user.preferences.automaticAllocation?true: false, "prefe
It's a little hard to tell thanks to the line-ending change (@TheHollidayInn's Windows dev environment messing with us, heh), but this should be the only line substantially altered, correct?

2017-04-11 22:32 UTC, TNychka commented
@SabreCat alright, cleaned up the whitespacing so now only the stats.jade file has been modified. 
And the only major change to the stats file was 
`ng-change='set({"preferences.automaticAllocation": user.preferences.automaticAllocation, "preferences.allocationMode":"taskbased"})'`
Which sends the two changes along in one request so there is no issue with the syncing to server.

2017-04-12 15:47 UTC, SabreCat approved these changes

2017-04-16 20:48 UTC, Alys commented
I've tested this locally and it's working well. Toggling the "Automatic Allocation" checkbox causes the `preferences.automaticAllocation` field to be toggled in the user's database document.

@TNychka thank you! I've awarded you tier 1. You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

2017-04-16 20:49 UTC, merged