Updated vagrant script to fix bcrypt missing error
HabitRPG/habitica pull request #8670
Opened 2017-04-13 14:13 UTC by yugensoft

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Updated npm version to match http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally
Added npm-pre-gyp dependency necessary for bcrypt to install

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 6365790b-b0ea-4da6-bbe3-f5a217330ad2

2017-04-17 20:31 UTC, TheHollidayInn commented
Looks good to me. @paglias does this seem right to you?

2017-04-18 17:08 UTC, paglias requested changes

2017-04-18 17:08 UTC, paglias commented on vagrant_scripts/install_node.sh
> +npm install -g npm@4.5.0
can this be just npm@4?

2017-04-22 20:01 UTC, yugensoft commented on vagrant_scripts/install_node.sh
> +npm install -g npm@4.5.0
ok sure ill change it

2017-04-22 22:34 UTC, yugensoft commented on vagrant_scripts/install_node.sh
> +npm install -g npm@4.5.0
ok its done

2017-05-06 21:57 UTC, Alys commented
I'm merging this because the current vagrant setup is wrong and this is at the very least an improvement, even if further changes are needed later.

@yugensoft Thank you! I'm awarding you your second tier for this PR and the investigative work needed to get vagrant working.

As your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required.

2017-05-06 21:57 UTC, merged