Allow Multiple Invites in Party (WIP)
HabitRPG/habitica pull request #8683
Opened 2017-04-18 19:56 UTC by Yutsuten

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #7792

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
This will change the number of possible party invitations a user can receive from one to unlimited. For now I only merged @eternal44 commits (#7901) into my branch.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a

2017-04-20 13:33 UTC, paglias commented on website/server/libs/clearPartyInvitation.js
> +  user.markModified('invitations.parties');
is this necessary? Changes should be tracked automatically unless you modify a property of a Mixed field

2017-04-20 13:33 UTC, paglias commented on website/server/libs/clearPartyInvitation.js
> +module.exports = function clearPartyInvitation (user, groupID) {
export default function...?

2017-04-23 05:01 UTC, Yutsuten commented
I haven't changed the visual, but if someone have great ideas in mind, please tell me so I change it!
That how it is looking right now:

![Partial Result](http://i.imgur.com/nBmduM2.png)

The ``invitations.party`` is still being updated with the lastest invitation, so I believe it won't break other applications that use the habitica API.
The ``invitations.parties`` is the brand new array of party invitations.

Now I only need to create some tests for this...
How about the migration? I'll do it or someone else? If it's me, can someone teach me how I create one?

2017-04-24 01:32 UTC, khipkin commented on website/common/locales/en/groups.json
> +  "joinPartyConfirmationText": "Are you sure you want to join the party \"<%= partyName %>\"? You can only be in one party at a time. If you join, all other party invitations will be cancelled.",
Suggestion/nit: "canceled" should be changed to "rejected" to match the button text for rejecting an invitation.

2017-04-24 01:32 UTC, khipkin commented on website/server/controllers/api-v3/groups.js
> +        // make him leave that party before doing anything
"make **them** leave"

2017-04-24 02:23 UTC, Alys commented on website/common/locales/en/groups.json
> +  "joinPartyConfirmationText": "Are you sure you want to join the party \"<%= partyName %>\"? You can only be in one party at a time. If you join, all other party invitations will be cancelled.",
Agreed. That makes it clear that the action taken automatically is the same as can be done manually.

2017-04-24 02:24 UTC, Alys commented on website/server/controllers/api-v3/groups.js
> +        // make him leave that party before doing anything
Ah yes, thanks @khipkin.  @Yutsuten We use [they / them as a singular pronoun](https://en.wikipedia.org/wiki/Singular_they) throughout Habitica to cover people of all genders.

2017-04-24 05:03 UTC, Yutsuten commented on website/server/controllers/api-v3/groups.js
> +        // make him leave that party before doing anything
Oh I haven't even noticed about that. Thank you, I'll change.

2017-04-24 05:03 UTC, Yutsuten commented on website/common/locales/en/groups.json
> +  "joinPartyConfirmationText": "Are you sure you want to join the party \"<%= partyName %>\"? You can only be in one party at a time. If you join, all other party invitations will be cancelled.",
Okay!

2017-04-24 08:20 UTC, paglias requested changes

2017-04-24 08:20 UTC, paglias commented on website/server/models/group.js
> +      user.invitations.parties = [];
this shouldn't remove only one invitation (matching the group variable) instead of all?

2017-04-24 17:51 UTC, Yutsuten commented on website/server/models/group.js
> +      user.invitations.parties = [];
Yes, I'll fix it... And I noticed that there are still a lot of references to ``invitations.party`` in the code, so I need to update them all...

2017-05-02 05:05 UTC, Yutsuten commented
Sorry for not being so active lately, I've got very busy...

Anyway, I think it is done. Tested multiple invites both when the user is not in a party and when he/she already is in a party (playing solo).

So, I'm ready for reviews and tips.

2017-05-09 18:33 UTC, Yutsuten commented
Any reviews?

2017-05-18 10:40 UTC, paglias submitted a review, later dismissed

2017-05-18 10:40 UTC, paglias commented on website/server/models/group.js
>        user.invitations.party = {};
this should be filled with any remaining invitation to other parties?

2017-05-21 01:23 UTC, Yutsuten commented on website/server/models/group.js
>        user.invitations.party = {};
Oh, yes. I'll change it.

2017-06-10 01:40 UTC, Yutsuten commented
Bump

2017-06-10 04:24 UTC, TheHollidayInn commented
It seems your tests are failing. We can review after those are fixed. I can't look at what is fsiling right now.

2017-06-10 21:48 UTC, Yutsuten commented
The error is:
```/home/travis/build/HabitRPG/habitica/website/client/components/inventory/item.vue```
 ```40:19  error  Missing trailing comma  comma-dangle```

But I haven't touched item.vue...

2017-06-11 13:26 UTC, paglias commented
@Yutsuten it may be an issue that already existed when you forked the develop branch. Can you try to update develop and merge it into your branch?

2017-06-13 01:27 UTC, Yutsuten commented
Strange... Other commits passed the tests...
Anyway, I updated my branch with develop.

2017-06-24 01:46 UTC, Yutsuten commented
Bump

2017-07-12 00:59 UTC, Yutsuten commented
Bump

2017-07-19 22:09 UTC, SabreCat approved these changes

2017-07-19 22:43 UTC, Alys commented
Did this end up not being a breaking change for the API? I.e., will all third-party tools that use the API with its current code still continue to work in exactly the same way after this is released?

If there's any changes to the API's interface or results, we'd want to announce this well in advance of it being merged.

I'm sorry, I know I should be able to work this out myself from looking at the code but I'm really short on time these days. :(

2017-07-19 22:56 UTC, SabreCat commented
@Alys Based on my read, there is one substantial difference: if you're checking for a party invite, you need to look through the `invitations.parties` array instead of the singular `invitations.party`. The server will handle the usual "send invitation" and "join group" actions without any changes to API calls, but if you fetch the user to check for invites, expectations will change there. We can discuss this in developer chat!

2017-07-19 23:06 UTC, SabreCat commented
Upon a further look, checking `invitations.party` will still work, as that will hold the most recent invite received: https://github.com/HabitRPG/habitica/pull/8683/files#diff-e10a9be49c74f4be55e32d817afeeee5R48

2017-07-19 23:51 UTC, SabreCat commented
One concern while testing: if you're already in a party, you get double confirm prompts--might be a bit of an annoyance?

2017-07-19 23:57 UTC, SabreCat commented
I'm OK with this as is, but will leave it Merge Pending for a bit in case other devs want to weigh in on the concerns above.

2017-07-20 01:45 UTC, SabreCat commented
Thanks for your effort and your patience with the review process, @Yutsuten! Welcome to Blacksmith tier 4!

2017-07-20 01:45 UTC, merged

2017-07-20 01:51 UTC, Yutsuten commented
Oh great!!