Althenis develop
HabitRPG/habitica pull request #8688
Opened 2017-04-20 15:23 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8145

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

A continuation of: https://github.com/HabitRPG/habitica/pull/8161. This also adds back sever checks for low gem amounts with unit tests now that we have abstracted the payments.

Credit goes to UUID: 5abc818d-baeb-4951-a66f-d6c1dba21305

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

2017-06-06 20:48 UTC, SabreCat requested changes
Pretty minor things remaining here. One locale file needing some chunks reverted, one question that may not need to be resolved at this time.

2017-06-06 20:48 UTC, SabreCat commented on website/common/locales/en/groups.json
> +  "askQuestionNewbiesGuild": "Ask a Question (Newbies Guild)",
There seem to be a bunch of unrelated edits to this string file, some of them (such as this) clearly incorrect. Mistake resolving a merge conflict?

2017-06-06 20:48 UTC, SabreCat commented on website/server/libs/amazonPayments.js
> +        throw new BadRequest(i18n.t('badAmountOfGemsToPurchase'));
We've been wanting not to have bare errors use translated strings IIRC--should this error message come from an API errors lib instead?

2017-06-23 17:43 UTC, TheHollidayInn commented on website/server/libs/amazonPayments.js
> +        throw new BadRequest(i18n.t('badAmountOfGemsToPurchase'));
Actually, we are using this on the front end as well, so maybe we just keep it in group translations for now?

2017-07-06 20:41 UTC, SabreCat approved these changes

2017-07-06 20:43 UTC, merged