Fixes apidoc error with Cast Skill
HabitRPG/habitica pull request #8709
Opened 2017-04-27 23:46 UTC by taldin

Changes Body to Query, changed example from  POST body  (per Blade in the Blacksmith's Guild)

2017-04-29 01:22 UTC, librarianmage requested changes

2017-04-29 01:22 UTC, MathWhiz commented on website/server/controllers/api-v3/user.js
> + *
There appears to be a trailing space here, which is why the Travis CI test is failing

2017-04-29 06:38 UTC, taldin commented
Okay, I think I fixed it.

2017-04-29 21:48 UTC, taldin commented
Hmm.  Apparently it's still failing.   I'm not sure how to fix it.

2017-04-29 23:46 UTC, Alys commented on website/server/controllers/api-v3/user.js
> + * @apiParam (Query) {UUID} targetId Query parameter, necessary if the spell is cast on a party member or task. Not used if the spell is case on onesself or the user's current party.
@taldin The test failure might be just a timeout. Can you please change this:
"Query parameter, necessary if the spell is cast on a party member or task. Not used if the spell is case on onesself or the user's current party."
to this:
"Query parameter, necessary if the skill is cast on a party member or task. Not used if the skill is cast on the user or the user's current party."
which will fix a couple of problems with the text and will also restart the tests. :)

2017-05-01 01:04 UTC, taldin commented
Well, it seems to be fixed now!

2017-05-01 01:04 UTC, MathWhiz commented
\o/

2017-05-11 21:40 UTC, taldin commented
Hrm.  I resolved the conflict with the develop branch and now it's failing the test again.

2017-05-23 20:06 UTC, merged

2017-05-23 20:07 UTC, TheHollidayInn commented
Noted towards your Tier! Thanks :D

2017-05-23 20:11 UTC, taldin commented
Thank ya!   Was there something I could have done to resolve that coveralls error?

2017-05-23 21:20 UTC, TheHollidayInn commented
Nah, just a small variation here. You didn't add code so you are good.