Client/equipment
HabitRPG/habitica pull request #8722
Opened 2017-05-09 19:59 UTC by negue

- extract strings to newClient.json
- add popovers to `use costume` and `auto equip`
- disable item selection with deactivated costume
- add error message on deactivated costume mode

2017-05-09 20:28 UTC, paglias requested changes

2017-05-09 20:28 UTC, paglias commented on website/client/components/inventory/drawer.vue
> +    top: calc(50% - 30px);
ohh this is cool, it's going to work in all browsers?

2017-05-09 20:28 UTC, paglias commented on website/client/components/inventory/equipment.vue
> +      if (!this.costume || this.user.preferences.costume) {
the starts are still going to show up with this I suppose, just not working. Maybe we should not show them at all?

2017-05-09 20:30 UTC, paglias requested changes

2017-05-09 20:30 UTC, paglias commented on website/client/components/inventory/equipment.vue
> +    drawer(:title="$t('equipment')", :errorMessage="(costume && !user.preferences.costume) ? $t('costumeDisabled') : ''")
I would pass null instead of empty string

2017-05-09 20:30 UTC, paglias commented on website/client/components/inventory/drawer.vue
> +        div.message(v-if="errorMessage != ''")
!errorMessage should work too

2017-05-10 21:41 UTC, negue commented on website/client/components/inventory/drawer.vue
> +    top: calc(50% - 30px);
it should http://caniuse.com/#feat=calc , back then the browsers need to have their own prefix but now all supports it

2017-05-10 21:42 UTC, negue commented on website/client/components/inventory/equipment.vue
> +      if (!this.costume || this.user.preferences.costume) {
I could hide it, but then maybe users ask "why are there isn't a star" -> "bug"

2017-05-11 20:15 UTC, negue commented on website/client/components/inventory/drawer.vue
> +        div.message(v-if="errorMessage != ''")
`!errorMessage` didn't work, had to use ` != null `

2017-05-11 20:15 UTC, negue commented on website/client/components/inventory/equipment.vue
> +      if (!this.costume || this.user.preferences.costume) {
star is now hidden

2017-05-13 19:36 UTC, closed without merging