Bug in Challenge: when editing any task that edit will save instantly instead of awaiting Save or Cancel
HabitRPG/habitica pull request #8723
Opened 2017-05-10 17:24 UTC by helenyau0

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: #8540 
Partial fix for https://github.com/HabitRPG/habitica/issues/8540

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
When a user creates a new challenge they are able to edit any of the above fields (title, description). However, if they add or make changes to the tasks below (habits, dailies, todos, and rewards) those changes will save instantly and clicking the cancel button will have no effect in discarding these changes because the "+" button does its own functionality when clicking it it will make a POST. The easiest fix to this problem was to add a warning message. That warning message is placed inside all the task templates warning users right away that adding any new task will get saved automatically and clicking the cancel button above will not revert any changes.   

![screen shot 2017-05-10 at 9 55 18 am](https://cloud.githubusercontent.com/assets/22210582/25910980/1710d1c2-3567-11e7-82fa-72447ca55660.png)

[//]: # (Put User ID in here - found in Settings -> API)
fda98da6-862b-4583-80ef-5ab81671875e
----
UUID:

2017-05-10 18:58 UTC, SabreCat commented
I like it. That would certainly have stopped me from the goof that prompted my posting that issue ticket. XD @Alys @lemoness any thoughts on the wording?

2017-05-10 21:45 UTC, Alys commented
Suggested wording:
"When you add a new task, it will be immediately saved to the challenge and given to all participants. Clicking the cancel button above will not revert your change."

I don't think the word "Warning" is needed. It makes it sound a bit like an error condition, rather than just advising the user of the behaviour.

2017-05-10 22:42 UTC, helenyau0 commented
@SabreCat @Alys thank you guys for responding back :) I will make those word changes now.

2017-05-12 00:53 UTC, librarianmage requested changes

2017-05-12 00:53 UTC, MathWhiz commented on website/views/shared/tasks/index.jade
> +          h5.tasks-warning When you add a new task, it will be immediately saved to the challenge and given to all participants. Clicking the cancel button above will not revert your change.
Shouldn't this be localized instead of put directly into the file?

2017-05-12 01:24 UTC, Alys commented on website/views/shared/tasks/index.jade
> +          h5.tasks-warning When you add a new task, it will be immediately saved to the challenge and given to all participants. Clicking the cancel button above will not revert your change.
Oh yes, good point. @helenyau0 If you're not sure how to do localised text (i.e., text that can be translated into the user's own language), have a look at line 28 inn this file, where it says `=env.t('dailiesRestingInInn')`. That's an example of how to insert text in a way that can be translated. `dailiesRestingInInn` is a string in [website/common/locales/en/tasks.json](https://github.com/HabitRPG/habitica/blob/develop/website/common/locales/en/tasks.json). For this string that you'd need to add, the `challenges.json` file in the same directory would be appropriate.

Also, can you please remove the blank spaces or tabs at the end of lines 10 and 25? You'll see them highlighted in dark green in [GitHub's diff](https://github.com/HabitRPG/habitica/pull/8723/files) for your change. It's a minor point but it helps to keep the code clean.

2017-06-06 21:08 UTC, TheHollidayInn commented
Looks good and works locally for me.

2017-06-06 21:50 UTC, SabreCat requested changes
Problem: under this PR, the warning appears on ALL task screens, not just Challenges. The warning should only appear in the Challenge create/edit context.

Suggestion: It'd look much better if the warning appeared once across the task columns, not repeated per every task type. Put a background behind it to draw attention.

2017-06-06 21:52 UTC, TheHollidayInn commented
Ah, I checked on challenges and group plans, my mistake. Should this appear on group plan tasks as well?

2017-06-06 22:03 UTC, SabreCat commented
You're only ever editing individual tasks in the group plan list, not a larger collection with top-level data, so I don't think it's applicable. (at least with current features!)

2017-06-06 22:52 UTC, TheHollidayInn commented
Makes sense!

2017-07-20 17:42 UTC, SabreCat commented
It's been a while since we've heard anything on this, and given this is a frontend change which will likely be invalidated by the Vue redesign in progress, I'm going to mark the source issue as On Hold and close this PR. @helenyau0, if you do get a chance to tidy things up, feel free to add commits and reopen the PR, and we can squeeze it in!

2017-07-20 17:42 UTC, closed without merging