[WIP] client/inventory/stable
HabitRPG/habitica pull request #8737
Opened 2017-05-17 20:33 UTC by negue

- [ ] Sidebar Filter
   - [x] Pets
   - [ ] Mounts
   - [ ] Hide Missing
   - [ ] Search
- [ ] Sort
  - [ ] Color
  - [ ] A-Z
  - [ ] Most Owned
  - [ ] Hatchable
- [ ] Select a
  - [ ] pet
  - [ ] mount
- [ ] feeding progress
- [ ] food drawer
  - [ ] drag food

**mentionable changes:**
- item component has now `popoverContent` and `itemContent` slots

2017-05-17 20:35 UTC, negue commented on website/client/components/inventory/equipment.vue
>            :item="flatGear[activeItems[group]]",
is there a way to create a temporary variable inside `v-for` so that we don't need to write `flatGear[...` all the time ^^

2017-05-18 08:28 UTC, paglias commented on website/client/components/inventory/equipment.vue
>            :item="flatGear[activeItems[group]]",
inside a v-for I don't think it's possible. You'd have to use a separate component

2017-05-18 08:29 UTC, paglias commented on website/client/components/inventory/stable.vue
> +        var petGroups = [
as this is a static array it should go in data not in computed

2017-05-18 08:30 UTC, paglias commented on website/client/components/inventory/stable.vue
> +        var petGroups = [
nevermind I see it uses viewOptions. But consider this way the array is recalculated every time and the viewOptions set here will be reset too

2017-05-20 18:45 UTC, negue commented on website/client/components/inventory/stable.vue
> +        var petGroups = [
if I move petGroups to data I don't have any content data yet

2017-06-12 10:44 UTC, paglias requested changes

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/countBadge.vue
> +  box-shadow: 0 1px 1px 0 rgba(26, 24, 29, 0.12);
rgba(26, 24, 29, 0.12); should be rgba($black, 0.12);

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/drawerSlider.vue
> +  box-shadow: 0 2px 2px 0 rgba(26, 24, 29, 0.16), 0 1px 4px 0 rgba(26, 24, 29, 0.12);
rgba($black, 0.XX)....

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/drawerSlider.vue
> +    background: linear-gradient(to left, rgba(gray, 0.01), $gray-50);
what does `gray` mean inside rgba?

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/drawerSlider.vue
> +        icons: {
not a big deal but since the icons' code doesn't change you can do `icons: Object.freeze(...)` it'll speed things up a little bit

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/index.vue
> +            h4.popover-content-title {{ $t('mattBoch') }}
v-once?

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/index.vue
> +            .popover-content-text {{ $t('mattBochText1') }}
v-once

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/index.vue
> +        b-dropdown.float-right(:text="$t('sortBy') +((selectedSortBy === 'standard')?'': ': '+ $t(selectedSortBy))", right=true)
not important but you can use ES6 in templates too, so ``string ${var}`` for example

2017-06-12 10:44 UTC, paglias commented on website/client/components/inventory/stable/index.vue
> +        title="Quick Inventory",
i18n string

2017-06-12 18:51 UTC, negue commented on website/client/components/inventory/stable/countBadge.vue
> +  box-shadow: 0 1px 1px 0 rgba(26, 24, 29, 0.12);
I just used the values from zeplin, but I can change that ^^

2017-06-12 18:59 UTC, negue commented on website/client/components/inventory/stable/drawerSlider.vue
> +        icons: {
is there a best practices for vuejs?, aren't data won't be updated anyway? I can add it but I'd like to know why this would speed it up

2017-06-12 19:22 UTC, negue commented on website/client/components/inventory/stable/drawerSlider.vue
> +    background: linear-gradient(to left, rgba(gray, 0.01), $gray-50);
its the normal css color

2017-06-12 19:43 UTC, paglias commented on website/client/components/inventory/stable/drawerSlider.vue
> +        icons: {
if you freeze the object Vue considers it an object that will never update so it'll work like plain data / v-once without listeners being added to it

2017-06-16 15:12 UTC, paglias requested changes

2017-06-16 15:12 UTC, paglias commented on website/client/assets/scss/dragdrop.scss
> +  cursor: -moz-grab;
Browser specific prefixes are added automatically by postcss during compilation

2017-06-16 15:12 UTC, paglias commented on website/client/assets/scss/dragdrop.scss
> +  cursor: -moz-grabbing;
same here

2017-06-23 11:24 UTC, merged