Yesterdailies 2
HabitRPG/habitica pull request #8805
Opened 2017-06-09 00:11 UTC by TheHollidayInn

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Replaces: #8717

Documentation of a discussion:

The way yesterdailies and cron will be changed. Essentially the following changes will be made:

- Cron is not checked/run on API calls automatically anymore. 
- Instead there will be a special API call /cron that runs it.
- all dailies are handled the same on the server regardless if they are yesterdailies or not.
- On the client side, 
     - the client checks if there are any uncompleted yesterdailies, 
     - displays those yesterdailies (if available), 
     - lets the user score the yesterdailies 
     - then runs the cron API call.

This change is made to later enable an offline mode for the mobile clients, so that they can score all tasks that were checked off when they were offline before cron is run.

2017-06-12 10:34 UTC, paglias requested changes

2017-06-12 10:34 UTC, paglias commented on website/server/models/task.js
> +  yesterDaily: {type: Boolean, default: true},
let's add a required flag here

2017-06-12 15:39 UTC, Alys commented on website/common/locales/en/tasks.json
> +    "yesterDailiesDescription": "Hover: If this setting is applied, Habitica will ask you if you meant to leave the Daily undone before calculating and applying damage to your avatar. This can protec
I think the word "Hover:" isn't meant to be there. :)

2017-06-12 16:54 UTC, TheHollidayInn commented on website/common/locales/en/tasks.json
> +    "yesterDailiesDescription": "Hover: If this setting is applied, Habitica will ask you if you meant to leave the Daily undone before calculating and applying damage to your avatar. This can protec
Lol copy and paste fail

2017-06-19 06:36 UTC, Alys commented
I've added some notes to the wiki about this to help third-party developers understand the changes and use them appropriately. It's in the "Information for Developers" section at the bottom of the [Dailies](http://habitica.wikia.com/wiki/Dailies#Information_for_Developers) page. By default that section will be hidden - there's a button to unhide it. @TheHollidayInn if you have time, would you like to review it in case I have some of the details wrong?

2017-07-05 20:04 UTC, merged