[WIP] Began adding tavern and party
HabitRPG/habitica pull request #8814
Opened 2017-06-12 05:34 UTC by TheHollidayInn

2017-06-12 10:33 UTC, paglias requested changes

2017-06-12 10:33 UTC, paglias commented on website/client/components/appMenu.vue
> +      router-link.nav-item(tag="li", :to="{name: 'market'}", exact)
I think market is now under shops, so this link can be removed

2017-06-12 10:33 UTC, paglias commented on website/client/components/appMenu.vue
> +      router-link.nav-item.dropdown(:to="{name: 'party'}", :class="{'active': $route.path.startsWith('/party')}")
is the :class binding necessary? It should work without it

2017-06-12 10:33 UTC, paglias commented on website/client/components/guilds/guild.vue
> +      this.guildId = 'habitrpg';
I think this is not anymore `habitrpg` but common/constants/TAVERN_ID

2017-06-12 10:33 UTC, paglias commented on website/client/router.js
> +    { name: 'market', path: '/market', component: Page },
shops

2017-06-12 10:33 UTC, paglias commented on website/client/router.js
> +    { name: 'party', path: '/party', component: GuildPage },
This is a duplicate, there's already a party entry in the router

2017-06-12 10:33 UTC, paglias commented on website/client/router.js
> +        { name: 'challenges', path: 'challenges', component: Page },
why challenges under user? also it's a duplicate, there's another challenge entry a few lines above

2017-06-12 10:33 UTC, paglias commented on website/client/router.js
> +      path: '/user',
this too seems a duplicate, maybe some type of conflict with `develop` but there's already an user entry

2017-06-12 12:38 UTC, TheHollidayInn commented on website/client/router.js
> +      path: '/user',
Yea, I think I just messed up when merging the routes. I'll take a look at develop and fix it.

2017-06-12 20:01 UTC, paglias commented on website/client/router.js
>        component: ParentPage,
outside the scope of this PR but this component should be changed with one that contains the submenu, will do when we implement the users views

2017-06-17 17:05 UTC, paglias commented on website/common/locales/en/newClient.json
> +  "facebook": "Facebook",
I don't think we should translate Facebook and Twitter

2017-06-17 23:15 UTC, TheHollidayInn commented on website/common/locales/en/newClient.json
> +  "facebook": "Facebook",
Ah, that makes sense haha

2017-06-22 18:30 UTC, paglias commented on website/client/assets/svg/quest-background-border.svg
> +    <g fill="#F9F9F9" fill-rule="evenodd">
just fyi, if you remove the fill attribute then you can style the icon with a css `color: XXXX`

2017-06-22 18:31 UTC, paglias commented on website/client/components/guilds/startQuestModal.vue
> +      this.group.quest = quest;
why both this.group and this.$store.party?

2017-06-22 18:35 UTC, TheHollidayInn commented on website/client/components/guilds/startQuestModal.vue
> +      this.group.quest = quest;
That is just from experimenting. I had local only, but then needed to share.

2017-06-27 20:02 UTC, merged

2017-06-28 08:37 UTC, paglias commented on website/client/components/guilds/createPartyModal.vue
> +    box-shadow: 0 2px 2px 0 rgba(26, 24, 29, 0.16), 0 1px 4px 0 rgba(26, 24, 29, 0.12);
$black

2017-06-28 08:38 UTC, paglias commented on website/client/components/guilds/groupFormModal.vue
> +          strong(v-once) Invite via Email or User ID
i18n

2017-06-28 08:38 UTC, paglias commented on website/client/components/guilds/membersModal.vue
>      background-color: #edecee;
color var

2017-06-28 08:38 UTC, paglias commented on website/client/components/guilds/membersModal.vue
> +      background-image: linear-gradient(to bottom, rgba(255, 255, 255, 0), #ffffff);
color vars

2017-06-28 08:38 UTC, paglias commented on website/client/components/guilds/membersModal.vue
> +    background-color: #ffffff;
color vars

2017-06-28 08:39 UTC, paglias reviewed
there are a lot of missing i18n strings / color vars + can we add TODOs for all the code that is commented but not implemented, otherwise I have no idea of what's done and what's missing