Explicitly configure HTTP request for PayPal
HabitRPG/habitica pull request #8896
Opened 2017-07-24 19:52 UTC by SabreCat

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8878

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Implements @Audiotuete's suggestion from https://github.com/HabitRPG/habitica/issues/8878#issuecomment-317247133, explicitly setting headers for the HTTP GET call to PayPal when sending a transaction.

Though this is a client-side fix, which would thus otherwise be on hold due to our frontend redesign underway, it addresses an issue blocking a revenue stream and is thus worthy of a hotfix.

[//]: # (Put User ID in here - found in Settings -> API)

2017-07-24 20:05 UTC, TheHollidayInn requested changes

2017-07-24 20:05 UTC, TheHollidayInn commented on website/client-old/js/services/paymentServices.js
> +    $http(req);
Let's return this just in case.

2017-07-24 20:14 UTC, TheHollidayInn approved these changes

2017-07-26 21:00 UTC, SabreCat commented
Implemented @Audiotuete's follow-up suggestion https://github.com/HabitRPG/habitica/issues/8878#issuecomment-317598329 . @TheHollidayInn, mind rechecking this? I've done a functional test and it does appear to address the issue.

2017-07-27 18:13 UTC, TheHollidayInn approved these changes

2017-07-27 18:31 UTC, merged

2017-07-27 18:33 UTC, SabreCat commented
@Audiotuete, what's your User ID in Habitica? I'd like to give you contributor credit for this, as you did the actual issue investigation, I only did the logistics of getting it into the code.

2017-07-27 20:13 UTC, Audiotuete commented
Thanks, my ID is:

ca8a6f62-d996-4f8a-a0eb-37bd7a3bc3a6


________________________________
Von: Sabe Jones <notifications@github.com>
Gesendet: Donnerstag, 27. Juli 2017 20:33
An: HabitRPG/habitica
Cc: Jan; Mention
Betreff: Re: [HabitRPG/habitica] Explicitly configure HTTP request for PayPal (#8896)


@Audiotuete<https://github.com/audiotuete>, what's your User ID in Habitica? I'd like to give you contributor credit for this, as you did the actual issue investigation, I only did the logistics of getting it into the code.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/HabitRPG/habitica/pull/8896#issuecomment-318448427>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AM-vM9_2A_t4dJfsypH0YQNSMt7hsVfcks5sSNfmgaJpZM4OhqF7>.

2017-07-27 20:47 UTC, SabreCat commented
@Audiotuete Blacksmith tier awarded! To get to Tier 2 you'll likely need to get your own PRs up and running, but we do appreciate the help!