Issue 9280: showEquipment on click
HabitRPG/habitica pull request #9312
Opened 2017-10-28 09:42 UTC by EmilyOng

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

#9280

2017-11-15 14:42 UTC, paglias requested changes

2017-11-15 14:42 UTC, paglias commented on website/client/components/avatar.vue
> +  script(src='https://unpkg.com/popper.js')
why did you add these new scripts? They're already available as npm packages

2017-11-15 14:42 UTC, paglias commented on website/client/components/avatar.vue
> +  new Vue({
this is creating a new vue instance, why?

2017-11-15 14:42 UTC, paglias commented on website/client/components/avatar.vue
> +      span(v-tooltip="showEquipments",:class="getGearClass('eyewear')")
if you pull the latest changes from develop, this should work without having to add new scripts

2017-12-13 03:50 UTC, MathWhiz commented
@EmilyOng Hello! How are you doing with this? It appears that @paglias has some questions about your PR, and it has a merge conflict. Would you be able to pull from develop?

2017-12-24 09:16 UTC, closed without merging