Copy-As-ToDo (Fixes #9302)
HabitRPG/habitica pull request #9328
Opened 2017-10-31 04:44 UTC by perkyguy

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes 9302

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
- Enabled the Copy To Task element for chat messages
- The Copy To Task component will now take in a copied message and create a task, and a notification
- The `group.vue` and `tavern.vue` files weren't binding the `group-name`, and so I fixed those real quick as well.

This **does not** add the functionality to the inbox. The change to have it work from there is trivial, but getting the modals to behave funny is another story. I will post my findings in the issue itself. 

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: e8be8049-ac14-401f-89ff-ce0aaa3445b4

2017-11-15 15:45 UTC, paglias requested changes

2017-11-15 15:45 UTC, paglias commented on website/client/components/chat/copyAsTodoModal.vue
> +      });
sorry for the delay reviewing this, the code looks good but can you make sure the `text` and `notes` in the modal get reset after the task is created? Thanks

2017-12-27 20:56 UTC, paglias commented
hey @perkyguy how are you doing on this?

2018-01-03 21:51 UTC, perkyguy commented
Sorry, had a bunch of things going on, hadn't gotten back to this. I'll take care of this soon. I know I was just having some issues getting my dev environment to work correctly (all of the menus were broken). I'll get to this (and my other PRs) fixed and resubmitted soon!

2018-02-09 08:40 UTC, paglias commented
I'm closing this since it seems to have been fixed elsewhere

2018-02-09 08:40 UTC, closed without merging