Added client side logging
HabitRPG/habitica pull request #9643
Opened 2017-12-03 21:14 UTC by TheHollidayInn

Fixes #6216

2017-12-04 10:09 UTC, paglias requested changes

2017-12-04 10:09 UTC, paglias commented on website/client/index.html
> +    <script type="text/javascript" src="//cloudfront.loggly.com/js/loggly.tracker-latest.min.js" async></script>
isn't this available as a npm package?

2017-12-07 14:45 UTC, TheHollidayInn commented
Yea.. Kind of. This library is for the front end. They have this: https://www.npmjs.com/package/loggly. But that is meant to be used with Winston which doesn't work on client side because of the fs module. 

Their docs says to use this on the front end (although it could just be old school). But the above allows to catch console errors globally.

2017-12-11 17:07 UTC, TheHollidayInn commented
I'm going to merge this for now, but if you think the npm package will work, let me know and I'll update it.

2017-12-11 17:07 UTC, merged