Keys kennel fixes
HabitRPG/habitica pull request #9848
Opened 2018-01-21 17:33 UTC by TheHollidayInn

Fixes #9243

- Add display of keys when you acquire all pets or mounts without refresh
- Remove keys after use without refresh
- Added redirect to stable after use
- Only show keys when you meat count requirements rather than achievement
- Added api calls

2018-01-21 17:36 UTC, paglias commented on website/client/components/shops/market/keysToKennel.vue
> +            axios.post('/api/v3/user/release-mounts');
can we make these actions?

2018-01-21 18:07 UTC, TheHollidayInn commented on website/client/components/shops/market/keysToKennel.vue
> +            axios.post('/api/v3/user/release-mounts');
Sure.

2018-02-21 22:01 UTC, SabreCat commented
Is there supposed to be a modal announcement when you reach the threshold / gain the achievement? Because none turned up for me.

2018-02-21 22:14 UTC, SabreCat commented
Price for Key to the Pet Kennels shows as 3 Gems, but with 3 Gems I'm prompted to buy Gems instead of being allowed to activate the Key.

2018-02-21 22:16 UTC, SabreCat commented
User's Beastmaster achievement does not update until after a hard refresh. Should we force a hard refresh after use of a Key?

2018-02-21 22:40 UTC, TheHollidayInn commented
There is no modal.

Can you screenshot what the addendum looks like? I'm not sure I addressed that in this PR. I thought the achievements were gained before this.

2018-02-22 00:13 UTC, SabreCat commented
![image](https://user-images.githubusercontent.com/4501321/36512990-d6f9c626-1732-11e8-8d47-93cf6e076fbd.png)

The achievement is awarded correctly--you're right, that's on the server side and unaffected by this. But the client doesn't show it until after a reload.

2018-02-22 17:07 UTC, SabreCat commented
Master Key is showing up prematurely. When I raise my last pet into a mount, both the Mount and Master keys appear, and the Pets key remains. (That last might be intentional, but the Master key behavior doesn't match test cases.)

2018-02-22 17:12 UTC, SabreCat commented
Price of each key should probably appear in the modal that shows up on click. I keep mistaking the Gems balance in the modal footer for the price.

2018-02-22 17:15 UTC, SabreCat commented
Key to the Pet Kennels is still available for me after releasing mounts, despite my not having any standard pets remaining.

2018-02-22 17:42 UTC, SabreCat requested changes
See comments for functional issues

2018-02-26 17:25 UTC, TheHollidayInn commented
Updated!

2018-03-02 21:24 UTC, SabreCat approved these changes

2018-03-02 21:30 UTC, merged

2018-03-15 21:45 UTC, DazoTrove commented
I saw this was deployed today, but the test cases above do not match how these used to work before the redesign. The Release Both (Master Keys to the Kennels) option became available for 6 gems after gaining 90 mounts, and it used to be free when you had 90 pets and 90 mounts (which grants the Triad Bingo achievement).

I think the test cases should be changed to the following, and changes should be made to support the free Master Keys to the Kennels when a player has all 90 pets and 90 mounts.

- Master Keys to the Kennels appears when getting your 90th mount (for 6 gems)
- Master Keys to the Kennels becomes free when getting your 90th pet while having all 90 mounts
- Master Keys to the Kennels removes all pets and mounts immediately and the key disappears