Partial Fix for #8735
HabitRPG/habitica pull request #9939
Opened 2018-02-03 19:57 UTC by Malcorr

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: #8735  (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Altered /test/api/v3/integration/groups/POST-groups_invite.test.js to reflect new output
Altered /website/common/locales/en/groups.json - Added username and UUID outputs to failed invites messages
Altered /website/server/controllers/api-v3/groups.js - sends username and uuid to error messages
Updated branch from main to fix merge conflicts from #9744 (orig PR) 

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 348b9f3a-83ef-4865-b4d1-8f64870c9734

2018-02-06 20:27 UTC, negue requested changes
Thanks for your fix 👍 

It works but it doesn't look that great for me, I mean the error json that is visible as toast.

I think we should also change the way our generic api errors are visible to the website.

See: https://github.com/HabitRPG/habitica/blob/develop/website/client/app.vue#L232

if `error.response.data.message` contains a value you could call `this.error(error.response.data.message);` otherwise use the current code.

That way all messages would be displayed  in a more readable kind

2018-02-06 20:27 UTC, negue commented on website/common/locales/en/groups.json
> +  "userAlreadyInAParty": "User \"<%= username %>\"  already in a party.\"<%= userId %>\"",
could you remove the extra space in the sentence, and add the user id in this way ` User-ID: {userId}`, that way people know it's the UserID and not a random number

2018-02-08 17:09 UTC, Malcorr commented
@negue Thank you for the review.  I am playing with the error messages right now, but could you explain more about the "this.error" portion of your suggested change?  Or point out a portion in the code where that is used, so I have something to compare that to?

2018-02-08 19:44 UTC, negue commented
`this.error` is a method from `mixins/notifications.js` which is mixed in with `vue`, that way you can use one of its method, here `this.error` .

 in `https://github.com/HabitRPG/habitica/blob/develop/website/client/app.vue#L233` you only have `error.response.data` but `.data` may have a message that why you also need to check if a message exists.

Once everything work we would see `User "test" already invit..`  instead of `{ok: false, message: "...` in an error notification

2018-02-09 00:53 UTC, Malcorr commented
So app.vue is where the error interceptor is, and I see where line 233 has the error.response.data.  Is this where we would check for, then possibly display any info in data.message?  Or would that be where the return is going back to?

2018-02-09 08:48 UTC, paglias commented
@Malcorr I would try to change line 233 so that to this:

```
          text: error.response.data && error.response.data.messages ? error.response.data.messages : error.response.data,
```

2018-02-09 08:50 UTC, paglias commented
It would be great if you could fix this too but actually it's a more generalized problem, see https://github.com/HabitRPG/habitica/issues/9841, not related to this PR in particular

2018-02-09 08:51 UTC, paglias commented
```
        const errorData = error.response.data;
        const errorMessage = errorData.message || errorData;

        this.$store.dispatch('snackbars:add', {
          title: 'Habitica',
          text: errorMessage,
          type: 'error',
          timeout: true,
        });
```

^ a bit better

2018-02-09 14:33 UTC, Malcorr commented
@paglias That fix seems to do it.  For readability, I am moving the UserID first, because it is about the length of the error display, so the first line will be "UserID:..." second line will read "User ""name" already..."

2018-02-09 14:48 UTC, paglias commented
Sounds good 👍

2018-02-09 21:12 UTC, Malcorr commented
Got a new error found by TravisCI, working with local build to find and fix source.

2018-02-09 21:34 UTC, paglias commented
It happens sometimes, I've restarted the build, not a problem with the pr

2018-02-09 22:01 UTC, Malcorr commented
Oh, good.  I couldn't figure out what I did.

2018-02-10 04:28 UTC, Malcorr commented
Had to fix merge conflict: app.vue line 421: "await this.castStart(this.selectedSpellToBuy, member);"

2018-02-10 19:19 UTC, negue commented
@Malcorr I guess you already fixed the conflict right? cause I can't see any in this PR

2018-02-19 18:00 UTC, merged

2018-02-19 18:00 UTC, paglias commented
@Malcorr  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!